#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^0.552 ^2.136 ^-0.281 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^0.552 ^2.14 ^-0.282 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^0.552 ^2.144 ^-0.282 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^0.552 ^2.147 ^-0.281 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^0.552 ^2.149 ^-0.28 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^0.552 ^2.15 ^-0.278 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^0.552 ^2.153 ^-0.27 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^0.552 ^2.157 ^-0.258 ~ ~