#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run tp @s ^0.552 ^2.161 ^-0.241 ~ ~
execute if score .this aj.fram matches 49 run tp @s ^0.552 ^2.165 ^-0.221 ~ ~
execute if score .this aj.fram matches 50 run tp @s ^0.552 ^2.169 ^-0.197 ~ ~
execute if score .this aj.fram matches 51 run tp @s ^0.552 ^2.171 ^-0.169 ~ ~
execute if score .this aj.fram matches 52 run tp @s ^0.552 ^2.171 ^-0.14 ~ ~
execute if score .this aj.fram matches 53 run tp @s ^0.552 ^2.169 ^-0.108 ~ ~
execute if score .this aj.fram matches 54 run tp @s ^0.552 ^2.164 ^-0.075 ~ ~
execute if score .this aj.fram matches 55 run tp @s ^0.552 ^2.157 ^-0.04 ~ ~