#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run tp @s ^0.552 ^2.25 ^0.198 ~ ~
execute if score .this aj.fram matches 65 run tp @s ^0.552 ^2.242 ^0.206 ~ ~
execute if score .this aj.fram matches 66 run tp @s ^0.552 ^2.175 ^0.211 ~ ~
execute if score .this aj.fram matches 67 run tp @s ^0.552 ^2.086 ^0.209 ~ ~
execute if score .this aj.fram matches 68 run tp @s ^0.552 ^1.979 ^0.202 ~ ~
execute if score .this aj.fram matches 69 run tp @s ^0.552 ^1.856 ^0.19 ~ ~
execute if score .this aj.fram matches 70 run tp @s ^0.552 ^1.721 ^0.173 ~ ~
execute if score .this aj.fram matches 71 run tp @s ^0.552 ^1.576 ^0.154 ~ ~