#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0 ^-0.25 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0 ^-0.219 ^0 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0 ^-0.183 ^0 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0 ^-0.141 ^0 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0 ^-0.094 ^0 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0 ^-0.044 ^0 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0 ^0.011 ^0 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0 ^0.069 ^0 ~ ~