#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 72 run tp @s ^0 ^0.786 ^0 ~ ~
execute if score .this aj.fram matches 73 run tp @s ^0 ^0.627 ^0 ~ ~
execute if score .this aj.fram matches 74 run tp @s ^0 ^0.47 ^0 ~ ~
execute if score .this aj.fram matches 75 run tp @s ^0 ^0.317 ^0 ~ ~
execute if score .this aj.fram matches 76 run tp @s ^0 ^0.172 ^0 ~ ~
execute if score .this aj.fram matches 77 run tp @s ^0 ^0.04 ^0 ~ ~
execute if score .this aj.fram matches 78 run tp @s ^0 ^-0.078 ^0 ~ ~
execute if score .this aj.fram matches 79 run tp @s ^0 ^-0.175 ^0 ~ ~