#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run tp @s ^0 ^1.62 ^0 ~ ~
execute if score .this aj.fram matches 49 run tp @s ^0 ^1.616 ^0 ~ ~
execute if score .this aj.fram matches 50 run tp @s ^0 ^1.61 ^0 ~ ~
execute if score .this aj.fram matches 51 run tp @s ^0 ^1.603 ^0 ~ ~
execute if score .this aj.fram matches 52 run tp @s ^0 ^1.596 ^0 ~ ~
execute if score .this aj.fram matches 53 run tp @s ^0 ^1.587 ^0 ~ ~
execute if score .this aj.fram matches 54 run tp @s ^0 ^1.577 ^0 ~ ~
execute if score .this aj.fram matches 55 run tp @s ^0 ^1.566 ^0 ~ ~