#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [-21.0296f,0f,0f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [-18.8671f,0f,0f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [-16.3759f,0f,0f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [-13.6103f,0f,0f]
execute if score .this aj.fram matches 52 run data modify entity @s Pose.Head set value [-10.6249f,0f,0f]
execute if score .this aj.fram matches 53 run data modify entity @s Pose.Head set value [-7.4742f,0f,0f]
execute if score .this aj.fram matches 54 run data modify entity @s Pose.Head set value [-4.2125f,0f,0f]
execute if score .this aj.fram matches 55 run data modify entity @s Pose.Head set value [-0.8944f,0f,0f]