#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run tp @s ^0.125 ^0.808 ^0 ~ ~
execute if score .this aj.fram matches 49 run tp @s ^0.125 ^0.803 ^0 ~ ~
execute if score .this aj.fram matches 50 run tp @s ^0.125 ^0.798 ^0 ~ ~
execute if score .this aj.fram matches 51 run tp @s ^0.125 ^0.791 ^0 ~ ~
execute if score .this aj.fram matches 52 run tp @s ^0.125 ^0.783 ^0 ~ ~
execute if score .this aj.fram matches 53 run tp @s ^0.125 ^0.774 ^0 ~ ~
execute if score .this aj.fram matches 54 run tp @s ^0.125 ^0.764 ^0 ~ ~
execute if score .this aj.fram matches 55 run tp @s ^0.125 ^0.753 ^0 ~ ~