#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 72 run data modify entity @s Pose.Head set value [-33.7256f,-5.8315f,-56.3603f]
execute if score .this aj.fram matches 73 run data modify entity @s Pose.Head set value [-31.4407f,-4.7906f,-47.8554f]
execute if score .this aj.fram matches 74 run data modify entity @s Pose.Head set value [-29.3509f,-3.8794f,-39.3201f]
execute if score .this aj.fram matches 75 run data modify entity @s Pose.Head set value [-27.4392f,-3.0782f,-30.9805f]
execute if score .this aj.fram matches 76 run data modify entity @s Pose.Head set value [-25.6894f,-2.3667f,-23.0603f]
execute if score .this aj.fram matches 77 run data modify entity @s Pose.Head set value [-24.0857f,-1.7241f,-15.782f]
execute if score .this aj.fram matches 78 run data modify entity @s Pose.Head set value [-22.6129f,-1.1296f,-9.3662f]
execute if score .this aj.fram matches 79 run data modify entity @s Pose.Head set value [-21.256f,-0.562f,-4.0325f]