#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run tp @s ^0.201 ^0.558 ^0.179 ~ ~
execute if score .this aj.fram matches 65 run tp @s ^0.198 ^0.553 ^0.178 ~ ~
execute if score .this aj.fram matches 66 run tp @s ^0.193 ^0.484 ^0.175 ~ ~
execute if score .this aj.fram matches 67 run tp @s ^0.187 ^0.391 ^0.169 ~ ~
execute if score .this aj.fram matches 68 run tp @s ^0.18 ^0.275 ^0.161 ~ ~
execute if score .this aj.fram matches 69 run tp @s ^0.172 ^0.142 ^0.151 ~ ~
execute if score .this aj.fram matches 70 run tp @s ^0.164 ^-0.004 ^0.139 ~ ~
execute if score .this aj.fram matches 71 run tp @s ^0.156 ^-0.16 ^0.125 ~ ~