#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64..71 run function emis:animations/calldown/tree/left_arm_display_64-71
execute if score .this aj.fram matches 72..79 run function emis:animations/calldown/tree/left_arm_display_72-79
execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [0f,0f,0f]