#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^0.185 ^0.468 ^0.159 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^0.186 ^0.476 ^0.165 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^0.187 ^0.482 ^0.169 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^0.188 ^0.487 ^0.173 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^0.189 ^0.489 ^0.175 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^0.189 ^0.49 ^0.176 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^0.189 ^0.488 ^0.174 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^0.187 ^0.483 ^0.169 ~ ~