#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run data modify entity @s Pose.Head set value [17.4401f,-28.9134f,0.1437f]
execute if score .this aj.fram matches 65 run data modify entity @s Pose.Head set value [16.6158f,-27.7768f,0.0926f]
execute if score .this aj.fram matches 66 run data modify entity @s Pose.Head set value [15.9264f,-26.6747f,-0.0021f]
execute if score .this aj.fram matches 67 run data modify entity @s Pose.Head set value [15.0751f,-25.2496f,-0.1308f]
execute if score .this aj.fram matches 68 run data modify entity @s Pose.Head set value [14.0776f,-23.5488f,-0.274f]
execute if score .this aj.fram matches 69 run data modify entity @s Pose.Head set value [12.9523f,-21.6205f,-0.4134f]
execute if score .this aj.fram matches 70 run data modify entity @s Pose.Head set value [11.7206f,-19.5145f,-0.5337f]
execute if score .this aj.fram matches 71 run data modify entity @s Pose.Head set value [10.4075f,-17.2814f,-0.6232f]