#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^-0.261 ^1.364 ^0.603 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^-0.287 ^1.39 ^0.606 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^-0.31 ^1.411 ^0.608 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^-0.332 ^1.431 ^0.607 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^-0.353 ^1.452 ^0.605 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^-0.375 ^1.478 ^0.602 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^-0.397 ^1.51 ^0.596 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^-0.403 ^1.534 ^0.593 ~ ~