#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [-45.7013f,-7.668f,11.1484f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [-46.4532f,-5.9791f,11.871f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [-47.2011f,-4.3409f,12.3678f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [-47.9396f,-2.7596f,12.6418f]
execute if score .this aj.fram matches 52 run data modify entity @s Pose.Head set value [-48.6613f,-1.2393f,12.6981f]
execute if score .this aj.fram matches 53 run data modify entity @s Pose.Head set value [-49.3579f,0.2186f,12.543f]
execute if score .this aj.fram matches 54 run data modify entity @s Pose.Head set value [-50.0192f,1.6145f,12.1837f]
execute if score .this aj.fram matches 55 run data modify entity @s Pose.Head set value [-50.6343f,2.9505f,11.6277f]