#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-58.2672f,-6.4827f,-15.067f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-35.0506f,-33.7013f,-16.7764f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-18.8414f,-49.2646f,-25.0884f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-15.7482f,-52.4568f,-32.3537f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-16.6833f,-54.2506f,-39.7793f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-21.6295f,-55.4102f,-46.395f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-30.3619f,-56.4417f,-51.3195f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-42.5163f,-57.4672f,-53.736f]