#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-101.4914f,25.2951f,-32.7548f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-102.8939f,25.6194f,-31.8327f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [-104.4273f,25.8238f,-30.7954f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-106.0766f,25.9195f,-29.6579f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [-107.8268f,25.9175f,-28.4349f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [-109.6631f,25.8289f,-27.1414f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [-111.5705f,25.6647f,-25.7924f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [-113.534f,25.436f,-24.4028f]