#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-0.7942f,0.5559f,0f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-1.7411f,1.2188f,0f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-2.8303f,1.9812f,0f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-4.0513f,2.8359f,0f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-5.3936f,3.7755f,0f]