#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 72 run data modify entity @s Pose.Head set value [16.6734f,10.9858f,-7.6909f]
execute if score .this aj.fram matches 73 run data modify entity @s Pose.Head set value [14.2796f,9.4676f,-6.3733f]
execute if score .this aj.fram matches 74 run data modify entity @s Pose.Head set value [11.8456f,7.8923f,-5.1248f]
execute if score .this aj.fram matches 75 run data modify entity @s Pose.Head set value [9.4331f,6.3072f,-3.9669f]
execute if score .this aj.fram matches 76 run data modify entity @s Pose.Head set value [7.1068f,4.762f,-2.916f]
execute if score .this aj.fram matches 77 run data modify entity @s Pose.Head set value [4.9331f,3.3074f,-1.9849f]
execute if score .this aj.fram matches 78 run data modify entity @s Pose.Head set value [2.9792f,1.9948f,-1.1832f]
execute if score .this aj.fram matches 79 run data modify entity @s Pose.Head set value [1.3125f,0.8755f,-0.5191f]