#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run tp @s ^-0.285 ^0.562 ^0.234 ~ ~
execute if score .this aj.fram matches 49 run tp @s ^-0.282 ^0.555 ^0.233 ~ ~
execute if score .this aj.fram matches 50 run tp @s ^-0.277 ^0.545 ^0.232 ~ ~
execute if score .this aj.fram matches 51 run tp @s ^-0.272 ^0.534 ^0.23 ~ ~
execute if score .this aj.fram matches 52 run tp @s ^-0.267 ^0.521 ^0.227 ~ ~
execute if score .this aj.fram matches 53 run tp @s ^-0.26 ^0.506 ^0.225 ~ ~
execute if score .this aj.fram matches 54 run tp @s ^-0.253 ^0.49 ^0.221 ~ ~
execute if score .this aj.fram matches 55 run tp @s ^-0.246 ^0.473 ^0.217 ~ ~