#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 72 run data modify entity @s Pose.Head set value [-73.2984f,22.4492f,-23.0132f]
execute if score .this aj.fram matches 73 run data modify entity @s Pose.Head set value [-62.0224f,19.0313f,-19.5328f]
execute if score .this aj.fram matches 74 run data modify entity @s Pose.Head set value [-50.8752f,15.6176f,-16.0336f]
execute if score .this aj.fram matches 75 run data modify entity @s Pose.Head set value [-40.0943f,12.2934f,-12.6112f]
execute if score .this aj.fram matches 76 run data modify entity @s Pose.Head set value [-29.9174f,9.1439f,-9.3613f]
execute if score .this aj.fram matches 77 run data modify entity @s Pose.Head set value [-20.5819f,6.2546f,-6.3795f]
execute if score .this aj.fram matches 78 run data modify entity @s Pose.Head set value [-12.3255f,3.7106f,-3.7616f]
execute if score .this aj.fram matches 79 run data modify entity @s Pose.Head set value [-5.3857f,1.5973f,-1.6032f]