#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run data modify entity @s Pose.Head set value [-25.1615f,17.6131f,0f]
execute if score .this aj.fram matches 65 run data modify entity @s Pose.Head set value [-23.1778f,16.2245f,0f]
execute if score .this aj.fram matches 66 run data modify entity @s Pose.Head set value [-21.2f,14.84f,0f]
execute if score .this aj.fram matches 67 run data modify entity @s Pose.Head set value [-19.2385f,13.4669f,0f]
execute if score .this aj.fram matches 68 run data modify entity @s Pose.Head set value [-17.3038f,12.1127f,0f]
execute if score .this aj.fram matches 69 run data modify entity @s Pose.Head set value [-15.4064f,10.7845f,0f]
execute if score .this aj.fram matches 70 run data modify entity @s Pose.Head set value [-13.5569f,9.4898f,0f]
execute if score .this aj.fram matches 71 run data modify entity @s Pose.Head set value [-11.7656f,8.2359f,0f]