#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-6.8466f,4.7927f,0f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-8.4f,5.88f,0f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-10.0431f,7.0302f,0f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-11.7656f,8.2359f,0f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-13.5569f,9.4898f,0f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-15.4064f,10.7845f,0f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-17.3038f,12.1127f,0f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-19.2385f,13.4669f,0f]