#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [-0.5137f,0f,0f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [-1.26f,0f,0f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [-2.1713f,0f,0f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [-3.18f,0f,0f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [-4.2188f,0f,0f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [-5.22f,0f,0f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [-6.1162f,0f,0f]