#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^0.552 ^0.4 ^-0.069 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^0.552 ^0.4 ^-0.067 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^0.552 ^0.401 ^-0.064 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^0.552 ^0.401 ^-0.061 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^0.552 ^0.401 ^-0.059 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^0.552 ^0.401 ^-0.056 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^0.552 ^0.402 ^-0.054 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^0.552 ^0.402 ^-0.051 ~ ~