#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-6.84f,0f,0f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-7.3237f,0f,0f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-7.5f,0f,0f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-7.4885f,0f,0f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-7.4545f,0f,0f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-7.3993f,0f,0f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-7.3237f,0f,0f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-7.229f,0f,0f]