#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^0.137 ^-1.36 ^0.105 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^0.138 ^-1.358 ^0.111 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^0.138 ^-1.357 ^0.116 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^0.139 ^-1.355 ^0.12 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^0.139 ^-1.354 ^0.124 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^0.139 ^-1.353 ^0.127 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^0.139 ^-1.352 ^0.13 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^0.139 ^-1.351 ^0.132 ~ ~