#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.14 ^-1.35 ^0.134 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.14 ^-1.35 ^0.136 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.14 ^-1.349 ^0.137 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.14 ^-1.349 ^0.138 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.14 ^-1.349 ^0.138 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.14 ^-1.349 ^0.138 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.14 ^-1.349 ^0.138 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^0.14 ^-1.349 ^0.137 ~ ~