#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.366 ^-0.394 ^0.348 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.36 ^-0.356 ^0.362 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.355 ^-0.331 ^0.369 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.352 ^-0.321 ^0.372 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.35 ^-0.323 ^0.371 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.348 ^-0.334 ^0.369 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.348 ^-0.353 ^0.364 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.348 ^-0.376 ^0.357 ~ ~