#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-20.9731f,1.1738f,-2.844f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-21.2394f,1.1887f,-2.8801f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-21.4391f,1.1999f,-2.9072f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-21.5723f,1.2073f,-2.9252f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-21.6389f,1.2111f,-2.9343f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-21.6389f,1.2111f,-2.9343f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-21.5723f,1.2073f,-2.9252f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-21.4391f,1.1999f,-2.9072f]