#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [-5.0362f,0.2656f,-0.3614f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [-12.086f,0.6182f,-0.8786f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [-20.6165f,1.0389f,-1.5078f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [-30.0949f,1.509f,-2.2054f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [-39.9886f,2.0098f,-2.9277f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [-49.7647f,2.5226f,-3.6309f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [-58.8904f,3.0287f,-4.2713f]