#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-7.235f,0.4049f,-0.9811f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-8.4208f,0.4713f,-1.1419f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-9.621f,0.5385f,-1.3046f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-10.8212f,0.6056f,-1.4674f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-12.007f,0.672f,-1.6282f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-13.1639f,0.7367f,-1.785f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-14.2775f,0.7991f,-1.9361f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-15.3334f,0.8582f,-2.0792f]