#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [9.2789f,0.8799f,-2.1318f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [9.2904f,0.7897f,-1.9133f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [8.8333f,0.6921f,-1.6769f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [8.005f,0.5902f,-1.4299f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [6.903f,0.4867f,-1.1793f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [5.6247f,0.3848f,-0.9323f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [4.2676f,0.2872f,-0.696f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [2.9292f,0.1971f,-0.4774f]