#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-16.3172f,0.9132f,-2.2126f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-17.2143f,0.9634f,-2.3343f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-18.0105f,1.008f,-2.4422f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-18.6911f,1.0461f,-2.5346f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-19.2419f,1.0769f,-2.6092f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-19.7746f,1.1067f,-2.6815f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-20.2407f,1.1328f,-2.7447f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-20.6402f,1.1552f,-2.7988f]