#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [0.1648f,0.0308f,-0.0747f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [0.3685f,0.0689f,-0.167f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [0.6068f,0.1135f,-0.2749f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [0.8752f,0.1637f,-0.3966f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [1.1696f,0.2187f,-0.53f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [1.4856f,0.2778f,-0.6732f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [1.8188f,0.3402f,-0.8242f]