#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^0.356 ^-0.521 ^0.264 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^0.36 ^-0.54 ^0.242 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^0.364 ^-0.559 ^0.216 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^0.368 ^-0.577 ^0.187 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^0.371 ^-0.592 ^0.157 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^0.373 ^-0.604 ^0.125 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^0.375 ^-0.613 ^0.094 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^0.375 ^-0.62 ^0.065 ~ ~