#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [27.8837f,-3.4586f,2.6403f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [36.4047f,-4.0729f,1.5322f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [43.023f,-4.0607f,0.4477f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [48.0621f,-3.5758f,-0.4315f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [51.8552f,-2.8015f,-0.9887f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [54.7438f,-1.9265f,-1.186f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [57.0718f,-1.1163f,-1.0642f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [59.1787f,-0.4893f,-0.729f]