#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.327 ^-0.503 ^0.67 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.331 ^-0.425 ^0.694 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.336 ^-0.369 ^0.704 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.341 ^-0.339 ^0.708 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.348 ^-0.328 ^0.707 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.356 ^-0.333 ^0.705 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^-0.365 ^-0.35 ^0.701 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^-0.375 ^-0.375 ^0.695 ~ ~