#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-96.7569f,76.3699f,-89.0283f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [173.4924f,76.4821f,-88.8897f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [83.7164f,76.8669f,-88.8003f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-6.0917f,77.5687f,-88.7657f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [-95.9443f,78.6323f,-88.7966f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [-12.3946f,3.0414f,3.9705f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [3.8319f,0.0443f,4.0577f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [17.1378f,-2.1085f,3.5545f]