#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-57.5202f,3.4841f,4.6387f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-57.9866f,3.5372f,4.7139f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-58.5377f,3.5703f,4.7578f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-59.1287f,3.5849f,4.7733f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-59.7148f,3.5824f,4.7632f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-60.2514f,3.5644f,4.73f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-60.6937f,3.5323f,4.6767f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-60.997f,3.4877f,4.606f]