#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [-84.2004f,2.4849f,3.244f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [-77.6628f,2.2302f,2.9115f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [-70.7333f,1.9547f,2.5518f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [-63.5687f,1.6667f,2.1759f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [-56.3258f,1.3746f,1.7946f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [-49.1612f,1.0867f,1.4187f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [-42.2318f,0.8112f,1.059f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [-35.6942f,0.5565f,0.7265f]