#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^-0.124 ^-1.33 ^0.18 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^-0.124 ^-1.33 ^0.179 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^-0.124 ^-1.331 ^0.178 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^-0.124 ^-1.332 ^0.176 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^-0.124 ^-1.333 ^0.174 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^-0.124 ^-1.334 ^0.172 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^-0.125 ^-1.335 ^0.169 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^-0.125 ^-1.337 ^0.166 ~ ~