#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.375 ^-0.625 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.373 ^-0.625 ^0.031 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.369 ^-0.619 ^0.075 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.364 ^-0.606 ^0.125 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.359 ^-0.583 ^0.179 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.354 ^-0.55 ^0.23 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^-0.35 ^-0.51 ^0.275 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.348 ^-0.466 ^0.311 ~ ~