#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [1.4296f,-0.2231f,0.1002f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [0.6019f,-0.0939f,0.0422f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [0f,0f,0f]