#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [-46.8927f,2.4849f,3.244f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [-42.0859f,2.2302f,2.9115f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [-36.8872f,1.9547f,2.5518f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [-31.4534f,1.6667f,2.1759f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [-25.9412f,1.3746f,1.7946f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [-20.5074f,1.0867f,1.4187f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [-15.3087f,0.8112f,1.059f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [-10.5019f,0.5565f,0.7265f]