#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-66.8632f,0.8554f,0.5612f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-63.7865f,1.5449f,1.6376f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-60.973f,2.166f,2.6076f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-58.7375f,2.6783f,3.4068f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-57.3946f,3.0414f,3.9705f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-57.0755f,3.1896f,4.1982f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-57.0199f,3.3118f,4.3836f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-57.183f,3.4095f,4.5295f]