#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-27.6424f,-1.5849f,0.712f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-27.9943f,-1.6051f,0.7211f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-28.2823f,-1.6216f,0.7285f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-28.5062f,-1.6345f,0.7343f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-28.6662f,-1.6436f,0.7384f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-28.7622f,-1.6491f,0.7409f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-28.7942f,-1.651f,0.7417f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-28.7622f,-1.6491f,0.7409f]