#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [-6.2436f,0.3309f,0.4319f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [-2.6908f,0.1426f,0.1861f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [0f,0f,0f]