#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0..7 run function emis:animations/f_tp/tree/right_leg_root_0-7
execute if score .this aj.fram matches 8 run tp @s ^-0.123 ^-1.094 ^-0.024 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.124 ^-1.047 ^-0.012 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.125 ^-1 ^0 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.125 ^-1 ^0 ~ ~