#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0..7 run function emis:animations/f_tp/tree/right_arm_root_0-7
execute if score .this aj.fram matches 8 run tp @s ^-0.306 ^-0.344 ^-0.061 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.311 ^-0.297 ^-0.031 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.312 ^-0.25 ^0 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.312 ^-0.25 ^0 ~ ~