#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0..7 run function emis:animations/f_tp/tree/right_arm2_root_0-7
execute if score .this aj.fram matches 8 run tp @s ^-0.372 ^-0.693 ^-0.198 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.376 ^-0.665 ^-0.1 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.375 ^-0.625 ^0 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.375 ^-0.625 ^0 ~ ~