#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [116.3449f,-28.9977f,-173.9127f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [116.4726f,-27.5714f,-174.1384f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [116.5723f,-26.3417f,-174.3232f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [116.639f,-25.3613f,-174.4815f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [116.6478f,-24.8571f,-174.619f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [116.6478f,-24.8571f,-174.619f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [106.6484f,-35.7424f,-134.1972f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [47.1571f,-38.3802f,-59.0497f]