#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.277 ^-1.331 ^-0.543 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.288 ^-1.354 ^-0.626 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.295 ^-1.379 ^-0.709 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.28 ^-1.377 ^-0.723 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.267 ^-1.375 ^-0.735 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.254 ^-1.374 ^-0.745 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.242 ^-1.372 ^-0.754 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.23 ^-1.371 ^-0.762 ~ ~