#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-6.716f,-27.6284f,0.9915f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-6.8207f,-30.3748f,1.0148f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-7.5289f,-32.4454f,0.998f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-8.6544f,-34.0312f,0.9506f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-10.0842f,-35.2472f,0.879f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-11.7436f,-36.1679f,0.7884f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-13.5788f,-36.8439f,0.6828f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-15.5454f,-37.3133f,0.5662f]