#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0.375 ^-0.625 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0.375 ^-0.625 ^0.014 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0.375 ^-0.621 ^0.055 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0.375 ^-0.61 ^0.107 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0.375 ^-0.596 ^0.146 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0.375 ^-0.59 ^0.158 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.372 ^-0.658 ^-0.13 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0.353 ^-0.698 ^-0.266 ~ ~