#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.125 ^-1.375 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.123 ^-1.375 ^0.021 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.12 ^-1.372 ^0.051 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.121 ^-1.366 ^0.084 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.13 ^-1.359 ^0.111 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.147 ^-1.353 ^0.126 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^-0.271 ^-1.352 ^0.103 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.287 ^-1.368 ^0.063 ~ ~