#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.091 ^-1.156 ^0.419 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.083 ^-1.103 ^0.449 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.075 ^-1.053 ^0.468 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.069 ^-1.012 ^0.48 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.064 ^-0.98 ^0.487 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.06 ^-0.958 ^0.486 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.055 ^-0.943 ^0.486 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.048 ^-0.935 ^0.485 ~ ~