#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [16.7159f,18.6648f,-20.0703f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [17.9982f,20.8055f,-23.0625f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [18.9467f,22.599f,-25.8168f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [19.5992f,24.0047f,-28.1817f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [20.0066f,24.9996f,-29.9947f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [20.1164f,25.7984f,-31.2707f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [19.9064f,26.6035f,-32.1647f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [19.4747f,27.3781f,-32.7201f]