#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [20.9912f,13.1812f,-15.6049f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [20.9371f,13.9815f,-15.7806f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [20.7918f,14.7528f,-15.8297f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [20.5907f,15.3748f,-15.7495f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [20.3673f,15.7227f,-15.537f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [20.1491f,15.669f,-15.1931f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [19.9551f,15.0853f,-14.7257f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [19.7939f,13.8445f,-14.1525f]