#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.555 ^-0.5 ^0.105 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.642 ^-0.46 ^0.112 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.691 ^-0.515 ^0.085 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.687 ^-0.601 ^0.087 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.627 ^-0.684 ^0.055 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.589 ^-0.68 ^0.051 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.627 ^-0.684 ^0.055 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^0.578 ^-0.691 ^0.015 ~ ~