#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.283 ^-0.25 ^0.195 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.387 ^-0.222 ^0.264 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.487 ^-0.297 ^0.32 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.562 ^-0.404 ^0.387 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.568 ^-0.5 ^0.383 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.57 ^-0.522 ^0.396 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.568 ^-0.5 ^0.383 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^0.454 ^-0.375 ^0.187 ~ ~