#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.119 ^-1 ^0.079 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.118 ^-1 ^0.089 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.116 ^-1 ^0.099 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.114 ^-1 ^0.108 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.113 ^-1 ^0.115 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.112 ^-1 ^0.117 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.111 ^-1 ^0.12 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.11 ^-1 ^0.122 ~ ~