#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [20.0066f,24.9996f,-29.9947f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [27.7767f,15.226f,-29.315f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [39.1727f,1.187f,-29.9993f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [51.4503f,-12.3099f,-32.5943f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [60.8346f,-21.0569f,-35.6367f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [69.048f,-24.0787f,-39.2579f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [60.8346f,-21.0569f,-35.6367f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [25.6226f,-12.715f,-17.0437f]