#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0.125 ^-1 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0.125 ^-1 ^0.008 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0.125 ^-1 ^0.017 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0.125 ^-1 ^0.027 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0.124 ^-1 ^0.037 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0.123 ^-1 ^0.048 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.122 ^-1 ^0.058 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0.121 ^-1 ^0.069 ~ ~