#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [0f,33.4259f,0f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [0f,37.8516f,0f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [0f,41.7824f,0f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [0f,45.0535f,0f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [0f,47.5f,0f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-0.0637f,49.4336f,0f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-0.2315f,51.2326f,0f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-0.4688f,52.832f,0f]