#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.273 ^-0.25 ^-0.089 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.271 ^-0.25 ^-0.093 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.27 ^-0.25 ^-0.095 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.269 ^-0.25 ^-0.096 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.27 ^-0.25 ^-0.095 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^-0.271 ^-0.25 ^-0.093 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^-0.274 ^-0.25 ^-0.088 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.278 ^-0.25 ^-0.08 ~ ~