#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.375 ^-0.625 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.412 ^-0.617 ^0.003 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.46 ^-0.601 ^0.002 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.515 ^-0.572 ^-0.004 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.569 ^-0.529 ^-0.015 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.617 ^-0.472 ^-0.031 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^-0.653 ^-0.404 ^-0.049 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.673 ^-0.33 ^-0.066 ~ ~