#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [-20f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [-11.4152f,6.3443f,14.2927f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [1.3039f,14.8603f,33.529f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [18.4082f,24.349f,57.4894f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [39.5895f,33.0511f,86.1488f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [63.0784f,39.5095f,118.4303f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [85.5306f,43.9157f,151.4194f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [104.1948f,48.2101f,-178.0771f]