#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^-0.283 ^-0.25 ^-0.07 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^-0.223 ^-0.222 ^0.126 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^-0.136 ^-0.297 ^0.375 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^-0.014 ^-0.404 ^0.629 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.057 ^-0.5 ^0.742 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.098 ^-0.522 ^0.806 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.057 ^-0.5 ^0.742 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^-0.142 ^-0.375 ^0.375 ~ ~