#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [2.6983f,9.239f,80.3878f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [3.3766f,6.8496f,90.798f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [3.4261f,4.0431f,99.7927f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [2.9766f,1.296f,107.1019f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [2.3111f,-0.957f,112.4794f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [2.0149f,-2.6449f,116.2533f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [2.3673f,-3.9591f,118.9969f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [3.2356f,-4.9128f,120.8172f]