#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.677 ^-0.255 ^-0.08 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.667 ^-0.186 ^-0.089 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.648 ^-0.127 ^-0.092 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.626 ^-0.081 ^-0.089 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.605 ^-0.049 ^-0.084 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.589 ^-0.028 ^-0.085 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^-0.575 ^-0.013 ^-0.091 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^-0.564 ^-0.004 ^-0.101 ~ ~