#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [0f,47.5f,0f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [20.01f,32.0165f,0.0562f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [41.8946f,8.535f,0.4685f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [63.3113f,-15.0277f,1.2827f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [82.2934f,-30.6716f,2.4848f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [84.1171f,-38.4096f,3.1031f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [82.2934f,-30.6716f,2.4848f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [73.44f,-11.6777f,0.9456f]