#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [109.9542f,86.7859f,-129.9933f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-108.4486f,69.7171f,1.252f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-96.594f,34.968f,-2.9362f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-83.8818f,0.3632f,-13.2746f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-69.3904f,-20.7135f,-26.3008f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-58.3247f,-34.4684f,-29.1861f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-60.0685f,-16.0428f,-29.2482f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-16.9372f,59.5909f,30.0802f]