#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.552 ^0.388 ^-0.024 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.552 ^0.388 ^-0.015 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.552 ^0.388 ^-0.007 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.553 ^0.388 ^0.001 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.552 ^0.388 ^0.007 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.552 ^0.388 ^0.013 ~ ~