#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^0 ^-0.266 ^0 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^0 ^-0.266 ^0 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^0 ^-0.266 ^0 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^0 ^-0.266 ^0 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^0 ^-0.266 ^0 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^0 ^-0.266 ^0 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^0 ^-0.266 ^0 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^0 ^-0.266 ^0 ~ ~