#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [0f,0.76f,0f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [0f,1.6667f,0f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [0f,2.5289f,0f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [0f,3.32f,0f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [0f,4.0133f,0f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [0f,4.5822f,0f]