#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-10.3587f,-4.8836f,0.2148f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-11.3486f,-4.5681f,0.2039f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-12.8935f,-4.0778f,0.1878f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-14.9081f,-3.4427f,0.1679f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-17.3073f,-2.6925f,0.1459f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-20.0055f,-1.8569f,0.1233f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-22.9168f,-0.9648f,0.1013f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-25.9543f,-0.0446f,0.0808f]