#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [-11.25f,5f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [-9.9288f,4.5841f,-0.0276f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [-8.1318f,4.0177f,-0.0659f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [-5.9448f,3.3274f,-0.1136f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [-3.4536f,2.5398f,-0.1689f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [-0.7437f,1.6813f,-0.2297f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [2.1001f,0.7786f,-0.2936f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [4.9935f,-0.1418f,-0.3581f]