#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.377 ^-0.641 ^-0.025 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.375 ^-0.641 ^-0.021 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.372 ^-0.64 ^-0.016 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.369 ^-0.639 ^-0.012 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.365 ^-0.637 ^-0.008 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.361 ^-0.635 ^-0.005 ~ ~