#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^0.358 ^-0.619 ^-0.052 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^0.36 ^-0.621 ^-0.051 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^0.363 ^-0.624 ^-0.049 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^0.367 ^-0.627 ^-0.046 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^0.371 ^-0.631 ^-0.043 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^0.374 ^-0.634 ^-0.039 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^0.376 ^-0.637 ^-0.035 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^0.377 ^-0.639 ^-0.03 ~ ~