#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [30.5333f,-4.8933f,0f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [32.0444f,-4.5911f,0f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [34.4f,-4.12f,0f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [37.4667f,-3.5067f,0f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [41.1111f,-2.7778f,0f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [45.2f,-1.96f,0f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [49.6f,-1.08f,0f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [54.1778f,-0.1644f,0f]