#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [80f,5f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [77.9111f,4.5822f,0f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [75.0667f,4.0133f,0f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [71.6f,3.32f,0f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [67.6444f,2.5289f,0f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [63.3333f,1.6667f,0f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [58.8f,0.76f,0f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [54.1778f,-0.1644f,0f]