#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [8.2465f,-1.0774f,0.0343f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [9.6967f,-1.9592f,0.0386f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [10.9291f,-2.779f,0.043f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [14.2178f,-3.5059f,0.0319f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [18.6922f,-4.1115f,0.0085f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [23.6797f,-4.5751f,-0.0133f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [28.5067f,-4.8775f,-0.0205f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [32.5f,-5f,0f]