#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0..7 run function emis:animations/walk/tree/right_arm2_root_0-7
execute if score .this aj.fram matches 8 run tp @s ^-0.375 ^-0.594 ^0.011 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.381 ^-0.591 ^0.101 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.39 ^-0.575 ^0.154 ~ ~