#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.353 ^-0.614 ^0.067 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.355 ^-0.616 ^0.065 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.359 ^-0.62 ^0.062 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.363 ^-0.624 ^0.058 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.367 ^-0.629 ^0.053 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^-0.371 ^-0.633 ^0.047 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^-0.373 ^-0.637 ^0.041 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.375 ^-0.639 ^0.034 ~ ~