#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.132 ^-1.369 ^0.16 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.131 ^-1.372 ^0.149 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.13 ^-1.376 ^0.133 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.128 ^-1.38 ^0.113 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.127 ^-1.384 ^0.09 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.126 ^-1.387 ^0.065 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^-0.125 ^-1.39 ^0.039 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.125 ^-1.391 ^0.012 ~ ~