#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.552 ^0.826 ^-0.023 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.552 ^0.841 ^-0.021 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.552 ^0.857 ^-0.02 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.552 ^0.871 ^-0.019 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.552 ^0.884 ^-0.018 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.552 ^0.895 ^-0.018 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.552 ^0.901 ^-0.018 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^0.552 ^0.904 ^-0.018 ~ ~