#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^0 ^0.207 ^0 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^0 ^0.196 ^0 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^0 ^0.189 ^0 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^0 ^0.187 ^0 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^0 ^0.273 ^0 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^0 ^0.312 ^0 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^0 ^0.219 ^0 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^0 ^0.07 ^0 ~ ~