#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [6.2439f,0.7362f,0f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [15.2859f,1.7906f,0f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [25.984f,3.0394f,0f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [37.1963f,4.3586f,0f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [47.781f,5.6244f,0f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [56.5962f,6.7128f,0f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [62.5f,7.5f,0f]