#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.125 ^-0.49 ^0 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.125 ^-0.488 ^0 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.125 ^-0.494 ^0 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.125 ^-0.505 ^0 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.125 ^-0.521 ^0 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.125 ^-0.54 ^0 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.125 ^-0.559 ^0 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.125 ^-0.579 ^0 ~ ~