#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^0.189 ^-0.828 ^0.175 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^0.189 ^-0.836 ^0.173 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^0.189 ^-0.848 ^0.169 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^0.189 ^-0.864 ^0.164 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^0.189 ^-0.881 ^0.159 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^0.188 ^-0.9 ^0.152 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^0.186 ^-0.919 ^0.145 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^0.184 ^-0.937 ^0.138 ~ ~