#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [15.7322f,-26.027f,0.0421f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [16.4017f,-26.813f,0.0215f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [17.0122f,-27.3867f,-0.0562f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [17.5648f,-27.775f,-0.1809f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [18.0582f,-28.0053f,-0.3398f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [18.4898f,-28.1051f,-0.5186f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [18.8573f,-28.1032f,-0.7028f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [19.1584f,-28.0297f,-0.8786f]