#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [59.1471f,8.3984f,0f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [58.015f,8.3681f,0f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [57.235f,8.3435f,0f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [56.9444f,8.3333f,0f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [57.0538f,8.3169f,0f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [57.356f,8.2716f,0f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [57.8125f,8.2031f,0f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [58.3848f,8.1173f,0f]