#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-20.4061f,49.3142f,0f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-21.8557f,50.7986f,0f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [-23.8281f,51.9531f,0f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-26.0802f,52.7778f,0f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [-28.369f,53.2726f,0f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [-30.4514f,53.4375f,0f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [-32.0843f,53.2726f,0f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [-33.0247f,52.7778f,0f]