#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-150.2539f,16.4209f,0f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-149.9248f,18.8296f,0f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-149.4133f,21.2795f,0f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-148.75f,23.75f,0f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-147.9651f,26.2205f,0f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-147.0891f,28.6704f,0f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-146.1523f,31.0791f,0f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-145.1852f,33.4259f,0f]