#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [-10.0551f,4.5826f,1.3066f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [0f,0f,0f]