#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-154.9151f,49.3142f,0f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-156.1188f,50.7986f,0f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [-157.8125f,51.9531f,0f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-159.7531f,52.7778f,0f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [-161.6975f,53.2726f,0f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [-163.4028f,53.4375f,0f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [-164.6258f,53.2726f,0f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [-165.1235f,52.7778f,0f]