#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.125 ^-1.375 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.128 ^-1.32 ^0.058 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.144 ^-1.224 ^0.139 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.178 ^-1.087 ^0.22 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.227 ^-0.922 ^0.282 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.278 ^-0.751 ^0.313 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^-0.318 ^-0.601 ^0.317 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.34 ^-0.5 ^0.307 ~ ~