#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^-0.534 ^0.536 ^0.108 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^-0.532 ^0.534 ^0.099 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^-0.528 ^0.531 ^0.089 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^-0.521 ^0.525 ^0.08 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^-0.513 ^0.517 ^0.072 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^-0.506 ^0.508 ^0.066 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^-0.5 ^0.496 ^0.062 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^-0.498 ^0.483 ^0.062 ~ ~