#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [13.444f,27.325f,-18.0625f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [13.542f,27.3783f,-17.8624f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [13.6316f,27.4453f,-17.6755f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [13.709f,27.5213f,-17.511f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [13.772f,27.5988f,-17.3756f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [13.819f,27.6678f,-17.2741f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [13.8486f,27.7171f,-17.21f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [13.859f,27.7356f,-17.1874f]