#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [13.8965f,27.7275f,-17.2311f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [13.9967f,27.6956f,-17.344f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [14.1423f,27.6247f,-17.4965f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [14.3156f,27.5034f,-17.6615f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [14.495f,27.3318f,-17.8201f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [14.6522f,27.1247f,-17.9655f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [14.7514f,26.9112f,-18.1024f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [14.7508f,26.732f,-18.2435f]