#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^-0.125 ^-0.606 ^0 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^-0.125 ^-0.616 ^0 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^-0.125 ^-0.623 ^0 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^-0.125 ^-0.625 ^0 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^-0.125 ^-0.54 ^0 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^-0.125 ^-0.5 ^0 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^-0.125 ^-0.593 ^0 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^-0.125 ^-0.743 ^0 ~ ~