#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^-0.125 ^-0.503 ^0 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^-0.125 ^-0.51 ^0 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^-0.125 ^-0.52 ^0 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^-0.125 ^-0.533 ^0 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^-0.125 ^-0.548 ^0 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^-0.125 ^-0.563 ^0 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^-0.125 ^-0.578 ^0 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^-0.125 ^-0.593 ^0 ~ ~