#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [2.0962f,4.7597f,-0.8815f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [4.8061f,11.0186f,-2.8851f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [7.4205f,17.3396f,-6.1065f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [9.4859f,22.424f,-10.0511f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [11.0973f,25.6445f,-13.6895f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [12.5746f,27.2121f,-16.1095f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [13.859f,27.7356f,-17.1874f]