#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.357 ^-0.582 ^0.294 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.357 ^-0.604 ^0.294 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.357 ^-0.619 ^0.295 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.357 ^-0.624 ^0.295 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.356 ^-0.622 ^0.295 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^-0.356 ^-0.615 ^0.296 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^-0.354 ^-0.605 ^0.297 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.352 ^-0.593 ^0.298 ~ ~