#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-86.3205f,36.7478f,6.1777f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-87.051f,36.4008f,4.9513f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-87.7814f,36.0539f,3.725f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-88.4709f,35.7264f,2.5674f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-89.0784f,35.4378f,1.5473f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-89.5631f,35.2075f,0.7335f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-89.884f,35.0551f,0.1948f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-90f,35f,0f]