#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.emis.anim.thr2
execute if score .aj.anim_loop aj.emis.anim matches 0 run function emis:animation_loop
scoreboard players set #execute aj.i 1