#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.emis.walk.loo matches 0 run function emis:animations/walk/stop
execute if score @s aj.emis.walk.loo matches 1 run function emis:animations/walk/pause
execute if score @s aj.emis.walk.loo matches 2 run function emis:animations/walk/zzz/execute/108