#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-101.6787f,6.7825f,-4.294f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-90.498f,0.1186f,-0.0126f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-79.3203f,6.7881f,4.2683f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-68.1426f,13.4575f,8.5491f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-56.965f,20.1269f,12.83f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-56.965f,20.1269f,12.83f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-56.965f,20.1269f,12.83f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-56.965f,20.1269f,12.83f]