#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [55.4969f,-49.6447f,-30.7106f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [54.213f,-56.3882f,-33.8133f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [52.8279f,-63.1865f,-36.7475f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [51.2096f,-70.0236f,-39.4154f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [48.986f,-76.8824f,-41.4769f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [44.2244f,-83.736f,-41.0304f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-80.8903f,-88.9967f,79.7086f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-93.353f,-84.6894f,112.1386f]