#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [67.5f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [65.5237f,-5.5575f,-4.6076f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [63.7494f,-11.3605f,-8.9349f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [62.1424f,-17.374f,-13.0173f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [60.6695f,-23.5673f,-16.8866f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [59.2993f,-29.9135f,-20.5706f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [58.0016f,-36.389f,-24.0923f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [56.7454f,-42.9724f,-27.4692f]