#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.312 ^-0.324 ^0.373 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.376 ^-0.247 ^0.375 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.306 ^-0.17 ^0.371 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.232 ^-0.107 ^0.343 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.165 ^-0.059 ^0.294 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^-0.165 ^-0.059 ^0.294 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^-0.165 ^-0.059 ^0.294 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.165 ^-0.059 ^0.294 ~ ~