#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-40.1164f,-14.4177f,-12.1128f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-42.631f,-16.2199f,-13.627f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-45.1455f,-18.0221f,-15.1411f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-47.6601f,-19.8243f,-16.6552f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-50.1746f,-21.6266f,-18.1693f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-52.6892f,-23.4288f,-19.6834f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-55.2037f,-25.231f,-21.1975f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-66.9685f,-16.7811f,-14.1358f]