#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [0f,0f,11.3636f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [0f,0f,12.0455f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [0f,0f,12.7273f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [0f,0f,13.4091f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [0f,0f,14.0909f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [0f,0f,14.7727f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [0f,0f,15.4545f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [0f,0f,16.1364f]