#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [-90.3129f,-20.8149f,10.7635f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [-72.2503f,-16.6519f,8.6108f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [-54.1877f,-12.489f,6.4581f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [-36.1252f,-8.326f,4.3054f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [-18.0626f,-4.163f,2.1527f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [0f,0f,0f]