#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [2.1706f,-0.6785f,11.2927f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [3.2559f,-1.0177f,11.939f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [4.3413f,-1.357f,12.5853f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [5.4266f,-1.6962f,13.2317f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [6.5119f,-2.0355f,13.878f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [7.5972f,-2.3747f,14.5243f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [8.6825f,-2.714f,15.1707f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [9.7678f,-3.0532f,15.817f]