#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-78.7332f,-8.3313f,-7.0742f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-90.498f,0.1186f,-0.0126f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-102.478f,-9.6346f,5.0146f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-114.458f,-19.3877f,10.0417f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-126.438f,-29.1409f,15.0688f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-129.8881f,-37.1208f,17.0242f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-133.3392f,-45.0545f,19.331f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-136.9371f,-52.9174f,22.1228f]