#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.257 ^-0.565 ^0.206 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.24 ^-0.547 ^0.226 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.223 ^-0.526 ^0.246 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.207 ^-0.503 ^0.263 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.192 ^-0.478 ^0.279 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.178 ^-0.452 ^0.293 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^-0.165 ^-0.423 ^0.305 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^-0.238 ^-0.383 ^0.348 ~ ~