#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0 ^-0.25 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0 ^-0.294 ^0 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0 ^-0.338 ^0 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0 ^-0.382 ^0 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0 ^-0.425 ^0 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0 ^-0.469 ^0 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0 ^-0.425 ^0 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0 ^-0.382 ^0 ~ ~