#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0 ^-0.188 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0 ^-0.232 ^0 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0 ^-0.275 ^0 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0 ^-0.319 ^0 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0 ^-0.363 ^0 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0 ^-0.407 ^0 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0 ^-0.363 ^0 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0 ^-0.319 ^0 ~ ~