#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [8.1188f,-1.3094f,1.2605f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [20.3194f,-2.9449f,3.2705f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [33.3963f,-3.6978f,5.2499f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [44.2438f,-2.8459f,6.2451f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [49.7411f,-0.1621f,5.7386f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [48.1613f,5.3825f,3.9647f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [42.0339f,12.7274f,2.3f]