#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.241 ^-1.351 ^-0.063 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.237 ^-1.352 ^-0.07 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.232 ^-1.352 ^-0.076 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.228 ^-1.352 ^-0.082 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.224 ^-1.351 ^-0.088 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.221 ^-1.351 ^-0.093 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.219 ^-1.35 ^-0.097 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^0.215 ^-1.348 ^-0.108 ~ ~