#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run tp @s ^0.375 ^-0.625 ^0.026 ~ ~
execute if score .this aj.fram matches 49 run tp @s ^0.375 ^-0.625 ^0.011 ~ ~
execute if score .this aj.fram matches 50 run tp @s ^0.375 ^-0.625 ^0 ~ ~
execute if score .this aj.fram matches 51 run tp @s ^0.375 ^-0.625 ^0 ~ ~