#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-41.92f,0f,-11.66f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-40.64f,0f,-4.62f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-40f,0f,0f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-40f,0f,0.6205f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-40f,0f,1.1138f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-40f,0f,1.4902f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-40f,0f,1.76f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-40f,0f,1.9336f]