#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-40f,0f,2.0213f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-40f,0f,2.0333f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-40f,0f,1.98f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-40f,0f,1.8717f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-40f,0f,1.7187f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-40f,0f,1.5314f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-40f,0f,1.32f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-40f,0f,1.0948f]