#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.43 ^-0.599 ^0.251 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.398 ^-0.573 ^0.244 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.375 ^-0.538 ^0.241 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.372 ^-0.538 ^0.241 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.369 ^-0.539 ^0.241 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.368 ^-0.539 ^0.241 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.366 ^-0.54 ^0.241 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.365 ^-0.54 ^0.241 ~ ~