#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [11.3703f,0f,-11.3703f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [10.1348f,0f,-10.1348f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [8.8338f,0f,-8.8338f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [7.5f,0f,-7.5f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [6.1662f,0f,-6.1662f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [4.8652f,0f,-4.8652f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [3.6297f,0f,-3.6297f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [2.4927f,0f,-2.4927f]