#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [9.6792f,4.6148f,-17.5547f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [10.7509f,3.6054f,-16.9811f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [11.7527f,2.6666f,-16.4483f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [12.6815f,1.8174f,-15.9701f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [13.5343f,1.0772f,-15.5602f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [14.3081f,0.4649f,-15.2322f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [15f,0f,-15f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [16.678f,-0.891f,-14.7574f]