#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^0.375 ^-0.574 ^0.189 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^0.375 ^-0.585 ^0.17 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^0.375 ^-0.594 ^0.15 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^0.375 ^-0.603 ^0.128 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^0.375 ^-0.61 ^0.106 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^0.375 ^-0.616 ^0.084 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^0.375 ^-0.62 ^0.063 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^0.375 ^-0.623 ^0.043 ~ ~