#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.106 ^2.573 ^0.215 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.104 ^2.521 ^0.217 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.103 ^2.464 ^0.223 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.103 ^2.404 ^0.233 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.103 ^2.341 ^0.245 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^-0.104 ^2.276 ^0.258 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^-0.105 ^2.21 ^0.273 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.106 ^2.144 ^0.287 ~ ~