#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-12.8503f,-5.684f,0.3127f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-13.0548f,-9.5537f,0.5585f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [-13.1333f,-11.2943f,0.6732f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-13.0206f,-8.8539f,0.5128f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [-12.5f,0f,0f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [-12.0597f,6.5874f,-0.2489f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [-11.504f,14.9614f,-0.3202f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [-10.9524f,24.2573f,0.0398f]