#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^-0.108 ^2.078 ^0.301 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^-0.11 ^2.014 ^0.313 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^-0.112 ^1.952 ^0.324 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^-0.115 ^1.893 ^0.332 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^-0.119 ^1.839 ^0.337 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^-0.123 ^1.789 ^0.339 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^-0.129 ^1.746 ^0.337 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^-0.163 ^1.631 ^0.278 ~ ~