#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.375 ^-0.968 ^0.025 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.34 ^-1.039 ^0.098 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.315 ^-1.091 ^0.205 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.262 ^-1.112 ^0.324 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.157 ^-1.087 ^0.434 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0.007 ^-0.992 ^0.517 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.039 ^-0.32 ^0.811 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.004 ^0.569 ^0.815 ~ ~