#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-9.3762f,15.5513f,0f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-9.3577f,15.5545f,0f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-9.44f,15.54f,0f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-9.6073f,15.5105f,0f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-9.8438f,15.4687f,0f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-10.1333f,15.4177f,0f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-10.46f,15.36f,0f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-10.808f,15.2986f,0f]