#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^-0.144 ^-1.368 ^0.07 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^-0.145 ^-1.368 ^0.072 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^-0.145 ^-1.368 ^0.074 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^-0.145 ^-1.367 ^0.076 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^-0.146 ^-1.367 ^0.077 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^-0.146 ^-1.367 ^0.078 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^-0.146 ^-1.367 ^0.078 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^-0.146 ^-1.366 ^0.079 ~ ~