#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [-9.4752f,11.3703f,0f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [-8.4457f,10.1348f,0f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [-7.3615f,8.8338f,0f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [-6.25f,7.5f,0f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [-5.1385f,6.1662f,0f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [-4.0543f,4.8652f,0f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [-3.0248f,3.6297f,0f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [-2.0773f,2.4927f,0f]