execute positioned ~ ~ ~ as @p[tag=qst14] at @s run tellraw @s ["",{"text":"Quest Completed:","color":"yellow"},{"text":" "},{"text":"An Artist's Anguish","underlined":true},{"text":"\n"},{"text":"Retrieve Corv Ihd's Painting","italic":true,"color":"gray"}]
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run playsound minecraft:dcustom.entity.player.levelup player @a ~ ~ ~ 1 2
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run particle minecraft:happy_villager ~ ~1 ~ 0.5 0.5 0.5 0 40
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run playsound minecraft:dcustom.ui.toast.challenge_complete player @a ~ ~ ~ 1 1
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~1 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~1 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~1 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~1 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~1 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~1 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~1 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~1 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon experience_orb ~ ~ ~2 {Value:6}
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run summon firework_rocket ~ ~2 ~ {LifeTime:30,FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Flight:2,Explosions:[{Type:1,Flicker:0b,Trail:0b,Colors:[I;15790320],FadeColors:[I;15790320]}]}}}}
execute positioned ~ ~ ~ as @p[tag=qst14] run advancement grant @s only dlc:corvid
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run give @s dlc:silver_ingot{display:{Lore:['{"extra":[{"italic":true,"color":"dark_purple","text":"The merchants of Drehmal like a"}],"text":""}','{"extra":[{"italic":true,"color":"dark_purple","text":"sack of scales as much as any"}],"text":""}','{"extra":[{"italic":true,"color":"dark_purple","text":"other, but for special equipment,"}],"text":""}','{"extra":[{"italic":true,"color":"dark_purple","text":"silver is the currency of choice."}],"text":""}','{"text":""}'],Name:'{"extra":[{"italic":false,"underlined":true,"color":"aqua","text":"Silver Ingot"}],"text":""}'}} 2
execute as @p[tag=qst14] run tag @s add qst14_e
execute positioned ~ ~ ~ as @p[tag=qst14] at @s run tag @s remove qst14

execute unless score #quest14 bool matches 1 run scoreboard players add #quest num 1
execute if score #quest num matches 17 run advancement grant @a only dlc:questmaster
scoreboard players set #quest14 bool 1