#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.emis.spin.loop matches 0 run function emis:animations/spin/stop
execute if score @s aj.emis.spin.loop matches 1 run function emis:animations/spin/pause
execute if score @s aj.emis.spin.loop matches 2 run function emis:animations/spin/zzz/execute/105