#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [0.6283f,-0.2628f,-0.047f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [1.4237f,-0.93f,-0.1735f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [2.3598f,-1.9085f,-0.3576f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [3.4107f,-3.1056f,-0.5773f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [4.5511f,-4.4285f,-0.8106f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [5.7565f,-5.7843f,-1.0356f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [7.0029f,-7.0801f,-1.2306f]