#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [28.0991f,56.7024f,24.7197f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [27.575f,58.9467f,26.1543f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [26.31f,60.4878f,27.2324f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [24.4056f,61.3799f,27.9165f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [21.9855f,61.6758f,28.1928f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [19.1984f,61.427f,28.0729f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [16.2123f,60.6834f,27.589f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [13.2057f,59.4946f,26.7841f]