#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [0f,7.4194f,0f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [0f,7.0968f,0f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [0f,6.7742f,0f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [0f,6.4516f,0f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [0f,6.129f,0f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [0f,5.8065f,0f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [0f,5.4839f,0f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [0f,5.1613f,0f]