#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [0f,4.8387f,0f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [0f,4.5161f,0f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [0f,4.1935f,0f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [0f,3.871f,0f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [0f,3.5484f,0f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [0f,3.2258f,0f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [0f,2.9032f,0f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [0f,2.5806f,0f]