#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [17.6846f,2.4679f,3.0105f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [19.1605f,9.0999f,5.1811f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [20.6611f,16.5712f,7.686f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [22.1496f,24.4798f,10.4469f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [23.5979f,32.4254f,13.3856f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [24.9823f,40.0107f,16.4189f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [26.2673f,46.8422f,19.4438f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [27.3701f,52.5324f,22.3018f]