#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-20.8882f,30.6712f,-5.2641f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-20.1165f,30.4443f,-5.6052f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [-19.3166f,30.2034f,-5.9417f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-18.5054f,29.9419f,-6.2685f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [-17.6994f,29.6532f,-6.5806f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [-16.9153f,29.33f,-6.8729f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [-16.1696f,28.9646f,-7.1402f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [-15.4788f,28.5491f,-7.3773f]