#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [-1.2834f,1.5953f,-0.3213f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [-1.0502f,1.3794f,-0.2614f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [-0.8313f,1.1591f,-0.2054f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [-0.6282f,0.9346f,-0.1538f]
execute if score .this aj.fram matches 52 run data modify entity @s Pose.Head set value [-0.4422f,0.7063f,-0.1069f]
execute if score .this aj.fram matches 53 run data modify entity @s Pose.Head set value [-0.2746f,0.4743f,-0.0653f]
execute if score .this aj.fram matches 54 run data modify entity @s Pose.Head set value [-0.1268f,0.2387f,-0.0295f]
execute if score .this aj.fram matches 55 run data modify entity @s Pose.Head set value [0f,0f,0f]