#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [-14.8595f,28.0751f,-7.5792f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [-14.3281f,27.534f,-7.7407f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [-13.9015f,26.9166f,-7.8571f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [-13.5961f,26.2136f,-7.9236f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [-13.429f,25.4155f,-7.9357f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [-13.3812f,23.8605f,-7.5972f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [-13.6312f,21.8645f,-7.0489f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [-14.1216f,19.5215f,-6.3366f]