#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^0.446 ^-0.606 ^0.035 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^0.448 ^-0.605 ^0.029 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^0.449 ^-0.605 ^0.023 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^0.449 ^-0.605 ^0.017 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^0.448 ^-0.605 ^0.013 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^0.445 ^-0.607 ^0.008 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^0.439 ^-0.609 ^0.004 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^0.432 ^-0.611 ^0.002 ~ ~