#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-3.746f,30.4755f,-10.8794f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-2.8104f,30.3269f,-10.9283f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [-1.8444f,30.1593f,-10.9673f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-0.865f,29.9644f,-10.9924f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [0.1107f,29.7341f,-10.9998f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [1.0654f,29.4599f,-10.9858f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [1.9816f,29.1336f,-10.9467f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [2.842f,28.7469f,-10.8789f]