#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^0.31 ^-0.25 ^0.04 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^0.31 ^-0.25 ^0.039 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^0.31 ^-0.25 ^0.037 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^0.311 ^-0.25 ^0.035 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^0.311 ^-0.25 ^0.033 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^0.311 ^-0.25 ^0.032 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^0.311 ^-0.25 ^0.03 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^0.311 ^-0.25 ^0.028 ~ ~