#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.129 ^-1.372 ^0.07 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.13 ^-1.372 ^0.069 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.13 ^-1.373 ^0.067 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.13 ^-1.373 ^0.065 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.13 ^-1.373 ^0.063 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.13 ^-1.373 ^0.061 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.13 ^-1.373 ^0.059 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^0.13 ^-1.373 ^0.056 ~ ~