#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-7.4628f,4.8944f,-1.6248f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-7.3215f,4.8493f,-1.6212f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-7.1585f,4.7946f,-1.6096f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-6.9756f,4.7305f,-1.5904f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-6.7743f,4.6572f,-1.5642f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-6.5562f,4.575f,-1.5313f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-6.323f,4.4839f,-1.4924f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-6.0762f,4.3843f,-1.448f]