#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-12.672f,15.7726f,-0.7073f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-11.5228f,17.93f,-0.8329f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-10.4706f,19.9888f,-0.9767f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-9.5739f,21.9165f,-1.1447f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-8.895f,23.6824f,-1.3445f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-8.4991f,25.2563f,-1.5855f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-8.4523f,26.606f,-1.8788f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-9.0281f,27.9946f,-2.2464f]