#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [-49.8563f,17.463f,11.3025f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [-60.799f,13.9152f,2.2222f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [-69.7428f,10.379f,-5.5357f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [-76.5321f,7.0926f,-11.8318f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [-81.0234f,4.2611f,-16.5582f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [-77.3375f,-1.4006f,-25.5123f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [-54.7505f,-4.3147f,-25.6873f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [-22.5943f,-5.9413f,-22.1082f]