#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [70.2268f,33.1089f,93.5513f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [55.9651f,31.1927f,85.6863f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [40.9535f,29.6471f,77.0804f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [24.9296f,28.7682f,66.7306f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [8.6449f,27.5919f,55.6059f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [-7.4454f,25.9181f,44.0679f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [-22.8517f,23.6401f,32.555f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [-37.1143f,20.7763f,21.5077f]