#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [-0.716f,0.9723f,0.3202f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [-1.6807f,2.0716f,0.7252f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [-2.8456f,3.282f,1.2032f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [-4.1623f,4.5879f,1.7422f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [-5.5829f,5.9733f,2.3305f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [-7.0596f,7.4224f,2.9563f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [-8.5452f,8.9194f,3.6081f]