#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^-0.308 ^-0.25 ^-0.054 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^-0.308 ^-0.25 ^-0.053 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^-0.308 ^-0.25 ^-0.051 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^-0.309 ^-0.25 ^-0.049 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^-0.309 ^-0.25 ^-0.047 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^-0.309 ^-0.25 ^-0.046 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^-0.309 ^-0.25 ^-0.044 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^-0.31 ^-0.25 ^-0.042 ~ ~