#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [3.1853f,10.4483f,4.2741f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [3.6341f,11.9933f,4.9427f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [4.032f,13.5388f,5.6018f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [4.3594f,15.069f,6.2394f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [4.5962f,16.5684f,6.843f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [4.7221f,18.0215f,7.3996f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [4.7161f,19.4129f,7.8961f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [4.8437f,21.315f,8.5787f]