#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if score @s aj.fram matches ..1 run function emis:animations/hood/zzz/conditional/184
execute if score #execute aj.i matches 0 run function emis:animations/hood/zzz/conditional/185