#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run tp @s ^0.465 ^2.391 ^0.299 ~ ~
execute if score .this aj.fram matches 65 run tp @s ^0.412 ^2.373 ^0.368 ~ ~
execute if score .this aj.fram matches 66 run tp @s ^0.35 ^2.354 ^0.428 ~ ~
execute if score .this aj.fram matches 67 run tp @s ^0.278 ^2.335 ^0.477 ~ ~
execute if score .this aj.fram matches 68 run tp @s ^0.2 ^2.315 ^0.515 ~ ~
execute if score .this aj.fram matches 69 run tp @s ^0.117 ^2.295 ^0.54 ~ ~
execute if score .this aj.fram matches 70 run tp @s ^0.031 ^2.275 ^0.552 ~ ~
execute if score .this aj.fram matches 71 run tp @s ^-0.055 ^2.254 ^0.55 ~ ~