#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [-180f,0f,180f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [-180f,-9f,180f]
execute if score .this aj.fram matches 82 run data modify entity @s Pose.Head set value [-180f,-18f,180f]
execute if score .this aj.fram matches 83 run data modify entity @s Pose.Head set value [-180f,-27f,180f]
execute if score .this aj.fram matches 84 run data modify entity @s Pose.Head set value [-180f,-36f,180f]
execute if score .this aj.fram matches 85 run data modify entity @s Pose.Head set value [-180f,-45f,180f]
execute if score .this aj.fram matches 86 run data modify entity @s Pose.Head set value [-180f,-54f,180f]
execute if score .this aj.fram matches 87 run data modify entity @s Pose.Head set value [-180f,-63f,180f]