#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 104 run tp @s ^0.507 ^1.646 ^0.217 ~ ~
execute if score .this aj.fram matches 105 run tp @s ^0.519 ^1.65 ^0.188 ~ ~
execute if score .this aj.fram matches 106 run tp @s ^0.533 ^1.658 ^0.141 ~ ~
execute if score .this aj.fram matches 107 run tp @s ^0.545 ^1.668 ^0.086 ~ ~
execute if score .this aj.fram matches 108 run tp @s ^0.551 ^1.677 ^0.033 ~ ~
execute if score .this aj.fram matches 109 run tp @s ^0.552 ^1.684 ^-0.007 ~ ~
execute if score .this aj.fram matches 110 run tp @s ^0.552 ^1.685 ^-0.024 ~ ~
execute if score .this aj.fram matches 111 run tp @s ^0.553 ^1.684 ^-0.025 ~ ~