#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run tp @s ^0.58 ^1.465 ^-0.039 ~ ~
execute if score .this aj.fram matches 153 run tp @s ^0.577 ^1.504 ^-0.039 ~ ~
execute if score .this aj.fram matches 154 run tp @s ^0.574 ^1.541 ^-0.039 ~ ~
execute if score .this aj.fram matches 155 run tp @s ^0.571 ^1.575 ^-0.038 ~ ~
execute if score .this aj.fram matches 156 run tp @s ^0.569 ^1.606 ^-0.037 ~ ~
execute if score .this aj.fram matches 157 run tp @s ^0.566 ^1.633 ^-0.037 ~ ~
execute if score .this aj.fram matches 158 run tp @s ^0.564 ^1.656 ^-0.036 ~ ~
execute if score .this aj.fram matches 159 run tp @s ^0.562 ^1.675 ^-0.035 ~ ~