#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 120 run data modify entity @s Pose.Head set value [-15.1062f,14.6319f,0f]
execute if score .this aj.fram matches 121 run data modify entity @s Pose.Head set value [-16.9768f,16.3415f,0f]
execute if score .this aj.fram matches 122 run data modify entity @s Pose.Head set value [-18.8248f,18.0298f,0f]
execute if score .this aj.fram matches 123 run data modify entity @s Pose.Head set value [-20.6277f,19.6765f,0f]
execute if score .this aj.fram matches 124 run data modify entity @s Pose.Head set value [-22.3631f,21.2611f,0f]
execute if score .this aj.fram matches 125 run data modify entity @s Pose.Head set value [-24.0086f,22.7635f,0f]
execute if score .this aj.fram matches 126 run data modify entity @s Pose.Head set value [-25.5416f,24.1633f,0f]
execute if score .this aj.fram matches 127 run data modify entity @s Pose.Head set value [-26.9397f,25.4401f,0f]