#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 200 run tp @s ^0 ^1.021 ^0 ~ ~
execute if score .this aj.fram matches 201 run tp @s ^0 ^1.022 ^0 ~ ~
execute if score .this aj.fram matches 202 run tp @s ^0 ^1.023 ^0 ~ ~
execute if score .this aj.fram matches 203 run tp @s ^0 ^1.025 ^0 ~ ~
execute if score .this aj.fram matches 204 run tp @s ^0 ^1.026 ^0 ~ ~
execute if score .this aj.fram matches 205 run tp @s ^0 ^1.027 ^0 ~ ~
execute if score .this aj.fram matches 206 run tp @s ^0 ^1.028 ^0 ~ ~
execute if score .this aj.fram matches 207 run tp @s ^0 ^1.029 ^0 ~ ~