#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 208 run data modify entity @s Pose.Head set value [0f,-26.8471f,0f]
execute if score .this aj.fram matches 209 run data modify entity @s Pose.Head set value [0f,-26.8319f,0f]
execute if score .this aj.fram matches 210 run data modify entity @s Pose.Head set value [0f,-26.7199f,0f]
execute if score .this aj.fram matches 211 run data modify entity @s Pose.Head set value [0f,-26.496f,0f]
execute if score .this aj.fram matches 212 run data modify entity @s Pose.Head set value [0f,-26.1449f,0f]
execute if score .this aj.fram matches 213 run data modify entity @s Pose.Head set value [0f,-25.6513f,0f]
execute if score .this aj.fram matches 214 run data modify entity @s Pose.Head set value [0f,-25f,0f]
execute if score .this aj.fram matches 215 run data modify entity @s Pose.Head set value [0f,-21.9907f,0f]