#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run tp @s ^0 ^1.062 ^0 ~ ~
execute if score .this aj.fram matches 65 run tp @s ^0 ^1.062 ^0 ~ ~
execute if score .this aj.fram matches 66 run tp @s ^0 ^1.062 ^0 ~ ~
execute if score .this aj.fram matches 67 run tp @s ^0 ^1.062 ^0 ~ ~
execute if score .this aj.fram matches 68 run tp @s ^0 ^1.062 ^0 ~ ~
execute if score .this aj.fram matches 69 run tp @s ^0 ^1.062 ^0 ~ ~
execute if score .this aj.fram matches 70 run tp @s ^0 ^1.062 ^0 ~ ~
execute if score .this aj.fram matches 71 run tp @s ^0 ^1.062 ^0 ~ ~