#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 216 run data modify entity @s Pose.Head set value [0f,-17.5926f,0f]
execute if score .this aj.fram matches 217 run data modify entity @s Pose.Head set value [0f,-12.5f,0f]
execute if score .this aj.fram matches 218 run data modify entity @s Pose.Head set value [0f,-7.4074f,0f]
execute if score .this aj.fram matches 219 run data modify entity @s Pose.Head set value [0f,-3.0093f,0f]
execute if score .this aj.fram matches 220 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 221 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 222 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 223 run data modify entity @s Pose.Head set value [0f,0f,0f]