#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 216 run data modify entity @s Pose.Head set value [0.9663f,-0.7459f,0f]
execute if score .this aj.fram matches 217 run data modify entity @s Pose.Head set value [0.455f,-0.53f,0f]
execute if score .this aj.fram matches 218 run data modify entity @s Pose.Head set value [-0.0563f,-0.3141f,0f]
execute if score .this aj.fram matches 219 run data modify entity @s Pose.Head set value [-0.4979f,-0.1276f,0f]
execute if score .this aj.fram matches 220 run data modify entity @s Pose.Head set value [-0.8f,0f,0f]
execute if score .this aj.fram matches 221 run data modify entity @s Pose.Head set value [-0.9805f,-1.6833f,0f]
execute if score .this aj.fram matches 222 run data modify entity @s Pose.Head set value [-0.9675f,-1.4962f,0f]
execute if score .this aj.fram matches 223 run data modify entity @s Pose.Head set value [-0.8708f,-0.5611f,0f]