#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run tp @s ^0 ^0.594 ^0 ~ ~
execute if score .this aj.fram matches 145 run tp @s ^0 ^0.63 ^0 ~ ~
execute if score .this aj.fram matches 146 run tp @s ^0 ^0.668 ^0 ~ ~
execute if score .this aj.fram matches 147 run tp @s ^0 ^0.707 ^0 ~ ~
execute if score .this aj.fram matches 148 run tp @s ^0 ^0.747 ^0 ~ ~
execute if score .this aj.fram matches 149 run tp @s ^0 ^0.787 ^0 ~ ~
execute if score .this aj.fram matches 150 run tp @s ^0 ^0.826 ^0 ~ ~
execute if score .this aj.fram matches 151 run tp @s ^0 ^0.865 ^0 ~ ~