#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run tp @s ^0 ^1.937 ^0 ~ ~
execute if score .this aj.fram matches 49 run tp @s ^0 ^1.946 ^0 ~ ~
execute if score .this aj.fram matches 50 run tp @s ^0 ^1.967 ^0 ~ ~
execute if score .this aj.fram matches 51 run tp @s ^0 ^1.988 ^0 ~ ~
execute if score .this aj.fram matches 52 run tp @s ^0 ^1.997 ^0 ~ ~
execute if score .this aj.fram matches 53 run tp @s ^0 ^1.984 ^0 ~ ~
execute if score .this aj.fram matches 54 run tp @s ^0 ^1.937 ^0 ~ ~
execute if score .this aj.fram matches 55 run tp @s ^0 ^1.928 ^0 ~ ~