#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 176 run data modify entity @s Pose.Head set value [0.4759f,-1.4395f,0f]
execute if score .this aj.fram matches 177 run data modify entity @s Pose.Head set value [0.0185f,-0.4638f,0f]
execute if score .this aj.fram matches 178 run data modify entity @s Pose.Head set value [-0.1f,0.83f,0f]
execute if score .this aj.fram matches 179 run data modify entity @s Pose.Head set value [0.805f,-0.115f,0f]
execute if score .this aj.fram matches 180 run data modify entity @s Pose.Head set value [1.71f,-1.06f,0f]
execute if score .this aj.fram matches 181 run data modify entity @s Pose.Head set value [1.7572f,-1.1092f,0f]
execute if score .this aj.fram matches 182 run data modify entity @s Pose.Head set value [1.7929f,-1.1466f,0f]
execute if score .this aj.fram matches 183 run data modify entity @s Pose.Head set value [1.8183f,-1.1731f,0f]