#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 96 run tp @s ^0 ^1.169 ^0 ~ ~
execute if score .this aj.fram matches 97 run tp @s ^0 ^1.157 ^0 ~ ~
execute if score .this aj.fram matches 98 run tp @s ^0 ^1.145 ^0 ~ ~
execute if score .this aj.fram matches 99 run tp @s ^0 ^1.134 ^0 ~ ~
execute if score .this aj.fram matches 100 run tp @s ^0 ^1.125 ^0 ~ ~
execute if score .this aj.fram matches 101 run tp @s ^0 ^1.09 ^0 ~ ~
execute if score .this aj.fram matches 102 run tp @s ^0 ^1.068 ^0 ~ ~
execute if score .this aj.fram matches 103 run tp @s ^0 ^1.057 ^0 ~ ~