#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 168 run tp @s ^0 ^1.103 ^0 ~ ~
execute if score .this aj.fram matches 169 run tp @s ^0 ^1.096 ^0 ~ ~
execute if score .this aj.fram matches 170 run tp @s ^0 ^1.094 ^0 ~ ~
execute if score .this aj.fram matches 171 run tp @s ^0 ^1.094 ^0 ~ ~
execute if score .this aj.fram matches 172 run tp @s ^0 ^1.095 ^0 ~ ~
execute if score .this aj.fram matches 173 run tp @s ^0 ^1.095 ^0 ~ ~
execute if score .this aj.fram matches 174 run tp @s ^0 ^1.096 ^0 ~ ~
execute if score .this aj.fram matches 175 run tp @s ^0 ^1.096 ^0 ~ ~