#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 192 run data modify entity @s Pose.Head set value [1.7653f,-1.1177f,0f]
execute if score .this aj.fram matches 193 run data modify entity @s Pose.Head set value [1.7483f,-1.1f,0f]
execute if score .this aj.fram matches 194 run data modify entity @s Pose.Head set value [1.7332f,-1.0842f,0f]
execute if score .this aj.fram matches 195 run data modify entity @s Pose.Head set value [1.7211f,-1.0715f,0f]
execute if score .this aj.fram matches 196 run data modify entity @s Pose.Head set value [1.7129f,-1.0631f,0f]
execute if score .this aj.fram matches 197 run data modify entity @s Pose.Head set value [1.71f,-1.06f,0f]
execute if score .this aj.fram matches 198 run data modify entity @s Pose.Head set value [1.7141f,-1.0617f,0f]
execute if score .this aj.fram matches 199 run data modify entity @s Pose.Head set value [1.7253f,-1.0665f,0f]