#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 112 run tp @s ^0 ^1.093 ^0 ~ ~
execute if score .this aj.fram matches 113 run tp @s ^0 ^1.092 ^0 ~ ~
execute if score .this aj.fram matches 114 run tp @s ^0 ^1.092 ^0 ~ ~
execute if score .this aj.fram matches 115 run tp @s ^0 ^1.092 ^0 ~ ~
execute if score .this aj.fram matches 116 run tp @s ^0 ^1.092 ^0 ~ ~
execute if score .this aj.fram matches 117 run tp @s ^0 ^1.092 ^0 ~ ~
execute if score .this aj.fram matches 118 run tp @s ^0 ^1.092 ^0 ~ ~
execute if score .this aj.fram matches 119 run tp @s ^0 ^1.092 ^0 ~ ~