#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 96 run tp @s ^0.171 ^-0.051 ^0.082 ~ ~
execute if score .this aj.fram matches 97 run tp @s ^0.171 ^-0.051 ^0.083 ~ ~
execute if score .this aj.fram matches 98 run tp @s ^0.171 ^-0.05 ^0.085 ~ ~
execute if score .this aj.fram matches 99 run tp @s ^0.17 ^-0.05 ^0.086 ~ ~
execute if score .this aj.fram matches 100 run tp @s ^0.17 ^-0.05 ^0.086 ~ ~
execute if score .this aj.fram matches 101 run tp @s ^0.167 ^-0.051 ^0.086 ~ ~
execute if score .this aj.fram matches 102 run tp @s ^0.163 ^-0.053 ^0.082 ~ ~
execute if score .this aj.fram matches 103 run tp @s ^0.159 ^-0.056 ^0.075 ~ ~