#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 104 run tp @s ^0.153 ^-0.059 ^0.066 ~ ~
execute if score .this aj.fram matches 105 run tp @s ^0.148 ^-0.062 ^0.056 ~ ~
execute if score .this aj.fram matches 106 run tp @s ^0.142 ^-0.065 ^0.045 ~ ~
execute if score .this aj.fram matches 107 run tp @s ^0.137 ^-0.067 ^0.034 ~ ~
execute if score .this aj.fram matches 108 run tp @s ^0.133 ^-0.069 ^0.024 ~ ~
execute if score .this aj.fram matches 109 run tp @s ^0.129 ^-0.07 ^0.016 ~ ~
execute if score .this aj.fram matches 110 run tp @s ^0.127 ^-0.071 ^0.011 ~ ~
execute if score .this aj.fram matches 111 run tp @s ^0.126 ^-0.071 ^0.009 ~ ~