#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 208 run tp @s ^0.306 ^0.012 ^0.121 ~ ~
execute if score .this aj.fram matches 209 run tp @s ^0.302 ^0.007 ^0.117 ~ ~
execute if score .this aj.fram matches 210 run tp @s ^0.297 ^0.001 ^0.113 ~ ~
execute if score .this aj.fram matches 211 run tp @s ^0.292 ^-0.007 ^0.11 ~ ~
execute if score .this aj.fram matches 212 run tp @s ^0.286 ^-0.014 ^0.107 ~ ~
execute if score .this aj.fram matches 213 run tp @s ^0.279 ^-0.023 ^0.105 ~ ~
execute if score .this aj.fram matches 214 run tp @s ^0.271 ^-0.033 ^0.104 ~ ~
execute if score .this aj.fram matches 215 run tp @s ^0.241 ^-0.075 ^0.101 ~ ~