#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 56 run tp @s ^1.773 ^1.05 ^0.115 ~ ~
execute if score .this aj.fram matches 57 run tp @s ^1.801 ^0.883 ^0.077 ~ ~
execute if score .this aj.fram matches 58 run tp @s ^1.871 ^0.719 ^0.038 ~ ~
execute if score .this aj.fram matches 59 run tp @s ^1.96 ^0.578 ^0.004 ~ ~
execute if score .this aj.fram matches 60 run tp @s ^2.028 ^0.468 ^-0.019 ~ ~
execute if score .this aj.fram matches 61 run tp @s ^2.028 ^0.467 ^-0.019 ~ ~
execute if score .this aj.fram matches 62 run tp @s ^2.028 ^0.466 ^-0.019 ~ ~
execute if score .this aj.fram matches 63 run tp @s ^2.027 ^0.463 ^-0.019 ~ ~