#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 56 run tp @s ^0.938 ^0.75 ^-0.937 ~ ~
execute if score .this aj.fram matches 57 run tp @s ^0.938 ^0.75 ^-0.667 ~ ~
execute if score .this aj.fram matches 58 run tp @s ^0.938 ^0.75 ^-0.395 ~ ~
execute if score .this aj.fram matches 59 run tp @s ^0.938 ^0.75 ^-0.16 ~ ~
execute if score .this aj.fram matches 60 run tp @s ^0.938 ^0.75 ^0 ~ ~
execute if score .this aj.fram matches 61 run tp @s ^0.938 ^0.75 ^0 ~ ~
execute if score .this aj.fram matches 62 run tp @s ^0.938 ^0.75 ^0 ~ ~
execute if score .this aj.fram matches 63 run tp @s ^0.938 ^0.75 ^0 ~ ~