#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^1.606 ^1.053 ^0.446 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^1.611 ^1.055 ^0.439 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^1.616 ^1.056 ^0.431 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^1.621 ^1.058 ^0.423 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^1.626 ^1.059 ^0.416 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^1.631 ^1.061 ^0.408 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^1.636 ^1.063 ^0.401 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^1.641 ^1.064 ^0.393 ~ ~