#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 176 run data modify entity @s Pose.Head set value [-59.501f,6.9977f,4.3702f]
execute if score .this aj.fram matches 177 run data modify entity @s Pose.Head set value [-59.1503f,8.356f,4.9331f]
execute if score .this aj.fram matches 178 run data modify entity @s Pose.Head set value [-58.8276f,10.6412f,6.063f]
execute if score .this aj.fram matches 179 run data modify entity @s Pose.Head set value [-62.0209f,21.6731f,15.6346f]
execute if score .this aj.fram matches 180 run data modify entity @s Pose.Head set value [-75.3351f,33.7683f,16.1442f]
execute if score .this aj.fram matches 181 run data modify entity @s Pose.Head set value [-76.3103f,34.4157f,15.7432f]
execute if score .this aj.fram matches 182 run data modify entity @s Pose.Head set value [-77.0226f,34.9556f,15.4073f]
execute if score .this aj.fram matches 183 run data modify entity @s Pose.Head set value [-77.4818f,35.4043f,15.1519f]