#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]