#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0.75 ^-0.375 ^0.313 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0.75 ^-0.37 ^0.306 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0.75 ^-0.365 ^0.299 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0.75 ^-0.36 ^0.293 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0.75 ^-0.355 ^0.286 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0.75 ^-0.349 ^0.28 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.75 ^-0.344 ^0.273 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0.75 ^-0.339 ^0.267 ~ ~