#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run data modify entity @s Pose.Head set value [-47.689f,30.1557f,4.8555f]
execute if score .this aj.fram matches 145 run data modify entity @s Pose.Head set value [-47.9537f,29.4514f,5.0241f]
execute if score .this aj.fram matches 146 run data modify entity @s Pose.Head set value [-48.2471f,28.7074f,5.189f]
execute if score .this aj.fram matches 147 run data modify entity @s Pose.Head set value [-48.5689f,27.9283f,5.3476f]
execute if score .this aj.fram matches 148 run data modify entity @s Pose.Head set value [-48.9188f,27.1188f,5.4977f]
execute if score .this aj.fram matches 149 run data modify entity @s Pose.Head set value [-49.2958f,26.2836f,5.6372f]
execute if score .this aj.fram matches 150 run data modify entity @s Pose.Head set value [-49.6988f,25.4273f,5.7649f]
execute if score .this aj.fram matches 151 run data modify entity @s Pose.Head set value [-50.1263f,24.5545f,5.8796f]