#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run tp @s ^2.026 ^0.459 ^-0.02 ~ ~
execute if score .this aj.fram matches 65 run tp @s ^2.025 ^0.454 ^-0.02 ~ ~
execute if score .this aj.fram matches 66 run tp @s ^2.023 ^0.448 ^-0.021 ~ ~
execute if score .this aj.fram matches 67 run tp @s ^2.021 ^0.442 ^-0.022 ~ ~
execute if score .this aj.fram matches 68 run tp @s ^2.019 ^0.434 ^-0.022 ~ ~
execute if score .this aj.fram matches 69 run tp @s ^2.016 ^0.425 ^-0.023 ~ ~
execute if score .this aj.fram matches 70 run tp @s ^2.014 ^0.416 ^-0.024 ~ ~
execute if score .this aj.fram matches 71 run tp @s ^2.01 ^0.406 ^-0.025 ~ ~