#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [-48.8825f,-35.5415f,-27.9919f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [-49.1049f,-35.4332f,-27.5644f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [-49.5934f,-35.1946f,-26.624f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [-50.0815f,-34.9557f,-25.6848f]
execute if score .this aj.fram matches 52 run data modify entity @s Pose.Head set value [-50.3035f,-34.8469f,-25.2587f]
execute if score .this aj.fram matches 53 run data modify entity @s Pose.Head set value [-49.9941f,-34.9992f,-25.8577f]
execute if score .this aj.fram matches 54 run data modify entity @s Pose.Head set value [-48.8857f,-35.5415f,-27.9972f]
execute if score .this aj.fram matches 55 run data modify entity @s Pose.Head set value [-46.3468f,-36.7702f,-32.8921f]