#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 104 run tp @s ^0.583 ^0.792 ^0.008 ~ ~
execute if score .this aj.fram matches 105 run tp @s ^0.57 ^0.779 ^0.017 ~ ~
execute if score .this aj.fram matches 106 run tp @s ^0.556 ^0.766 ^0.026 ~ ~
execute if score .this aj.fram matches 107 run tp @s ^0.543 ^0.756 ^0.034 ~ ~
execute if score .this aj.fram matches 108 run tp @s ^0.531 ^0.747 ^0.042 ~ ~
execute if score .this aj.fram matches 109 run tp @s ^0.521 ^0.74 ^0.048 ~ ~
execute if score .this aj.fram matches 110 run tp @s ^0.513 ^0.735 ^0.052 ~ ~
execute if score .this aj.fram matches 111 run tp @s ^0.51 ^0.733 ^0.054 ~ ~