#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 240 run tp @s ^0.125 ^-1.375 ^0 ~ ~
execute if score .this aj.fram matches 241 run tp @s ^0.125 ^-1.375 ^0 ~ ~
execute if score .this aj.fram matches 242 run tp @s ^0.125 ^-1.375 ^0 ~ ~