#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 160 run data modify entity @s Pose.Head set value [-10.0206f,-21.2272f,-27.4484f]
execute if score .this aj.fram matches 161 run data modify entity @s Pose.Head set value [-10.2821f,-21.0294f,-26.3452f]
execute if score .this aj.fram matches 162 run data modify entity @s Pose.Head set value [-10.5335f,-20.8393f,-25.2852f]
execute if score .this aj.fram matches 163 run data modify entity @s Pose.Head set value [-10.7731f,-20.658f,-24.2746f]
execute if score .this aj.fram matches 164 run data modify entity @s Pose.Head set value [-10.9996f,-20.4867f,-23.3194f]
execute if score .this aj.fram matches 165 run data modify entity @s Pose.Head set value [-11.2114f,-20.3265f,-22.426f]
execute if score .this aj.fram matches 166 run data modify entity @s Pose.Head set value [-11.4071f,-20.1784f,-21.6004f]
execute if score .this aj.fram matches 167 run data modify entity @s Pose.Head set value [-11.5853f,-20.0436f,-20.8488f]