#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 240 run data modify entity @s Pose.Head set value [-94.8326f,6.444f,-6.9805f]
execute if score .this aj.fram matches 241 run data modify entity @s Pose.Head set value [-50.5279f,0.4387f,-1.712f]
execute if score .this aj.fram matches 242 run data modify entity @s Pose.Head set value [-20f,0f,0f]