#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 96 run data modify entity @s Pose.Head set value [9.0315f,-27.4217f,-0.7953f]
execute if score .this aj.fram matches 97 run data modify entity @s Pose.Head set value [9.2725f,-27.457f,-0.5606f]
execute if score .this aj.fram matches 98 run data modify entity @s Pose.Head set value [9.5144f,-27.482f,-0.3488f]
execute if score .this aj.fram matches 99 run data modify entity @s Pose.Head set value [9.757f,-27.4965f,-0.1614f]
execute if score .this aj.fram matches 100 run data modify entity @s Pose.Head set value [10f,-27.5f,0f]
execute if score .this aj.fram matches 101 run data modify entity @s Pose.Head set value [11.0928f,-27.42f,0.4922f]
execute if score .this aj.fram matches 102 run data modify entity @s Pose.Head set value [12.3879f,-27.2171f,0.8063f]
execute if score .this aj.fram matches 103 run data modify entity @s Pose.Head set value [13.8267f,-26.9195f,0.9728f]