#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run data modify entity @s Pose.Head set value [0.882f,-17.3361f,-56.8249f]
execute if score .this aj.fram matches 89 run data modify entity @s Pose.Head set value [0.8673f,-17.3388f,-55.9914f]
execute if score .this aj.fram matches 90 run data modify entity @s Pose.Head set value [0.8438f,-17.3432f,-55.1609f]
execute if score .this aj.fram matches 91 run data modify entity @s Pose.Head set value [0.8108f,-17.3493f,-54.3356f]
execute if score .this aj.fram matches 92 run data modify entity @s Pose.Head set value [0.768f,-17.3573f,-53.5176f]
execute if score .this aj.fram matches 93 run data modify entity @s Pose.Head set value [0.7147f,-17.3672f,-52.7091f]
execute if score .this aj.fram matches 94 run data modify entity @s Pose.Head set value [0.6503f,-17.3792f,-51.9124f]
execute if score .this aj.fram matches 95 run data modify entity @s Pose.Head set value [0.5742f,-17.3933f,-51.1295f]