#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [0f,-17.5f,-47.5f]