#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [-5.1173f,-25.6836f,-4.713f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [-5.8133f,-25.8161f,-4.4271f]
execute if score .this aj.fram matches 82 run data modify entity @s Pose.Head set value [-6.5078f,-25.9481f,-4.1396f]
execute if score .this aj.fram matches 83 run data modify entity @s Pose.Head set value [-7.1975f,-26.0789f,-3.8517f]
execute if score .this aj.fram matches 84 run data modify entity @s Pose.Head set value [-7.8792f,-26.208f,-3.5645f]
execute if score .this aj.fram matches 85 run data modify entity @s Pose.Head set value [-8.5495f,-26.3346f,-3.2791f]
execute if score .this aj.fram matches 86 run data modify entity @s Pose.Head set value [-9.2051f,-26.4581f,-2.9967f]
execute if score .this aj.fram matches 87 run data modify entity @s Pose.Head set value [-9.8428f,-26.5779f,-2.7184f]