#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [10f,-27.5f,0f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [10.0748f,-27.534f,0.1305f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [10.2392f,-27.608f,0.4174f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [10.4035f,-27.6808f,0.704f]
execute if score .this aj.fram matches 52 run data modify entity @s Pose.Head set value [10.4781f,-27.7135f,0.8342f]
execute if score .this aj.fram matches 53 run data modify entity @s Pose.Head set value [10.3736f,-27.6676f,0.6519f]
execute if score .this aj.fram matches 54 run data modify entity @s Pose.Head set value [10f,-27.5f,0f]
execute if score .this aj.fram matches 55 run data modify entity @s Pose.Head set value [9.1461f,-27.0952f,-1.4899f]