#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 56 run tp @s ^-0.226 ^0.223 ^1.019 ~ ~
execute if score .this aj.fram matches 57 run tp @s ^-0.697 ^0.629 ^0.856 ~ ~
execute if score .this aj.fram matches 58 run tp @s ^-1.2 ^1.008 ^0.686 ~ ~
execute if score .this aj.fram matches 59 run tp @s ^-1.652 ^1.318 ^0.536 ~ ~
execute if score .this aj.fram matches 60 run tp @s ^-1.966 ^1.535 ^0.435 ~ ~
execute if score .this aj.fram matches 61 run tp @s ^-1.966 ^1.535 ^0.435 ~ ~
execute if score .this aj.fram matches 62 run tp @s ^-1.967 ^1.537 ^0.433 ~ ~
execute if score .this aj.fram matches 63 run tp @s ^-1.967 ^1.54 ^0.431 ~ ~