#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [-70.254f,5.6776f,-47.9668f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [-70.3898f,5.3549f,-47.8271f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [-70.6869f,4.6459f,-47.5255f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [-70.9816f,3.9383f,-47.2312f]
execute if score .this aj.fram matches 52 run data modify entity @s Pose.Head set value [-71.1147f,3.6174f,-47.0996f]
execute if score .this aj.fram matches 53 run data modify entity @s Pose.Head set value [-70.9282f,4.0679f,-47.2832f]
execute if score .this aj.fram matches 54 run data modify entity @s Pose.Head set value [-70.2541f,5.6801f,-47.9647f]
execute if score .this aj.fram matches 55 run data modify entity @s Pose.Head set value [-68.6781f,9.3779f,-49.6632f]