#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 96 run tp @s ^-0.92 ^1.255 ^0.237 ~ ~
execute if score .this aj.fram matches 97 run tp @s ^-0.916 ^1.258 ^0.243 ~ ~
execute if score .this aj.fram matches 98 run tp @s ^-0.911 ^1.261 ^0.251 ~ ~
execute if score .this aj.fram matches 99 run tp @s ^-0.906 ^1.263 ^0.259 ~ ~
execute if score .this aj.fram matches 100 run tp @s ^-0.901 ^1.265 ^0.269 ~ ~
execute if score .this aj.fram matches 101 run tp @s ^-0.859 ^1.252 ^0.324 ~ ~
execute if score .this aj.fram matches 102 run tp @s ^-0.781 ^1.206 ^0.391 ~ ~
execute if score .this aj.fram matches 103 run tp @s ^-0.68 ^1.129 ^0.447 ~ ~