#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.076 ^0.153 ^0.896 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.073 ^0.146 ^0.902 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.069 ^0.14 ^0.908 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.065 ^0.134 ^0.914 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.061 ^0.127 ^0.92 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.057 ^0.121 ^0.926 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^-0.053 ^0.115 ^0.932 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^-0.049 ^0.109 ^0.938 ~ ~