#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 128 run tp @s ^-0.523 ^4.889 ^0.786 ~ ~
execute if score .this aj.fram matches 129 run tp @s ^-0.565 ^4.996 ^0.516 ~ ~
execute if score .this aj.fram matches 130 run tp @s ^-0.588 ^5.041 ^0.302 ~ ~
execute if score .this aj.fram matches 131 run tp @s ^-0.604 ^4.214 ^-0.139 ~ ~
execute if score .this aj.fram matches 132 run tp @s ^-0.599 ^3.39 ^-0.045 ~ ~
execute if score .this aj.fram matches 133 run tp @s ^-0.593 ^2.533 ^0.176 ~ ~
execute if score .this aj.fram matches 134 run tp @s ^-0.588 ^1.601 ^0.302 ~ ~
execute if score .this aj.fram matches 135 run tp @s ^-0.586 ^0.885 ^0.344 ~ ~