#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^-0.013 ^0.052 ^0.991 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^-0.009 ^0.045 ^0.997 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^-0.006 ^0.039 ^1.002 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^-0.002 ^0.033 ^1.008 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.002 ^0.026 ^1.014 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.006 ^0.02 ^1.02 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.01 ^0.014 ^1.026 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^0.014 ^0.007 ^1.032 ~ ~