#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 184 run data modify entity @s Pose.Head set value [-6.2043f,-15.2093f,87.4076f]
execute if score .this aj.fram matches 185 run data modify entity @s Pose.Head set value [-6.5095f,-14.969f,88.4427f]
execute if score .this aj.fram matches 186 run data modify entity @s Pose.Head set value [-6.7267f,-14.8755f,89.3216f]
execute if score .this aj.fram matches 187 run data modify entity @s Pose.Head set value [-6.8678f,-14.9152f,90.057f]
execute if score .this aj.fram matches 188 run data modify entity @s Pose.Head set value [-6.9433f,-15.0712f,90.6598f]
execute if score .this aj.fram matches 189 run data modify entity @s Pose.Head set value [-6.9636f,-15.3236f,91.1409f]
execute if score .this aj.fram matches 190 run data modify entity @s Pose.Head set value [-6.9388f,-15.6495f,91.511f]
execute if score .this aj.fram matches 191 run data modify entity @s Pose.Head set value [-6.8793f,-16.0238f,91.782f]