#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 56 run data modify entity @s Pose.Head set value [-66.2128f,15.0594f,-52.6502f]
execute if score .this aj.fram matches 57 run data modify entity @s Pose.Head set value [-63.4193f,21.533f,-56.6612f]
execute if score .this aj.fram matches 58 run data modify entity @s Pose.Head set value [-60.9322f,27.5675f,-61.0862f]
execute if score .this aj.fram matches 59 run data modify entity @s Pose.Head set value [-59.2599f,31.9798f,-64.8386f]
execute if score .this aj.fram matches 60 run data modify entity @s Pose.Head set value [-58.6628f,33.6844f,-66.429f]
execute if score .this aj.fram matches 61 run data modify entity @s Pose.Head set value [-58.709f,33.6391f,-66.4105f]
execute if score .this aj.fram matches 62 run data modify entity @s Pose.Head set value [-58.8433f,33.5061f,-66.3549f]
execute if score .this aj.fram matches 63 run data modify entity @s Pose.Head set value [-59.0587f,33.2901f,-66.2624f]