#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 216 run data modify entity @s Pose.Head set value [-7.5332f,-10.2171f,62.4075f]
execute if score .this aj.fram matches 217 run data modify entity @s Pose.Head set value [-9.6089f,-4.7964f,46.5222f]
execute if score .this aj.fram matches 218 run data modify entity @s Pose.Head set value [-11.4166f,0.4463f,28.6982f]
execute if score .this aj.fram matches 219 run data modify entity @s Pose.Head set value [-12.998f,4.3795f,12.1368f]
execute if score .this aj.fram matches 220 run data modify entity @s Pose.Head set value [-14.1604f,6.4655f,0.2626f]
execute if score .this aj.fram matches 221 run data modify entity @s Pose.Head set value [-15.0047f,5.5911f,-7.0006f]
execute if score .this aj.fram matches 222 run data modify entity @s Pose.Head set value [-15.5491f,5.619f,-6.3895f]
execute if score .this aj.fram matches 223 run data modify entity @s Pose.Head set value [-15.4438f,6.1599f,-2.3775f]