#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 104 run data modify entity @s Pose.Head set value [-36.064f,-2.9554f,-27.5133f]
execute if score .this aj.fram matches 105 run data modify entity @s Pose.Head set value [-22.3058f,-6.5407f,-18.4959f]
execute if score .this aj.fram matches 106 run data modify entity @s Pose.Head set value [-8.3342f,-11.1998f,-9.2756f]
execute if score .this aj.fram matches 107 run data modify entity @s Pose.Head set value [4.7982f,-16.4415f,-1.0528f]
execute if score .this aj.fram matches 108 run data modify entity @s Pose.Head set value [16.1027f,-21.3265f,5.3895f]
execute if score .this aj.fram matches 109 run data modify entity @s Pose.Head set value [24.4241f,-24.8885f,9.9358f]
execute if score .this aj.fram matches 110 run data modify entity @s Pose.Head set value [28.3465f,-26.4361f,12.9413f]
execute if score .this aj.fram matches 111 run data modify entity @s Pose.Head set value [28.3155f,-26.3339f,14.053f]