#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run tp @s ^-1.003 ^0.848 ^0.608 ~ ~
execute if score .this aj.fram matches 153 run tp @s ^-1.01 ^0.875 ^0.564 ~ ~
execute if score .this aj.fram matches 154 run tp @s ^-1.01 ^0.909 ^0.527 ~ ~
execute if score .this aj.fram matches 155 run tp @s ^-1.004 ^0.946 ^0.495 ~ ~
execute if score .this aj.fram matches 156 run tp @s ^-0.993 ^0.983 ^0.47 ~ ~
execute if score .this aj.fram matches 157 run tp @s ^-0.977 ^1.015 ^0.45 ~ ~
execute if score .this aj.fram matches 158 run tp @s ^-0.957 ^1.039 ^0.437 ~ ~
execute if score .this aj.fram matches 159 run tp @s ^-0.933 ^1.052 ^0.428 ~ ~