#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0.107 ^0.038 ^0.638 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0.111 ^0.032 ^0.644 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0.115 ^0.025 ^0.65 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0.119 ^0.019 ^0.656 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0.122 ^0.013 ^0.662 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0.126 ^0.006 ^0.668 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.13 ^0 ^0.674 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0.134 ^-0.006 ^0.68 ~ ~