#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run tp @s ^-0.655 ^0.887 ^0.162 ~ ~
execute if score .this aj.fram matches 153 run tp @s ^-0.659 ^0.923 ^0.155 ~ ~
execute if score .this aj.fram matches 154 run tp @s ^-0.661 ^0.96 ^0.149 ~ ~
execute if score .this aj.fram matches 155 run tp @s ^-0.663 ^0.995 ^0.144 ~ ~
execute if score .this aj.fram matches 156 run tp @s ^-0.664 ^1.027 ^0.141 ~ ~
execute if score .this aj.fram matches 157 run tp @s ^-0.664 ^1.054 ^0.14 ~ ~
execute if score .this aj.fram matches 158 run tp @s ^-0.663 ^1.075 ^0.142 ~ ~
execute if score .this aj.fram matches 159 run tp @s ^-0.661 ^1.089 ^0.147 ~ ~