#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run tp @s ^-0.312 ^0.862 ^0 ~ ~
execute if score .this aj.fram matches 153 run tp @s ^-0.312 ^0.898 ^0 ~ ~
execute if score .this aj.fram matches 154 run tp @s ^-0.312 ^0.932 ^0 ~ ~
execute if score .this aj.fram matches 155 run tp @s ^-0.312 ^0.963 ^0 ~ ~
execute if score .this aj.fram matches 156 run tp @s ^-0.312 ^0.991 ^0 ~ ~
execute if score .this aj.fram matches 157 run tp @s ^-0.312 ^1.016 ^0 ~ ~
execute if score .this aj.fram matches 158 run tp @s ^-0.312 ^1.037 ^0 ~ ~
execute if score .this aj.fram matches 159 run tp @s ^-0.312 ^1.054 ^0 ~ ~