#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-157.754f,5.6776f,-47.9668f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-157.754f,5.6776f,-47.9668f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-157.754f,5.6776f,-47.9668f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-157.754f,5.6776f,-47.9668f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-157.754f,5.6776f,-47.9668f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-157.754f,5.6776f,-47.9668f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-157.754f,5.6776f,-47.9668f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-157.754f,5.6776f,-47.9668f]