#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run data modify entity @s Pose.Head set value [1.9777f,29.5936f,1.8728f]
execute if score .this aj.fram matches 65 run data modify entity @s Pose.Head set value [2.258f,29.6984f,1.8946f]
execute if score .this aj.fram matches 66 run data modify entity @s Pose.Head set value [2.5929f,29.825f,1.9219f]
execute if score .this aj.fram matches 67 run data modify entity @s Pose.Head set value [2.9795f,29.9729f,1.9553f]
execute if score .this aj.fram matches 68 run data modify entity @s Pose.Head set value [3.4152f,30.142f,1.9951f]
execute if score .this aj.fram matches 69 run data modify entity @s Pose.Head set value [3.8972f,30.332f,2.0417f]
execute if score .this aj.fram matches 70 run data modify entity @s Pose.Head set value [4.4228f,30.5427f,2.0954f]
execute if score .this aj.fram matches 71 run data modify entity @s Pose.Head set value [4.9892f,30.7741f,2.1564f]