#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 216 run data modify entity @s Pose.Head set value [-93.8281f,-28.4444f,58.5439f]
execute if score .this aj.fram matches 217 run data modify entity @s Pose.Head set value [-94.2019f,-29.3602f,41.5356f]
execute if score .this aj.fram matches 218 run data modify entity @s Pose.Head set value [-94.3538f,-30.4296f,22.4399f]
execute if score .this aj.fram matches 219 run data modify entity @s Pose.Head set value [-94.6428f,-31.942f,4.8233f]
execute if score .this aj.fram matches 220 run data modify entity @s Pose.Head set value [-95.0735f,-33.5919f,-7.5993f]
execute if score .this aj.fram matches 221 run data modify entity @s Pose.Head set value [-96.8079f,-36.9379f,-14.0231f]
execute if score .this aj.fram matches 222 run data modify entity @s Pose.Head set value [-100.0457f,-37.1313f,-11.0264f]
execute if score .this aj.fram matches 223 run data modify entity @s Pose.Head set value [-100.7361f,-35.4647f,-6.366f]