#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 104 run tp @s ^-0.292 ^0.106 ^0.268 ~ ~
execute if score .this aj.fram matches 105 run tp @s ^-0.286 ^0.089 ^0.258 ~ ~
execute if score .this aj.fram matches 106 run tp @s ^-0.279 ^0.071 ^0.247 ~ ~
execute if score .this aj.fram matches 107 run tp @s ^-0.27 ^0.054 ^0.236 ~ ~
execute if score .this aj.fram matches 108 run tp @s ^-0.262 ^0.039 ^0.226 ~ ~
execute if score .this aj.fram matches 109 run tp @s ^-0.254 ^0.027 ^0.217 ~ ~
execute if score .this aj.fram matches 110 run tp @s ^-0.249 ^0.02 ^0.211 ~ ~
execute if score .this aj.fram matches 111 run tp @s ^-0.248 ^0.018 ^0.21 ~ ~