#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 56 run data modify entity @s Pose.Head set value [-151.7703f,52.4226f,-58.3857f]
execute if score .this aj.fram matches 57 run data modify entity @s Pose.Head set value [-151.7703f,52.4226f,-60.1045f]
execute if score .this aj.fram matches 58 run data modify entity @s Pose.Head set value [-151.7703f,52.4225f,-61.7192f]
execute if score .this aj.fram matches 59 run data modify entity @s Pose.Head set value [-151.7702f,52.4225f,-62.9172f]
execute if score .this aj.fram matches 60 run data modify entity @s Pose.Head set value [-151.7702f,52.4225f,-63.386f]
execute if score .this aj.fram matches 61 run data modify entity @s Pose.Head set value [-151.8077f,52.4358f,-63.4007f]
execute if score .this aj.fram matches 62 run data modify entity @s Pose.Head set value [-151.9162f,52.4744f,-63.4429f]
execute if score .this aj.fram matches 63 run data modify entity @s Pose.Head set value [-152.0901f,52.5363f,-63.5095f]