#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 120 run data modify entity @s Pose.Head set value [23.4274f,48.5178f,0.2677f]
execute if score .this aj.fram matches 121 run data modify entity @s Pose.Head set value [23.4299f,48.4785f,0.2877f]
execute if score .this aj.fram matches 122 run data modify entity @s Pose.Head set value [23.4328f,48.4343f,0.3103f]
execute if score .this aj.fram matches 123 run data modify entity @s Pose.Head set value [23.4359f,48.3871f,0.3344f]
execute if score .this aj.fram matches 124 run data modify entity @s Pose.Head set value [23.4391f,48.3393f,0.359f]
execute if score .this aj.fram matches 125 run data modify entity @s Pose.Head set value [23.4423f,48.2929f,0.3829f]
execute if score .this aj.fram matches 126 run data modify entity @s Pose.Head set value [23.4454f,48.2501f,0.405f]
execute if score .this aj.fram matches 127 run data modify entity @s Pose.Head set value [23.448f,48.2131f,0.4241f]