#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 216 run data modify entity @s Pose.Head set value [-106.3351f,6.1292f,-11.4834f]
execute if score .this aj.fram matches 217 run data modify entity @s Pose.Head set value [-99.7886f,11.7146f,-10.952f]
execute if score .this aj.fram matches 218 run data modify entity @s Pose.Head set value [-92.9175f,17.3216f,-10.512f]
execute if score .this aj.fram matches 219 run data modify entity @s Pose.Head set value [-86.8692f,22.1792f,-10.1996f]
execute if score .this aj.fram matches 220 run data modify entity @s Pose.Head set value [-82.81f,25.51f,-10.02f]
execute if score .this aj.fram matches 221 run data modify entity @s Pose.Head set value [-80.1481f,25.7321f,-9.7478f]
execute if score .this aj.fram matches 222 run data modify entity @s Pose.Head set value [-80.3276f,25.7178f,-9.726f]
execute if score .this aj.fram matches 223 run data modify entity @s Pose.Head set value [-81.7483f,25.5997f,-9.8512f]