#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 224 run tp @s ^-0.275 ^1.321 ^0.375 ~ ~
execute if score .this aj.fram matches 225 run tp @s ^-0.269 ^0.216 ^0.327 ~ ~
execute if score .this aj.fram matches 226 run tp @s ^-0.256 ^-0.858 ^0.233 ~ ~
execute if score .this aj.fram matches 227 run tp @s ^-0.256 ^-0.858 ^0.233 ~ ~
execute if score .this aj.fram matches 228 run tp @s ^-0.256 ^-0.858 ^0.233 ~ ~
execute if score .this aj.fram matches 229 run tp @s ^-0.256 ^-0.858 ^0.233 ~ ~
execute if score .this aj.fram matches 230 run tp @s ^-0.256 ^-0.858 ^0.233 ~ ~
execute if score .this aj.fram matches 231 run tp @s ^-0.256 ^-0.858 ^0.233 ~ ~