#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 176 run data modify entity @s Pose.Head set value [-39.8948f,38.3666f,-7.2833f]
execute if score .this aj.fram matches 177 run data modify entity @s Pose.Head set value [-41.5704f,38.0323f,-7.4132f]
execute if score .this aj.fram matches 178 run data modify entity @s Pose.Head set value [-45.14f,37.32f,-7.69f]
execute if score .this aj.fram matches 179 run data modify entity @s Pose.Head set value [-81.1434f,17.569f,-9.6149f]
execute if score .this aj.fram matches 180 run data modify entity @s Pose.Head set value [-114.0838f,-1.9489f,-12.4444f]
execute if score .this aj.fram matches 181 run data modify entity @s Pose.Head set value [-115.1907f,-2.9566f,-12.6283f]
execute if score .this aj.fram matches 182 run data modify entity @s Pose.Head set value [-115.6637f,-3.7194f,-12.7707f]
execute if score .this aj.fram matches 183 run data modify entity @s Pose.Head set value [-115.5778f,-4.2617f,-12.8736f]