#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run tp @s ^0.296 ^-0.266 ^0.921 ~ ~
execute if score .this aj.fram matches 49 run tp @s ^0.366 ^-0.347 ^0.96 ~ ~
execute if score .this aj.fram matches 50 run tp @s ^0.472 ^-0.467 ^1.004 ~ ~
execute if score .this aj.fram matches 51 run tp @s ^0.58 ^-0.587 ^1.044 ~ ~
execute if score .this aj.fram matches 52 run tp @s ^0.658 ^-0.67 ^1.068 ~ ~
execute if score .this aj.fram matches 53 run tp @s ^0.674 ^-0.675 ^1.067 ~ ~
execute if score .this aj.fram matches 54 run tp @s ^0.596 ^-0.566 ^1.03 ~ ~
execute if score .this aj.fram matches 55 run tp @s ^0.375 ^-0.291 ^0.938 ~ ~