#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 128 run data modify entity @s Pose.Head set value [23.4502f,48.184f,0.4392f]
execute if score .this aj.fram matches 129 run data modify entity @s Pose.Head set value [23.4516f,48.1649f,0.4491f]
execute if score .this aj.fram matches 130 run data modify entity @s Pose.Head set value [23.4521f,48.1581f,0.4527f]
execute if score .this aj.fram matches 131 run data modify entity @s Pose.Head set value [23.4521f,48.1581f,0.4527f]
execute if score .this aj.fram matches 132 run data modify entity @s Pose.Head set value [23.4521f,48.1581f,0.4527f]
execute if score .this aj.fram matches 133 run data modify entity @s Pose.Head set value [23.4521f,48.1581f,0.4527f]
execute if score .this aj.fram matches 134 run data modify entity @s Pose.Head set value [23.4521f,48.1581f,0.4527f]
execute if score .this aj.fram matches 135 run data modify entity @s Pose.Head set value [23.4521f,48.1581f,0.4527f]