#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [11.4307f,33.7559f,2.9865f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [12.2363f,34.179f,3.0957f]
execute if score .this aj.fram matches 82 run data modify entity @s Pose.Head set value [13.047f,34.6172f,3.2038f]
execute if score .this aj.fram matches 83 run data modify entity @s Pose.Head set value [13.8589f,35.0691f,3.3095f]
execute if score .this aj.fram matches 84 run data modify entity @s Pose.Head set value [14.6684f,35.533f,3.4113f]
execute if score .this aj.fram matches 85 run data modify entity @s Pose.Head set value [15.4715f,36.0068f,3.5078f]
execute if score .this aj.fram matches 86 run data modify entity @s Pose.Head set value [16.2645f,36.4886f,3.5976f]
execute if score .this aj.fram matches 87 run data modify entity @s Pose.Head set value [17.0434f,36.9759f,3.6796f]