#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 128 run data modify entity @s Pose.Head set value [-45.0651f,37.3485f,-7.715f]
execute if score .this aj.fram matches 129 run data modify entity @s Pose.Head set value [-45.1202f,37.3275f,-7.6966f]
execute if score .this aj.fram matches 130 run data modify entity @s Pose.Head set value [-45.14f,37.32f,-7.69f]
execute if score .this aj.fram matches 131 run data modify entity @s Pose.Head set value [-45.14f,37.32f,-7.69f]
execute if score .this aj.fram matches 132 run data modify entity @s Pose.Head set value [-45.14f,37.32f,-7.69f]
execute if score .this aj.fram matches 133 run data modify entity @s Pose.Head set value [-45.14f,37.32f,-7.69f]
execute if score .this aj.fram matches 134 run data modify entity @s Pose.Head set value [-45.14f,37.32f,-7.69f]
execute if score .this aj.fram matches 135 run data modify entity @s Pose.Head set value [-45.14f,37.32f,-7.69f]