#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run data modify entity @s Pose.Head set value [-146.8525f,33.0012f,-66.1379f]
execute if score .this aj.fram matches 65 run data modify entity @s Pose.Head set value [-147.2111f,32.6365f,-65.9736f]
execute if score .this aj.fram matches 66 run data modify entity @s Pose.Head set value [-147.6294f,32.204f,-65.7723f]
execute if score .this aj.fram matches 67 run data modify entity @s Pose.Head set value [-148.1001f,31.7085f,-65.534f]
execute if score .this aj.fram matches 68 run data modify entity @s Pose.Head set value [-148.6161f,31.1551f,-65.259f]
execute if score .this aj.fram matches 69 run data modify entity @s Pose.Head set value [-149.1702f,30.5486f,-64.9478f]
execute if score .this aj.fram matches 70 run data modify entity @s Pose.Head set value [-149.7556f,29.8936f,-64.6012f]
execute if score .this aj.fram matches 71 run data modify entity @s Pose.Head set value [-150.3657f,29.195f,-64.2205f]