#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [-156.0292f,21.6299f,-59.5887f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [-156.5898f,20.7151f,-58.9887f]
execute if score .this aj.fram matches 82 run data modify entity @s Pose.Head set value [-157.1219f,19.7971f,-58.3822f]
execute if score .this aj.fram matches 83 run data modify entity @s Pose.Head set value [-157.6221f,18.8788f,-57.7719f]
execute if score .this aj.fram matches 84 run data modify entity @s Pose.Head set value [-158.0871f,17.963f,-57.1604f]
execute if score .this aj.fram matches 85 run data modify entity @s Pose.Head set value [-158.5137f,17.0522f,-56.5499f]
execute if score .this aj.fram matches 86 run data modify entity @s Pose.Head set value [-158.8987f,16.149f,-55.9425f]
execute if score .this aj.fram matches 87 run data modify entity @s Pose.Head set value [-159.2388f,15.2558f,-55.3398f]