#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 208 run data modify entity @s Pose.Head set value [-110.0051f,-3.9534f,-12.7238f]
execute if score .this aj.fram matches 209 run data modify entity @s Pose.Head set value [-111.3475f,-3.9369f,-12.7214f]
execute if score .this aj.fram matches 210 run data modify entity @s Pose.Head set value [-112.4925f,-3.8155f,-12.704f]
execute if score .this aj.fram matches 211 run data modify entity @s Pose.Head set value [-113.3896f,-3.5727f,-12.6694f]
execute if score .this aj.fram matches 212 run data modify entity @s Pose.Head set value [-113.9879f,-3.1919f,-12.6156f]
execute if score .this aj.fram matches 213 run data modify entity @s Pose.Head set value [-114.2365f,-2.6562f,-12.541f]
execute if score .this aj.fram matches 214 run data modify entity @s Pose.Head set value [-114.0838f,-1.9489f,-12.4444f]
execute if score .this aj.fram matches 215 run data modify entity @s Pose.Head set value [-111.4513f,1.3255f,-12.0248f]