#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 96 run data modify entity @s Pose.Head set value [22.8273f,41.1589f,3.9532f]
execute if score .this aj.fram matches 97 run data modify entity @s Pose.Head set value [23.2739f,41.546f,3.9317f]
execute if score .this aj.fram matches 98 run data modify entity @s Pose.Head set value [23.6707f,41.9065f,3.9018f]
execute if score .this aj.fram matches 99 run data modify entity @s Pose.Head set value [24.0153f,42.2373f,3.8647f]
execute if score .this aj.fram matches 100 run data modify entity @s Pose.Head set value [24.3051f,42.5356f,3.8213f]
execute if score .this aj.fram matches 101 run data modify entity @s Pose.Head set value [25.123f,43.5771f,3.5829f]
execute if score .this aj.fram matches 102 run data modify entity @s Pose.Head set value [25.5439f,44.4585f,3.2671f]
execute if score .this aj.fram matches 103 run data modify entity @s Pose.Head set value [25.6482f,45.1972f,2.9038f]