#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 136 run data modify entity @s Pose.Head set value [-116.8963f,39.4289f,3.2715f]
execute if score .this aj.fram matches 137 run data modify entity @s Pose.Head set value [-109.6063f,37.3175f,5.5206f]
execute if score .this aj.fram matches 138 run data modify entity @s Pose.Head set value [-102.237f,35.1811f,7.7941f]
execute if score .this aj.fram matches 139 run data modify entity @s Pose.Head set value [-95.7234f,33.2889f,9.8034f]
execute if score .this aj.fram matches 140 run data modify entity @s Pose.Head set value [-91f,31.91f,11.26f]
execute if score .this aj.fram matches 141 run data modify entity @s Pose.Head set value [-89.1991f,31.2576f,11.7991f]
execute if score .this aj.fram matches 142 run data modify entity @s Pose.Head set value [-87.9473f,30.5735f,12.1438f]
execute if score .this aj.fram matches 143 run data modify entity @s Pose.Head set value [-87.1414f,29.909f,12.3367f]