#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [24.3154f,42.5432f,3.8268f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [24.3154f,42.5432f,3.8268f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [24.3154f,42.5432f,3.8268f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [24.3154f,42.5432f,3.8268f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [24.3154f,42.5432f,3.8268f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [24.3154f,42.5432f,3.8268f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [24.3154f,42.5432f,3.8268f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [24.3154f,42.5432f,3.8268f]