#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 112 run tp @s ^-0.561 ^0.826 ^0.176 ~ ~
execute if score .this aj.fram matches 113 run tp @s ^-0.56 ^0.835 ^0.188 ~ ~
execute if score .this aj.fram matches 114 run tp @s ^-0.558 ^0.847 ^0.204 ~ ~
execute if score .this aj.fram matches 115 run tp @s ^-0.554 ^0.863 ^0.223 ~ ~
execute if score .this aj.fram matches 116 run tp @s ^-0.55 ^0.883 ^0.243 ~ ~
execute if score .this aj.fram matches 117 run tp @s ^-0.545 ^0.907 ^0.262 ~ ~
execute if score .this aj.fram matches 118 run tp @s ^-0.542 ^0.936 ^0.279 ~ ~
execute if score .this aj.fram matches 119 run tp @s ^-0.54 ^0.968 ^0.293 ~ ~