#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 56 run tp @s ^-1.103 ^-0.198 ^-0.896 ~ ~
execute if score .this aj.fram matches 57 run tp @s ^-1.527 ^-0.223 ^-0.882 ~ ~
execute if score .this aj.fram matches 58 run tp @s ^-1.96 ^-0.391 ^-0.789 ~ ~
execute if score .this aj.fram matches 59 run tp @s ^-2.32 ^-0.647 ^-0.68 ~ ~
execute if score .this aj.fram matches 60 run tp @s ^-2.555 ^-0.864 ^-0.603 ~ ~
execute if score .this aj.fram matches 61 run tp @s ^-2.555 ^-0.864 ^-0.602 ~ ~
execute if score .this aj.fram matches 62 run tp @s ^-2.556 ^-0.864 ^-0.602 ~ ~
execute if score .this aj.fram matches 63 run tp @s ^-2.556 ^-0.863 ^-0.601 ~ ~