#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 128 run data modify entity @s Pose.Head set value [-120.6326f,40.1366f,2.325f]
execute if score .this aj.fram matches 129 run data modify entity @s Pose.Head set value [-124.5299f,41.4791f,0.9688f]
execute if score .this aj.fram matches 130 run data modify entity @s Pose.Head set value [-127.5f,42.5f,0f]
execute if score .this aj.fram matches 131 run data modify entity @s Pose.Head set value [-135.2925f,45.1283f,-2.3923f]
execute if score .this aj.fram matches 132 run data modify entity @s Pose.Head set value [-135.9475f,45.2775f,-2.5956f]
execute if score .this aj.fram matches 133 run data modify entity @s Pose.Head set value [-132.3788f,44.038f,-1.5012f]
execute if score .this aj.fram matches 134 run data modify entity @s Pose.Head set value [-127.5f,42.5f,0f]
execute if score .this aj.fram matches 135 run data modify entity @s Pose.Head set value [-123.1725f,41.2461f,1.3351f]