#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-151.77f,52.42f,-55.89f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-151.77f,52.42f,-55.89f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-151.77f,52.42f,-55.89f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-151.77f,52.42f,-55.89f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-151.77f,52.42f,-55.89f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-151.77f,52.42f,-55.89f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-151.77f,52.42f,-55.89f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-151.77f,52.42f,-55.89f]