#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 232 run tp @s ^-0.276 ^-1.372 ^0.338 ~ ~
execute if score .this aj.fram matches 233 run tp @s ^-0.276 ^-1.372 ^0.338 ~ ~
execute if score .this aj.fram matches 234 run tp @s ^-0.276 ^-1.372 ^0.338 ~ ~
execute if score .this aj.fram matches 235 run tp @s ^-0.276 ^-1.372 ^0.338 ~ ~
execute if score .this aj.fram matches 236 run tp @s ^-0.276 ^-1.372 ^0.338 ~ ~
execute if score .this aj.fram matches 237 run tp @s ^-0.369 ^-1.409 ^0.192 ~ ~
execute if score .this aj.fram matches 238 run tp @s ^-0.338 ^-1.404 ^0.028 ~ ~
execute if score .this aj.fram matches 239 run tp @s ^-0.271 ^-1.394 ^0.078 ~ ~