#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run tp @s ^-0.858 ^-0.4 ^-0.704 ~ ~
execute if score .this aj.fram matches 49 run tp @s ^-0.807 ^-0.414 ^-0.706 ~ ~
execute if score .this aj.fram matches 50 run tp @s ^-0.72 ^-0.428 ^-0.686 ~ ~
execute if score .this aj.fram matches 51 run tp @s ^-0.627 ^-0.439 ^-0.658 ~ ~
execute if score .this aj.fram matches 52 run tp @s ^-0.556 ^-0.439 ^-0.64 ~ ~
execute if score .this aj.fram matches 53 run tp @s ^-0.534 ^-0.417 ^-0.654 ~ ~
execute if score .this aj.fram matches 54 run tp @s ^-0.591 ^-0.367 ^-0.712 ~ ~
execute if score .this aj.fram matches 55 run tp @s ^-0.776 ^-0.277 ^-0.817 ~ ~