#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.858 ^-0.213 ^-0.516 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.858 ^-0.217 ^-0.52 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.858 ^-0.22 ^-0.524 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.858 ^-0.224 ^-0.528 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.858 ^-0.228 ^-0.532 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.858 ^-0.232 ^-0.536 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^-0.858 ^-0.236 ^-0.54 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.858 ^-0.24 ^-0.543 ~ ~