#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.858 ^-0.244 ^-0.547 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.858 ^-0.248 ^-0.551 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.858 ^-0.252 ^-0.555 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.858 ^-0.256 ^-0.559 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.858 ^-0.259 ^-0.563 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.858 ^-0.263 ^-0.567 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^-0.858 ^-0.267 ^-0.571 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^-0.858 ^-0.271 ^-0.575 ~ ~