#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.emis.root] run function emis:animations/dies/zzz/conditional/292
execute if score #execute aj.i matches 0 run function emis:animations/dies/zzz/conditional/293