#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.087 ^-0.189 ^0.045 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.187 ^-0.188 ^0.125 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.205 ^-0.188 ^0.137 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.211 ^-0.188 ^0.141 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.205 ^-0.188 ^0.137 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.187 ^-0.188 ^0.125 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^-0.094 ^-0.188 ^0.063 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0 ^-0.188 ^0 ~ ~