#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.04 ^-1.004 ^0.148 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.062 ^-1 ^0.125 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.08 ^-1 ^0.137 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.086 ^-1 ^0.141 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.08 ^-1 ^0.137 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.062 ^-1 ^0.125 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.031 ^-1 ^0.063 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.125 ^-1 ^0 ~ ~