#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [-8.7063f,24.1687f,83.7484f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [12.1366f,32.3262f,79.8387f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [47.2222f,47.0771f,84.0136f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [97.0897f,56.1922f,107.1138f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [134.8297f,53.8505f,126.434f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [146.7557f,52.1929f,128.4233f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [154.6847f,52.252f,127.1724f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [156.6597f,55.0691f,122.7738f]