#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-178.0803f,42.3274f,136.9094f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-172.6603f,29.7694f,132.1219f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [165.6924f,46.6927f,116.8145f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [113.2446f,53.606f,71.702f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [70.3965f,31.451f,35.9473f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [52.5412f,-1.1252f,25.7625f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [43.76f,-31.0998f,22.252f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [45.0612f,-46.3138f,19.1747f]