#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.52 ^0.356 ^0.186 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.506 ^0.356 ^0.221 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.49 ^0.356 ^0.255 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.472 ^0.356 ^0.287 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.452 ^0.356 ^0.318 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.429 ^0.356 ^0.348 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.405 ^0.356 ^0.376 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.379 ^0.356 ^0.402 ~ ~