#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.204 ^-0.633 ^0.457 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.429 ^-0.614 ^0.233 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.402 ^-0.588 ^-0.027 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.122 ^-0.561 ^-0.186 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^0.116 ^-0.552 ^-0.165 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^0.293 ^-0.543 ^0.074 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^0.274 ^-0.542 ^0.087 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^0.259 ^-0.541 ^0.099 ~ ~