#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [3.4648f,-22.5651f,-31.8252f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [3.4648f,-22.5651f,-31.8252f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [3.4648f,-22.5651f,-31.8252f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [3.4648f,-22.5651f,-31.8252f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [3.4648f,-22.5651f,-31.8252f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [3.4648f,-22.5651f,-31.8252f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [3.4648f,-22.5651f,-31.8252f]