#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.084 ^-1.405 ^0.232 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.164 ^-1.4 ^0.163 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.153 ^-1.391 ^0.123 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.048 ^-1.381 ^0.109 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.011 ^-1.372 ^0.111 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^0.021 ^-1.363 ^0.21 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^0.002 ^-1.362 ^0.223 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.013 ^-1.361 ^0.235 ~ ~