#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.027 ^-1.043 ^0.154 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.071 ^-1.038 ^0.138 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.064 ^-1.029 ^0.162 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.003 ^-1.019 ^0.195 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.03 ^-1.01 ^0.207 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^-0.053 ^-1 ^0.273 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^-0.073 ^-0.999 ^0.285 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.087 ^-0.999 ^0.298 ~ ~