#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [23.2712f,25.8066f,67.227f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [36.6126f,31.018f,70.7579f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [53.9954f,35.5909f,75.4132f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [36.4462f,30.8801f,70.4342f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-4.3996f,18.2444f,65.0202f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-57.0057f,-0.2974f,67.8155f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-96.1737f,-11.5706f,76.2783f]