#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.038 ^-1.047 ^-0.119 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.038 ^-1.047 ^-0.119 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.038 ^-1.047 ^-0.119 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.038 ^-1.047 ^-0.119 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.038 ^-1.047 ^-0.119 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.038 ^-1.047 ^-0.119 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^-0.038 ^-1.047 ^-0.119 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^-0.038 ^-1.047 ^-0.119 ~ ~