#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-60.6167f,9.1285f,49.9191f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-60.6167f,9.1285f,49.9191f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [-60.6167f,9.1285f,49.9191f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [-60.6167f,9.1285f,49.9191f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [-60.6167f,9.1285f,49.9191f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-60.6167f,9.1285f,49.9191f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-60.6167f,9.1285f,49.9191f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-60.6167f,9.1285f,49.9191f]