#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [141.1472f,56.2661f,-157.1021f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [137.2577f,45.8918f,-162.0427f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [134.7495f,34.3755f,-165.857f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [137.2577f,45.8918f,-162.0427f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [156.3261f,70.3034f,-140.0662f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-88.5773f,66.9913f,-20.7259f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-74.1348f,42.2175f,-2.6145f]