#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^0.212 ^-1.372 ^-0.181 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^0.387 ^-1.312 ^0.098 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^0.298 ^-1.23 ^0.495 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^0.003 ^-1.142 ^0.695 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.332 ^-1.142 ^0.605 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^-0.531 ^-1.158 ^0.414 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^-0.534 ^-1.194 ^0.454 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.52 ^-1.238 ^0.496 ~ ~