#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.fram = @s aj.fram
execute rotated ~ 0 as @e[type=#emis:bone_entities,tag=aj.emis.bone,distance=..4.348999999999999] if score @s aj.id = .this aj.id run function emis:animations/stom/tree/trunk
scoreboard players operation @s aj.fram += .aj.emis.framerate aj.i
scoreboard players set .aj.animation aj.emis.anim 1
execute unless score @s aj.fram matches 0..31 run function emis:animations/stom/edge