#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.emis.root] at @s run function emis:animations/spw1/zzz/conditional/200
execute if score #execute aj.i matches 0 run function emis:animations/spw1/zzz/conditional/201