#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 312 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 313 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 314 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 315 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 316 run tp @s ^0.552 ^0.27 ^-0.007 ~ ~
execute if score .this aj.fram matches 317 run tp @s ^0.552 ^0.263 ^-0.007 ~ ~
execute if score .this aj.fram matches 318 run tp @s ^0.552 ^0.255 ^-0.007 ~ ~
execute if score .this aj.fram matches 319 run tp @s ^0.552 ^0.247 ^-0.007 ~ ~