#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 280 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 281 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 282 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 283 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 284 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 285 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 286 run tp @s ^0.552 ^0.275 ^-0.007 ~ ~
execute if score .this aj.fram matches 287 run tp @s ^0.552 ^0.271 ^-0.007 ~ ~