#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 368 run tp @s ^0.552 ^0.278 ^-0.333 ~ ~
execute if score .this aj.fram matches 369 run tp @s ^0.552 ^0.278 ^-0.36 ~ ~
execute if score .this aj.fram matches 370 run tp @s ^0.552 ^0.278 ^-0.388 ~ ~
execute if score .this aj.fram matches 371 run tp @s ^0.552 ^0.278 ^-0.415 ~ ~
execute if score .this aj.fram matches 372 run tp @s ^0.552 ^0.278 ^-0.442 ~ ~
execute if score .this aj.fram matches 373 run tp @s ^0.552 ^0.278 ^-0.469 ~ ~
execute if score .this aj.fram matches 374 run tp @s ^0.552 ^0.278 ^-0.496 ~ ~
execute if score .this aj.fram matches 375 run tp @s ^0.552 ^0.278 ^-0.523 ~ ~