#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 136 run tp @s ^0.551 ^0.224 ^0.573 ~ ~
execute if score .this aj.fram matches 137 run tp @s ^0.551 ^0.234 ^0.557 ~ ~
execute if score .this aj.fram matches 138 run tp @s ^0.551 ^0.243 ^0.542 ~ ~
execute if score .this aj.fram matches 139 run tp @s ^0.55 ^0.253 ^0.527 ~ ~
execute if score .this aj.fram matches 140 run tp @s ^0.55 ^0.263 ^0.512 ~ ~
execute if score .this aj.fram matches 141 run tp @s ^0.55 ^0.274 ^0.497 ~ ~
execute if score .this aj.fram matches 142 run tp @s ^0.549 ^0.284 ^0.481 ~ ~
execute if score .this aj.fram matches 143 run tp @s ^0.549 ^0.294 ^0.466 ~ ~