#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 200 run tp @s ^0.552 ^0.278 ^-0.007 ~ ~
execute if score .this aj.fram matches 201 run tp @s ^0.552 ^0.276 ^-0.007 ~ ~
execute if score .this aj.fram matches 202 run tp @s ^0.552 ^0.274 ^-0.007 ~ ~
execute if score .this aj.fram matches 203 run tp @s ^0.552 ^0.272 ^-0.007 ~ ~
execute if score .this aj.fram matches 204 run tp @s ^0.552 ^0.269 ^-0.007 ~ ~
execute if score .this aj.fram matches 205 run tp @s ^0.552 ^0.267 ^-0.007 ~ ~
execute if score .this aj.fram matches 206 run tp @s ^0.552 ^0.265 ^-0.007 ~ ~
execute if score .this aj.fram matches 207 run tp @s ^0.552 ^0.263 ^-0.007 ~ ~