#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 160 run tp @s ^0.55 ^0.393 ^0.162 ~ ~
execute if score .this aj.fram matches 161 run tp @s ^0.55 ^0.396 ^0.141 ~ ~
execute if score .this aj.fram matches 162 run tp @s ^0.551 ^0.399 ^0.121 ~ ~
execute if score .this aj.fram matches 163 run tp @s ^0.551 ^0.401 ^0.1 ~ ~
execute if score .this aj.fram matches 164 run tp @s ^0.551 ^0.403 ^0.08 ~ ~
execute if score .this aj.fram matches 165 run tp @s ^0.552 ^0.404 ^0.06 ~ ~
execute if score .this aj.fram matches 166 run tp @s ^0.552 ^0.405 ^0.041 ~ ~
execute if score .this aj.fram matches 167 run tp @s ^0.552 ^0.405 ^0.022 ~ ~