#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 448 run data modify entity @s Pose.Head set value [9.2961f,1.5073f,0.6519f]
execute if score .this aj.fram matches 449 run data modify entity @s Pose.Head set value [8.3443f,1.3588f,0.6158f]
execute if score .this aj.fram matches 450 run data modify entity @s Pose.Head set value [7.385f,1.2084f,0.5705f]
execute if score .this aj.fram matches 451 run data modify entity @s Pose.Head set value [6.4314f,1.0579f,0.5173f]
execute if score .this aj.fram matches 452 run data modify entity @s Pose.Head set value [5.4959f,0.9092f,0.4577f]
execute if score .this aj.fram matches 453 run data modify entity @s Pose.Head set value [4.5907f,0.764f,0.3937f]
execute if score .this aj.fram matches 454 run data modify entity @s Pose.Head set value [3.7273f,0.6241f,0.3275f]
execute if score .this aj.fram matches 455 run data modify entity @s Pose.Head set value [2.9165f,0.4915f,0.2613f]