#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run tp @s ^0.549 ^0.304 ^0.45 ~ ~
execute if score .this aj.fram matches 145 run tp @s ^0.548 ^0.314 ^0.435 ~ ~
execute if score .this aj.fram matches 146 run tp @s ^0.548 ^0.324 ^0.419 ~ ~
execute if score .this aj.fram matches 147 run tp @s ^0.548 ^0.333 ^0.403 ~ ~
execute if score .this aj.fram matches 148 run tp @s ^0.548 ^0.339 ^0.389 ~ ~
execute if score .this aj.fram matches 149 run tp @s ^0.547 ^0.344 ^0.373 ~ ~
execute if score .this aj.fram matches 150 run tp @s ^0.547 ^0.35 ^0.357 ~ ~
execute if score .this aj.fram matches 151 run tp @s ^0.547 ^0.355 ^0.339 ~ ~