#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 256 run tp @s ^0 ^-0.379 ^0 ~ ~
execute if score .this aj.fram matches 257 run tp @s ^0 ^-0.382 ^0 ~ ~
execute if score .this aj.fram matches 258 run tp @s ^0 ^-0.386 ^0 ~ ~
execute if score .this aj.fram matches 259 run tp @s ^0 ^-0.389 ^0 ~ ~
execute if score .this aj.fram matches 260 run tp @s ^0 ^-0.393 ^0 ~ ~
execute if score .this aj.fram matches 261 run tp @s ^0 ^-0.396 ^0 ~ ~
execute if score .this aj.fram matches 262 run tp @s ^0 ^-0.4 ^0 ~ ~
execute if score .this aj.fram matches 263 run tp @s ^0 ^-0.403 ^0 ~ ~