#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 208 run tp @s ^0 ^-0.393 ^0 ~ ~
execute if score .this aj.fram matches 209 run tp @s ^0 ^-0.396 ^0 ~ ~
execute if score .this aj.fram matches 210 run tp @s ^0 ^-0.398 ^0 ~ ~
execute if score .this aj.fram matches 211 run tp @s ^0 ^-0.4 ^0 ~ ~
execute if score .this aj.fram matches 212 run tp @s ^0 ^-0.402 ^0 ~ ~
execute if score .this aj.fram matches 213 run tp @s ^0 ^-0.405 ^0 ~ ~
execute if score .this aj.fram matches 214 run tp @s ^0 ^-0.407 ^0 ~ ~
execute if score .this aj.fram matches 215 run tp @s ^0 ^-0.375 ^0 ~ ~