#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 408 run data modify entity @s Pose.Head set value [0f,62.5f,0f]
execute if score .this aj.fram matches 409 run data modify entity @s Pose.Head set value [0f,62.5f,0f]
execute if score .this aj.fram matches 410 run data modify entity @s Pose.Head set value [0f,62.5f,0f]
execute if score .this aj.fram matches 411 run data modify entity @s Pose.Head set value [0f,62.5f,0f]
execute if score .this aj.fram matches 412 run data modify entity @s Pose.Head set value [0f,62.5f,0f]
execute if score .this aj.fram matches 413 run data modify entity @s Pose.Head set value [0f,62.5f,0f]
execute if score .this aj.fram matches 414 run data modify entity @s Pose.Head set value [0f,62.5f,0f]
execute if score .this aj.fram matches 415 run data modify entity @s Pose.Head set value [0f,62.5f,0f]