#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 288 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 289 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 290 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 291 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 292 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 293 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 294 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 295 run data modify entity @s Pose.Head set value [0f,2.5f,0f]