#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run data modify entity @s Pose.Head set value [7.3976f,3.8485f,0f]
execute if score .this aj.fram matches 153 run data modify entity @s Pose.Head set value [6.8813f,4.0274f,0f]
execute if score .this aj.fram matches 154 run data modify entity @s Pose.Head set value [6.3677f,4.179f,0f]
execute if score .this aj.fram matches 155 run data modify entity @s Pose.Head set value [5.8586f,4.2998f,0f]
execute if score .this aj.fram matches 156 run data modify entity @s Pose.Head set value [5.3559f,4.3863f,0f]
execute if score .this aj.fram matches 157 run data modify entity @s Pose.Head set value [4.8613f,4.4349f,0f]
execute if score .this aj.fram matches 158 run data modify entity @s Pose.Head set value [4.3767f,4.442f,0f]
execute if score .this aj.fram matches 159 run data modify entity @s Pose.Head set value [3.9039f,4.4041f,0f]