#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run data modify entity @s Pose.Head set value [11.4086f,1.8633f,0f]
execute if score .this aj.fram matches 145 run data modify entity @s Pose.Head set value [10.9358f,2.1322f,0f]
execute if score .this aj.fram matches 146 run data modify entity @s Pose.Head set value [10.4512f,2.4022f,0f]
execute if score .this aj.fram matches 147 run data modify entity @s Pose.Head set value [9.9566f,2.6699f,0f]
execute if score .this aj.fram matches 148 run data modify entity @s Pose.Head set value [9.4539f,2.9317f,0f]
execute if score .this aj.fram matches 149 run data modify entity @s Pose.Head set value [8.9448f,3.184f,0f]
execute if score .this aj.fram matches 150 run data modify entity @s Pose.Head set value [8.4312f,3.4233f,0f]
execute if score .this aj.fram matches 151 run data modify entity @s Pose.Head set value [7.9149f,3.646f,0f]