#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 200 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 201 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 202 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 203 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 204 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 205 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 206 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 207 run data modify entity @s Pose.Head set value [0f,2.5f,0f]