#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 368 run tp @s ^0 ^-0.313 ^-0.326 ~ ~
execute if score .this aj.fram matches 369 run tp @s ^0 ^-0.313 ^-0.353 ~ ~
execute if score .this aj.fram matches 370 run tp @s ^0 ^-0.313 ^-0.38 ~ ~
execute if score .this aj.fram matches 371 run tp @s ^0 ^-0.313 ^-0.408 ~ ~
execute if score .this aj.fram matches 372 run tp @s ^0 ^-0.313 ^-0.435 ~ ~
execute if score .this aj.fram matches 373 run tp @s ^0 ^-0.313 ^-0.462 ~ ~
execute if score .this aj.fram matches 374 run tp @s ^0 ^-0.313 ^-0.489 ~ ~
execute if score .this aj.fram matches 375 run tp @s ^0 ^-0.313 ^-0.516 ~ ~