#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run data modify entity @s Pose.Head set value [35.8975f,0f,0f]
execute if score .this aj.fram matches 89 run data modify entity @s Pose.Head set value [35.771f,0f,0f]
execute if score .this aj.fram matches 90 run data modify entity @s Pose.Head set value [35.625f,0f,0f]
execute if score .this aj.fram matches 91 run data modify entity @s Pose.Head set value [35.4696f,0f,0f]
execute if score .this aj.fram matches 92 run data modify entity @s Pose.Head set value [35.315f,0f,0f]
execute if score .this aj.fram matches 93 run data modify entity @s Pose.Head set value [35.1711f,0f,0f]
execute if score .this aj.fram matches 94 run data modify entity @s Pose.Head set value [35.0481f,0f,0f]
execute if score .this aj.fram matches 95 run data modify entity @s Pose.Head set value [34.9561f,0f,0f]