#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 256 run tp @s ^0 ^-0.316 ^0 ~ ~
execute if score .this aj.fram matches 257 run tp @s ^0 ^-0.32 ^0 ~ ~
execute if score .this aj.fram matches 258 run tp @s ^0 ^-0.323 ^0 ~ ~
execute if score .this aj.fram matches 259 run tp @s ^0 ^-0.327 ^0 ~ ~
execute if score .this aj.fram matches 260 run tp @s ^0 ^-0.33 ^0 ~ ~
execute if score .this aj.fram matches 261 run tp @s ^0 ^-0.334 ^0 ~ ~
execute if score .this aj.fram matches 262 run tp @s ^0 ^-0.337 ^0 ~ ~
execute if score .this aj.fram matches 263 run tp @s ^0 ^-0.341 ^0 ~ ~