#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 128 run tp @s ^0 ^-0.412 ^0.533 ~ ~
execute if score .this aj.fram matches 129 run tp @s ^0 ^-0.412 ^0.533 ~ ~
execute if score .this aj.fram matches 130 run tp @s ^0 ^-0.412 ^0.533 ~ ~
execute if score .this aj.fram matches 131 run tp @s ^0 ^-0.403 ^0.519 ~ ~
execute if score .this aj.fram matches 132 run tp @s ^0 ^-0.394 ^0.506 ~ ~
execute if score .this aj.fram matches 133 run tp @s ^0 ^-0.384 ^0.493 ~ ~
execute if score .this aj.fram matches 134 run tp @s ^0 ^-0.375 ^0.479 ~ ~
execute if score .this aj.fram matches 135 run tp @s ^0 ^-0.366 ^0.466 ~ ~