#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^0 ^-0.513 ^0.704 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^0 ^-0.541 ^0.731 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^0 ^-0.569 ^0.758 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^0 ^-0.597 ^0.785 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^0 ^-0.625 ^0.813 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^0 ^-0.634 ^0.82 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^0 ^-0.637 ^0.824 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^0 ^-0.638 ^0.824 ~ ~