#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 184 run data modify entity @s Pose.Head set value [-100.7324f,24.8168f,22.6179f]
execute if score .this aj.fram matches 185 run data modify entity @s Pose.Head set value [-102.5546f,27.5255f,19.232f]
execute if score .this aj.fram matches 186 run data modify entity @s Pose.Head set value [-104.5623f,30.0348f,15.4757f]
execute if score .this aj.fram matches 187 run data modify entity @s Pose.Head set value [-106.7677f,32.3109f,11.344f]
execute if score .this aj.fram matches 188 run data modify entity @s Pose.Head set value [-109.1727f,34.3191f,6.8406f]
execute if score .this aj.fram matches 189 run data modify entity @s Pose.Head set value [-111.7652f,36.0252f,1.9821f]
execute if score .this aj.fram matches 190 run data modify entity @s Pose.Head set value [-114.5168f,37.3976f,-3.2001f]
execute if score .this aj.fram matches 191 run data modify entity @s Pose.Head set value [-117.3811f,38.4089f,-8.6575f]