#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [-21.1728f,18.7472f,-7.096f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [-21.1728f,18.7472f,-7.096f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [-21.1728f,18.7472f,-7.096f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [-21.1728f,18.7472f,-7.096f]
execute if score .this aj.fram matches 52 run data modify entity @s Pose.Head set value [-21.1728f,18.7472f,-7.096f]
execute if score .this aj.fram matches 53 run data modify entity @s Pose.Head set value [-21.1728f,18.7472f,-7.096f]
execute if score .this aj.fram matches 54 run data modify entity @s Pose.Head set value [-21.1728f,18.7472f,-7.096f]
execute if score .this aj.fram matches 55 run data modify entity @s Pose.Head set value [-21.1728f,18.7472f,-7.096f]