#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 328 run tp @s ^0.144 ^-0.375 ^0.277 ~ ~
execute if score .this aj.fram matches 329 run tp @s ^0.144 ^-0.375 ^0.277 ~ ~
execute if score .this aj.fram matches 330 run tp @s ^0.144 ^-0.383 ^0.277 ~ ~
execute if score .this aj.fram matches 331 run tp @s ^0.144 ^-0.391 ^0.277 ~ ~
execute if score .this aj.fram matches 332 run tp @s ^0.144 ^-0.399 ^0.277 ~ ~
execute if score .this aj.fram matches 333 run tp @s ^0.144 ^-0.407 ^0.277 ~ ~
execute if score .this aj.fram matches 334 run tp @s ^0.144 ^-0.375 ^0.277 ~ ~
execute if score .this aj.fram matches 335 run tp @s ^0.144 ^-0.375 ^0.277 ~ ~