#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.313 ^-0.344 ^0.406 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.313 ^-0.368 ^0.443 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.313 ^-0.396 ^0.484 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.313 ^-0.426 ^0.528 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.313 ^-0.458 ^0.572 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.313 ^-0.489 ^0.613 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.313 ^-0.519 ^0.65 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.313 ^-0.547 ^0.677 ~ ~