#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 192 run tp @s ^0.279 ^-0.579 ^0.569 ~ ~
execute if score .this aj.fram matches 193 run tp @s ^0.279 ^-0.579 ^0.569 ~ ~
execute if score .this aj.fram matches 194 run tp @s ^0.279 ^-0.579 ^0.569 ~ ~
execute if score .this aj.fram matches 195 run tp @s ^0.279 ^-0.579 ^0.569 ~ ~
execute if score .this aj.fram matches 196 run tp @s ^0.279 ^-0.579 ^0.569 ~ ~
execute if score .this aj.fram matches 197 run tp @s ^0.279 ^-0.579 ^0.569 ~ ~
execute if score .this aj.fram matches 198 run tp @s ^0.279 ^-0.579 ^0.569 ~ ~
execute if score .this aj.fram matches 199 run tp @s ^0.279 ^-0.579 ^0.569 ~ ~