#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run tp @s ^0.125 ^-1.383 ^0.74 ~ ~
execute if score .this aj.fram matches 89 run tp @s ^0.125 ^-1.376 ^0.731 ~ ~
execute if score .this aj.fram matches 90 run tp @s ^0.125 ^-1.369 ^0.722 ~ ~
execute if score .this aj.fram matches 91 run tp @s ^0.125 ^-1.362 ^0.713 ~ ~
execute if score .this aj.fram matches 92 run tp @s ^0.125 ^-1.355 ^0.704 ~ ~
execute if score .this aj.fram matches 93 run tp @s ^0.125 ^-1.349 ^0.695 ~ ~
execute if score .this aj.fram matches 94 run tp @s ^0.125 ^-1.342 ^0.686 ~ ~
execute if score .this aj.fram matches 95 run tp @s ^0.125 ^-1.335 ^0.677 ~ ~