#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 440 run tp @s ^0.279 ^-0.451 ^0.625 ~ ~
execute if score .this aj.fram matches 441 run tp @s ^0.298 ^-0.461 ^0.619 ~ ~
execute if score .this aj.fram matches 442 run tp @s ^0.32 ^-0.472 ^0.608 ~ ~
execute if score .this aj.fram matches 443 run tp @s ^0.345 ^-0.485 ^0.591 ~ ~
execute if score .this aj.fram matches 444 run tp @s ^0.37 ^-0.5 ^0.569 ~ ~
execute if score .this aj.fram matches 445 run tp @s ^0.396 ^-0.515 ^0.541 ~ ~
execute if score .this aj.fram matches 446 run tp @s ^0.42 ^-0.531 ^0.507 ~ ~
execute if score .this aj.fram matches 447 run tp @s ^0.441 ^-0.547 ^0.469 ~ ~