#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 352 run data modify entity @s Pose.Head set value [-31.6779f,24.9609f,-19.7056f]
execute if score .this aj.fram matches 353 run data modify entity @s Pose.Head set value [-49.9178f,31.9238f,-36.1857f]
execute if score .this aj.fram matches 354 run data modify entity @s Pose.Head set value [-68.8216f,34.7557f,-55.8006f]
execute if score .this aj.fram matches 355 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 356 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 357 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 358 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 359 run data modify entity @s Pose.Head set value [0f,2.5f,0f]