#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 400 run tp @s ^0.144 ^-0.375 ^-0.918 ~ ~
execute if score .this aj.fram matches 401 run tp @s ^0.144 ^-0.375 ^-0.946 ~ ~
execute if score .this aj.fram matches 402 run tp @s ^0.144 ^-0.375 ^-0.973 ~ ~
execute if score .this aj.fram matches 403 run tp @s ^0.144 ^-0.375 ^-1 ~ ~
execute if score .this aj.fram matches 404 run tp @s ^0.144 ^-0.375 ^-1.027 ~ ~
execute if score .this aj.fram matches 405 run tp @s ^0.144 ^-0.375 ^-1.054 ~ ~
execute if score .this aj.fram matches 406 run tp @s ^0.144 ^-0.375 ^-1.081 ~ ~
execute if score .this aj.fram matches 407 run tp @s ^0.144 ^-0.375 ^-1.109 ~ ~