#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-47.4473f,32.0104f,10.2913f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-54.4199f,36.0234f,11.0812f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-60.8384f,39.6834f,11.3451f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-66.3688f,42.7727f,11.2075f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-74.5467f,47.278f,10.4391f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-76.4689f,48.2967f,10.1495f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-76.7227f,48.4294f,10.1079f]