#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 376 run tp @s ^0.058 ^-1.125 ^-0.433 ~ ~
execute if score .this aj.fram matches 377 run tp @s ^0.058 ^-1.125 ^-0.46 ~ ~
execute if score .this aj.fram matches 378 run tp @s ^0.058 ^-1.125 ^-0.487 ~ ~
execute if score .this aj.fram matches 379 run tp @s ^0.058 ^-1.125 ^-0.514 ~ ~
execute if score .this aj.fram matches 380 run tp @s ^0.058 ^-1.125 ^-0.541 ~ ~
execute if score .this aj.fram matches 381 run tp @s ^0.058 ^-1.125 ^-0.568 ~ ~
execute if score .this aj.fram matches 382 run tp @s ^0.058 ^-1.125 ^-0.596 ~ ~
execute if score .this aj.fram matches 383 run tp @s ^0.058 ^-1.125 ^-0.623 ~ ~