#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 416 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 417 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 418 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 419 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 420 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 421 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 422 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 423 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]