#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 424 run data modify entity @s Pose.Head set value [-60.7541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 425 run data modify entity @s Pose.Head set value [-60.7541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 426 run data modify entity @s Pose.Head set value [-62.4388f,21.4938f,-61.2154f]
execute if score .this aj.fram matches 427 run data modify entity @s Pose.Head set value [-64.8408f,16.8927f,-61.9269f]
execute if score .this aj.fram matches 428 run data modify entity @s Pose.Head set value [-67.3907f,11.963f,-62.5235f]
execute if score .this aj.fram matches 429 run data modify entity @s Pose.Head set value [-69.5416f,7.8118f,-62.9009f]
execute if score .this aj.fram matches 430 run data modify entity @s Pose.Head set value [-71.2011f,4.6372f,-63.1146f]
execute if score .this aj.fram matches 431 run data modify entity @s Pose.Head set value [-72.6563f,1.8857f,-63.2473f]