#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 400 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 401 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 402 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 403 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 404 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 405 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 406 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 407 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]