#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 392 run tp @s ^0.279 ^-0.539 ^-0.385 ~ ~
execute if score .this aj.fram matches 393 run tp @s ^0.279 ^-0.539 ^-0.412 ~ ~
execute if score .this aj.fram matches 394 run tp @s ^0.279 ^-0.539 ^-0.44 ~ ~
execute if score .this aj.fram matches 395 run tp @s ^0.279 ^-0.539 ^-0.467 ~ ~
execute if score .this aj.fram matches 396 run tp @s ^0.279 ^-0.539 ^-0.494 ~ ~
execute if score .this aj.fram matches 397 run tp @s ^0.279 ^-0.539 ^-0.521 ~ ~
execute if score .this aj.fram matches 398 run tp @s ^0.279 ^-0.539 ^-0.548 ~ ~
execute if score .this aj.fram matches 399 run tp @s ^0.279 ^-0.539 ^-0.575 ~ ~