#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 128 run data modify entity @s Pose.Head set value [-124.8192f,-6.1603f,14.3443f]
execute if score .this aj.fram matches 129 run data modify entity @s Pose.Head set value [-131.9579f,-6.5993f,19.5259f]
execute if score .this aj.fram matches 130 run data modify entity @s Pose.Head set value [-137.2087f,-7.0334f,24.5947f]
execute if score .this aj.fram matches 131 run data modify entity @s Pose.Head set value [-139.475f,-7.3576f,28.8971f]
execute if score .this aj.fram matches 132 run data modify entity @s Pose.Head set value [-137.66f,-7.4667f,31.7791f]
execute if score .this aj.fram matches 133 run data modify entity @s Pose.Head set value [-130.667f,-7.2555f,32.5871f]
execute if score .this aj.fram matches 134 run data modify entity @s Pose.Head set value [-126.2609f,-7.0725f,32.2207f]
execute if score .this aj.fram matches 135 run data modify entity @s Pose.Head set value [-120.481f,-6.8275f,31.4777f]