#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 272 run tp @s ^0.009 ^-1.348 ^0.414 ~ ~
execute if score .this aj.fram matches 273 run tp @s ^-0.001 ^-1.355 ^0.41 ~ ~
execute if score .this aj.fram matches 274 run tp @s ^-0.005 ^-1.363 ^0.405 ~ ~
execute if score .this aj.fram matches 275 run tp @s ^-0.004 ^-1.373 ^0.401 ~ ~
execute if score .this aj.fram matches 276 run tp @s ^0.003 ^-1.382 ^0.398 ~ ~
execute if score .this aj.fram matches 277 run tp @s ^0.016 ^-1.39 ^0.396 ~ ~
execute if score .this aj.fram matches 278 run tp @s ^0.035 ^-1.396 ^0.396 ~ ~
execute if score .this aj.fram matches 279 run tp @s ^0.058 ^-1.398 ^0.398 ~ ~