#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 264 run data modify entity @s Pose.Head set value [-68.8216f,34.7557f,-55.8006f]
execute if score .this aj.fram matches 265 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 266 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 267 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 268 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 269 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 270 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 271 run data modify entity @s Pose.Head set value [-6.6464f,8.1253f,-2.8416f]