#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 136 run data modify entity @s Pose.Head set value [-113.4902f,-6.5277f,30.3981f]
execute if score .this aj.fram matches 137 run data modify entity @s Pose.Head set value [-105.4517f,-6.1799f,29.0219f]
execute if score .this aj.fram matches 138 run data modify entity @s Pose.Head set value [-96.5284f,-5.7913f,27.389f]
execute if score .this aj.fram matches 139 run data modify entity @s Pose.Head set value [-86.8834f,-5.3689f,25.5396f]
execute if score .this aj.fram matches 140 run data modify entity @s Pose.Head set value [-76.6797f,-4.9197f,23.5137f]
execute if score .this aj.fram matches 141 run data modify entity @s Pose.Head set value [-66.0804f,-4.4508f,21.3512f]
execute if score .this aj.fram matches 142 run data modify entity @s Pose.Head set value [-55.2484f,-3.9691f,19.0923f]
execute if score .this aj.fram matches 143 run data modify entity @s Pose.Head set value [-44.3468f,-3.4818f,16.7768f]