#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 288 run data modify entity @s Pose.Head set value [-63.8671f,46.5249f,-52.1201f]
execute if score .this aj.fram matches 289 run data modify entity @s Pose.Head set value [-64.5643f,53.5883f,-47.3872f]
execute if score .this aj.fram matches 290 run data modify entity @s Pose.Head set value [-63.7671f,60.3946f,-40.8235f]
execute if score .this aj.fram matches 291 run data modify entity @s Pose.Head set value [-60.173f,66.7407f,-31.131f]
execute if score .this aj.fram matches 292 run data modify entity @s Pose.Head set value [-51.28f,72.188f,-15.8061f]
execute if score .this aj.fram matches 293 run data modify entity @s Pose.Head set value [-33.6687f,75.7807f,8.577f]
execute if score .this aj.fram matches 294 run data modify entity @s Pose.Head set value [-9.6656f,76.1586f,39.7031f]
execute if score .this aj.fram matches 295 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]