#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 120 run tp @s ^0.423 ^-0.788 ^0.717 ~ ~
execute if score .this aj.fram matches 121 run tp @s ^0.421 ^-0.751 ^0.77 ~ ~
execute if score .this aj.fram matches 122 run tp @s ^0.419 ^-0.688 ^0.829 ~ ~
execute if score .this aj.fram matches 123 run tp @s ^0.416 ^-0.603 ^0.875 ~ ~
execute if score .this aj.fram matches 124 run tp @s ^0.414 ^-0.509 ^0.897 ~ ~
execute if score .this aj.fram matches 125 run tp @s ^0.416 ^-0.424 ^0.895 ~ ~
execute if score .this aj.fram matches 126 run tp @s ^0.423 ^-0.362 ^0.879 ~ ~
execute if score .this aj.fram matches 127 run tp @s ^0.436 ^-0.324 ^0.859 ~ ~