#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [-70.5236f,44.2909f,10.7446f]
execute if score .this aj.fram matches 82 run data modify entity @s Pose.Head set value [-70.3241f,43.2784f,10.6123f]
execute if score .this aj.fram matches 83 run data modify entity @s Pose.Head set value [-70.0042f,42.0879f,10.4961f]
execute if score .this aj.fram matches 84 run data modify entity @s Pose.Head set value [-69.5877f,40.7421f,10.3942f]
execute if score .this aj.fram matches 85 run data modify entity @s Pose.Head set value [-69.0984f,39.2639f,10.3046f]
execute if score .this aj.fram matches 86 run data modify entity @s Pose.Head set value [-68.5602f,37.6762f,10.2248f]
execute if score .this aj.fram matches 87 run data modify entity @s Pose.Head set value [-67.9967f,36.0019f,10.1521f]