#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 432 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 433 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 434 run data modify entity @s Pose.Head set value [0f,2.5219f,0f]
execute if score .this aj.fram matches 435 run data modify entity @s Pose.Head set value [0f,2.5729f,0f]
execute if score .this aj.fram matches 436 run data modify entity @s Pose.Head set value [0f,2.6312f,0f]
execute if score .this aj.fram matches 437 run data modify entity @s Pose.Head set value [0f,2.6749f,0f]
execute if score .this aj.fram matches 438 run data modify entity @s Pose.Head set value [0f,2.6822f,0f]
execute if score .this aj.fram matches 439 run data modify entity @s Pose.Head set value [0f,2.6312f,0f]