#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.125 ^-1.094 ^0.406 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.125 ^-1.118 ^0.443 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.125 ^-1.146 ^0.484 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.125 ^-1.176 ^0.528 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.125 ^-1.208 ^0.572 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.125 ^-1.239 ^0.613 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.125 ^-1.269 ^0.65 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.125 ^-1.297 ^0.677 ~ ~