#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 72 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]
execute if score .this aj.fram matches 73 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]
execute if score .this aj.fram matches 74 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]
execute if score .this aj.fram matches 75 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]
execute if score .this aj.fram matches 76 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]
execute if score .this aj.fram matches 77 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]
execute if score .this aj.fram matches 78 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]
execute if score .this aj.fram matches 79 run data modify entity @s Pose.Head set value [-70.5792f,45.1025f,10.8944f]