#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 112 run data modify entity @s Pose.Head set value [-19.6637f,-8.1148f,-5.5981f]
execute if score .this aj.fram matches 113 run data modify entity @s Pose.Head set value [-20.458f,-7.9964f,-5.5222f]
execute if score .this aj.fram matches 114 run data modify entity @s Pose.Head set value [-21.4045f,-7.8681f,-5.4255f]
execute if score .this aj.fram matches 115 run data modify entity @s Pose.Head set value [-22.5193f,-7.7374f,-5.305f]
execute if score .this aj.fram matches 116 run data modify entity @s Pose.Head set value [-23.8187f,-7.612f,-5.1575f]
execute if score .this aj.fram matches 117 run data modify entity @s Pose.Head set value [-25.3186f,-7.4995f,-4.98f]
execute if score .this aj.fram matches 118 run data modify entity @s Pose.Head set value [-27.0351f,-7.4077f,-4.7695f]
execute if score .this aj.fram matches 119 run data modify entity @s Pose.Head set value [-28.9845f,-7.3442f,-4.523f]