#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 176 run tp @s ^0.099 ^-1.075 ^0.061 ~ ~
execute if score .this aj.fram matches 177 run tp @s ^0.09 ^-1.091 ^0.077 ~ ~
execute if score .this aj.fram matches 178 run tp @s ^0.08 ^-1.105 ^0.091 ~ ~
execute if score .this aj.fram matches 179 run tp @s ^0.069 ^-1.117 ^0.103 ~ ~
execute if score .this aj.fram matches 180 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~
execute if score .this aj.fram matches 181 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~
execute if score .this aj.fram matches 182 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~
execute if score .this aj.fram matches 183 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~