#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [-5.125f,0f,0f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [-10.25f,0f,0f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [-15.375f,0f,0f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [-20.5f,0f,0f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [-25.625f,0f,0f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [-30.75f,0f,0f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [-35.875f,0f,0f]