#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 352 run tp @s ^0.144 ^-0.391 ^0.277 ~ ~
execute if score .this aj.fram matches 353 run tp @s ^0.144 ^-0.399 ^0.277 ~ ~
execute if score .this aj.fram matches 354 run tp @s ^0.144 ^-0.407 ^0.277 ~ ~
execute if score .this aj.fram matches 355 run tp @s ^0.144 ^-0.375 ^0.277 ~ ~
execute if score .this aj.fram matches 356 run tp @s ^0.144 ^-0.375 ^0.277 ~ ~
execute if score .this aj.fram matches 357 run tp @s ^0.144 ^-0.375 ^0.25 ~ ~
execute if score .this aj.fram matches 358 run tp @s ^0.144 ^-0.375 ^0.223 ~ ~
execute if score .this aj.fram matches 359 run tp @s ^0.144 ^-0.375 ^0.196 ~ ~