#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 280 run tp @s ^0.279 ^-0.539 ^0.593 ~ ~
execute if score .this aj.fram matches 281 run tp @s ^0.279 ^-0.539 ^0.593 ~ ~
execute if score .this aj.fram matches 282 run tp @s ^0.279 ^-0.539 ^0.593 ~ ~
execute if score .this aj.fram matches 283 run tp @s ^0.279 ^-0.539 ^0.593 ~ ~
execute if score .this aj.fram matches 284 run tp @s ^0.279 ^-0.539 ^0.593 ~ ~
execute if score .this aj.fram matches 285 run tp @s ^0.279 ^-0.539 ^0.593 ~ ~
execute if score .this aj.fram matches 286 run tp @s ^0.239 ^-0.578 ^0.587 ~ ~
execute if score .this aj.fram matches 287 run tp @s ^0.197 ^-0.614 ^0.574 ~ ~