#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 448..455 run function emis:animations/hood/tree/left_leg2_root_448-455
execute if score .this aj.fram matches 456 run tp @s ^0.123 ^-1.391 ^0.08 ~ ~
execute if score .this aj.fram matches 457 run tp @s ^0.124 ^-1.387 ^0.055 ~ ~
execute if score .this aj.fram matches 458 run tp @s ^0.125 ^-1.383 ^0.033 ~ ~
execute if score .this aj.fram matches 459 run tp @s ^0.125 ^-1.379 ^0.015 ~ ~
execute if score .this aj.fram matches 460 run tp @s ^0.125 ^-1.375 ^0 ~ ~