#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 160 run tp @s ^0.125 ^-1.011 ^0.116 ~ ~
execute if score .this aj.fram matches 161 run tp @s ^0.125 ^-1.008 ^0.101 ~ ~
execute if score .this aj.fram matches 162 run tp @s ^0.125 ^-1.006 ^0.087 ~ ~
execute if score .this aj.fram matches 163 run tp @s ^0.125 ^-1.004 ^0.073 ~ ~
execute if score .this aj.fram matches 164 run tp @s ^0.125 ^-1.002 ^0.06 ~ ~
execute if score .this aj.fram matches 165 run tp @s ^0.125 ^-1 ^0.048 ~ ~
execute if score .this aj.fram matches 166 run tp @s ^0.125 ^-1 ^0.036 ~ ~
execute if score .this aj.fram matches 167 run tp @s ^0.125 ^-0.999 ^0.025 ~ ~