#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 424 run tp @s ^0.044 ^-1.341 ^-1.43 ~ ~
execute if score .this aj.fram matches 425 run tp @s ^0.044 ^-1.341 ^-1.457 ~ ~
execute if score .this aj.fram matches 426 run tp @s ^0.044 ^-1.341 ^-1.421 ~ ~
execute if score .this aj.fram matches 427 run tp @s ^0.044 ^-1.341 ^-1.164 ~ ~
execute if score .this aj.fram matches 428 run tp @s ^0.044 ^-1.341 ^-0.827 ~ ~
execute if score .this aj.fram matches 429 run tp @s ^0.044 ^-1.341 ^-0.55 ~ ~
execute if score .this aj.fram matches 430 run tp @s ^0.044 ^-1.341 ^-0.354 ~ ~
execute if score .this aj.fram matches 431 run tp @s ^0.044 ^-1.341 ^-0.169 ~ ~