#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 264 run data modify entity @s Pose.Head set value [-9.6656f,76.1586f,39.7031f]
execute if score .this aj.fram matches 265 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 266 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 267 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 268 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 269 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 270 run data modify entity @s Pose.Head set value [-58.2541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 271 run data modify entity @s Pose.Head set value [-60.4067f,32.0102f,-58.4594f]