#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 384 run tp @s ^0.279 ^-0.539 ^-0.168 ~ ~
execute if score .this aj.fram matches 385 run tp @s ^0.279 ^-0.539 ^-0.195 ~ ~
execute if score .this aj.fram matches 386 run tp @s ^0.279 ^-0.539 ^-0.222 ~ ~
execute if score .this aj.fram matches 387 run tp @s ^0.279 ^-0.539 ^-0.249 ~ ~
execute if score .this aj.fram matches 388 run tp @s ^0.279 ^-0.539 ^-0.276 ~ ~
execute if score .this aj.fram matches 389 run tp @s ^0.279 ^-0.539 ^-0.304 ~ ~
execute if score .this aj.fram matches 390 run tp @s ^0.279 ^-0.539 ^-0.331 ~ ~
execute if score .this aj.fram matches 391 run tp @s ^0.279 ^-0.539 ^-0.358 ~ ~