#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 232 run tp @s ^0.058 ^-1.132 ^0.111 ~ ~
execute if score .this aj.fram matches 233 run tp @s ^0.058 ^-1.136 ^0.111 ~ ~
execute if score .this aj.fram matches 234 run tp @s ^0.058 ^-1.139 ^0.111 ~ ~
execute if score .this aj.fram matches 235 run tp @s ^0.058 ^-1.143 ^0.111 ~ ~
execute if score .this aj.fram matches 236 run tp @s ^0.058 ^-1.146 ^0.111 ~ ~
execute if score .this aj.fram matches 237 run tp @s ^0.058 ^-1.15 ^0.111 ~ ~
execute if score .this aj.fram matches 238 run tp @s ^0.058 ^-1.153 ^0.111 ~ ~
execute if score .this aj.fram matches 239 run tp @s ^0.058 ^-1.157 ^0.111 ~ ~