#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 96 run tp @s ^0.418 ^-0.929 ^0.769 ~ ~
execute if score .this aj.fram matches 97 run tp @s ^0.419 ^-0.922 ^0.758 ~ ~
execute if score .this aj.fram matches 98 run tp @s ^0.421 ^-0.915 ^0.747 ~ ~
execute if score .this aj.fram matches 99 run tp @s ^0.422 ^-0.908 ^0.738 ~ ~
execute if score .this aj.fram matches 100 run tp @s ^0.423 ^-0.901 ^0.729 ~ ~
execute if score .this aj.fram matches 101 run tp @s ^0.423 ^-0.894 ^0.721 ~ ~
execute if score .this aj.fram matches 102 run tp @s ^0.424 ^-0.887 ^0.712 ~ ~
execute if score .this aj.fram matches 103 run tp @s ^0.425 ^-0.879 ^0.704 ~ ~