#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 192 run data modify entity @s Pose.Head set value [-53.9646f,31.1419f,-58.6181f]
execute if score .this aj.fram matches 193 run data modify entity @s Pose.Head set value [-53.9646f,31.1419f,-58.6181f]
execute if score .this aj.fram matches 194 run data modify entity @s Pose.Head set value [-53.9646f,31.1419f,-58.6181f]
execute if score .this aj.fram matches 195 run data modify entity @s Pose.Head set value [-53.9646f,31.1419f,-58.6181f]
execute if score .this aj.fram matches 196 run data modify entity @s Pose.Head set value [-53.9646f,31.1419f,-58.6181f]
execute if score .this aj.fram matches 197 run data modify entity @s Pose.Head set value [-53.9646f,31.1419f,-58.6181f]
execute if score .this aj.fram matches 198 run data modify entity @s Pose.Head set value [-53.9646f,31.1419f,-58.6181f]
execute if score .this aj.fram matches 199 run data modify entity @s Pose.Head set value [-53.9646f,31.1419f,-58.6181f]