#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 264 run tp @s ^0.058 ^-1.157 ^0.111 ~ ~
execute if score .this aj.fram matches 265 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~
execute if score .this aj.fram matches 266 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~
execute if score .this aj.fram matches 267 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~
execute if score .this aj.fram matches 268 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~
execute if score .this aj.fram matches 269 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~
execute if score .this aj.fram matches 270 run tp @s ^0.058 ^-1.125 ^0.111 ~ ~
execute if score .this aj.fram matches 271 run tp @s ^0.058 ^-1.129 ^0.111 ~ ~