#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [3.2392f,0.6472f,-1.0758f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [8.2158f,1.4948f,-2.6384f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [14.2067f,2.5027f,-4.5119f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [20.489f,3.6305f,-6.52f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [26.3397f,4.8381f,-8.4869f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [31.0359f,6.0852f,-10.2365f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [33.8544f,7.3317f,-11.5927f]