#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run tp @s ^0.107 ^-1.373 ^0.416 ~ ~
execute if score .this aj.fram matches 153 run tp @s ^0.106 ^-1.375 ^0.388 ~ ~
execute if score .this aj.fram matches 154 run tp @s ^0.106 ^-1.376 ^0.36 ~ ~
execute if score .this aj.fram matches 155 run tp @s ^0.105 ^-1.377 ^0.333 ~ ~
execute if score .this aj.fram matches 156 run tp @s ^0.105 ^-1.378 ^0.305 ~ ~
execute if score .this aj.fram matches 157 run tp @s ^0.105 ^-1.378 ^0.277 ~ ~
execute if score .this aj.fram matches 158 run tp @s ^0.105 ^-1.378 ^0.249 ~ ~
execute if score .this aj.fram matches 159 run tp @s ^0.105 ^-1.378 ^0.222 ~ ~