#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 344 run data modify entity @s Pose.Head set value [-31.6779f,24.9609f,-19.7056f]
execute if score .this aj.fram matches 345 run data modify entity @s Pose.Head set value [-68.8216f,34.7557f,-55.8006f]
execute if score .this aj.fram matches 346 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 347 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 348 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 349 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 350 run data modify entity @s Pose.Head set value [0f,2.5f,0f]
execute if score .this aj.fram matches 351 run data modify entity @s Pose.Head set value [-15.1777f,14.7556f,-7.6117f]