#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 272 run tp @s ^0.144 ^-0.382 ^0.277 ~ ~
execute if score .this aj.fram matches 273 run tp @s ^0.144 ^-0.386 ^0.277 ~ ~
execute if score .this aj.fram matches 274 run tp @s ^0.144 ^-0.389 ^0.277 ~ ~
execute if score .this aj.fram matches 275 run tp @s ^0.144 ^-0.393 ^0.277 ~ ~
execute if score .this aj.fram matches 276 run tp @s ^0.144 ^-0.396 ^0.277 ~ ~
execute if score .this aj.fram matches 277 run tp @s ^0.144 ^-0.4 ^0.277 ~ ~
execute if score .this aj.fram matches 278 run tp @s ^0.144 ^-0.403 ^0.277 ~ ~
execute if score .this aj.fram matches 279 run tp @s ^0.144 ^-0.407 ^0.277 ~ ~