#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 160 run data modify entity @s Pose.Head set value [-12.2354f,0.5369f,2.903f]
execute if score .this aj.fram matches 161 run data modify entity @s Pose.Head set value [-10.5383f,0.5159f,2.7897f]
execute if score .this aj.fram matches 162 run data modify entity @s Pose.Head set value [-8.9272f,0.4887f,2.6423f]
execute if score .this aj.fram matches 163 run data modify entity @s Pose.Head set value [-7.4092f,0.4547f,2.4588f]
execute if score .this aj.fram matches 164 run data modify entity @s Pose.Head set value [-5.9916f,0.4137f,2.2372f]
execute if score .this aj.fram matches 165 run data modify entity @s Pose.Head set value [-4.6816f,0.3654f,1.9756f]
execute if score .this aj.fram matches 166 run data modify entity @s Pose.Head set value [-3.4865f,0.3092f,1.6721f]
execute if score .this aj.fram matches 167 run data modify entity @s Pose.Head set value [-2.4136f,0.245f,1.3247f]