#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 384 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 385 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 386 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 387 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 388 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 389 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 390 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 391 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]