#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 360 run tp @s ^0.279 ^-0.539 ^0.484 ~ ~
execute if score .this aj.fram matches 361 run tp @s ^0.279 ^-0.539 ^0.457 ~ ~
execute if score .this aj.fram matches 362 run tp @s ^0.279 ^-0.539 ^0.43 ~ ~
execute if score .this aj.fram matches 363 run tp @s ^0.279 ^-0.539 ^0.403 ~ ~
execute if score .this aj.fram matches 364 run tp @s ^0.279 ^-0.539 ^0.376 ~ ~
execute if score .this aj.fram matches 365 run tp @s ^0.279 ^-0.539 ^0.349 ~ ~
execute if score .this aj.fram matches 366 run tp @s ^0.279 ^-0.539 ^0.321 ~ ~
execute if score .this aj.fram matches 367 run tp @s ^0.279 ^-0.539 ^0.294 ~ ~