#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^0.125 ^-1.378 ^1.076 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^0.125 ^-1.372 ^1.106 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^0.125 ^-1.367 ^1.133 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^0.125 ^-1.362 ^1.157 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^0.125 ^-1.357 ^1.179 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^0.125 ^-1.334 ^1.178 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^0.125 ^-1.323 ^1.177 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^0.125 ^-1.322 ^1.177 ~ ~