#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run data modify entity @s Pose.Head set value [-93.3877f,0f,0f]
execute if score .this aj.fram matches 89 run data modify entity @s Pose.Head set value [-92.2487f,0f,0f]
execute if score .this aj.fram matches 90 run data modify entity @s Pose.Head set value [-91.1097f,0f,0f]
execute if score .this aj.fram matches 91 run data modify entity @s Pose.Head set value [-89.9706f,0f,0f]
execute if score .this aj.fram matches 92 run data modify entity @s Pose.Head set value [-88.8316f,0f,0f]
execute if score .this aj.fram matches 93 run data modify entity @s Pose.Head set value [-87.6926f,0f,0f]
execute if score .this aj.fram matches 94 run data modify entity @s Pose.Head set value [-86.5535f,0f,0f]
execute if score .this aj.fram matches 95 run data modify entity @s Pose.Head set value [-85.4145f,0f,0f]