#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 264 run data modify entity @s Pose.Head set value [69.9803f,65.0783f,142.8983f]
execute if score .this aj.fram matches 265 run data modify entity @s Pose.Head set value [-60.7541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 266 run data modify entity @s Pose.Head set value [-60.7541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 267 run data modify entity @s Pose.Head set value [-60.7541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 268 run data modify entity @s Pose.Head set value [-60.7541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 269 run data modify entity @s Pose.Head set value [-60.7541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 270 run data modify entity @s Pose.Head set value [-60.7541f,24.6681f,-60.6295f]
execute if score .this aj.fram matches 271 run data modify entity @s Pose.Head set value [-64.4258f,35.4704f,-58.1991f]