#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 312 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 313 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 314 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 315 run data modify entity @s Pose.Head set value [-55f,2.5f,0f]
execute if score .this aj.fram matches 316 run data modify entity @s Pose.Head set value [-56.4277f,14.7556f,-7.6117f]
execute if score .this aj.fram matches 317 run data modify entity @s Pose.Head set value [-59.1779f,24.9609f,-19.7056f]
execute if score .this aj.fram matches 318 run data modify entity @s Pose.Head set value [-63.6678f,31.9238f,-36.1857f]
execute if score .this aj.fram matches 319 run data modify entity @s Pose.Head set value [-68.8216f,34.7557f,-55.8006f]