#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 200 run data modify entity @s Pose.Head set value [-136.4646f,31.1419f,-58.6181f]
execute if score .this aj.fram matches 201 run data modify entity @s Pose.Head set value [-133.1852f,37.5888f,-56.7341f]
execute if score .this aj.fram matches 202 run data modify entity @s Pose.Head set value [-129.8376f,44.0301f,-54.7063f]
execute if score .this aj.fram matches 203 run data modify entity @s Pose.Head set value [-126.3901f,50.4505f,-52.4819f]
execute if score .this aj.fram matches 204 run data modify entity @s Pose.Head set value [-122.7789f,56.8329f,-49.9767f]
execute if score .this aj.fram matches 205 run data modify entity @s Pose.Head set value [-118.8732f,63.1578f,-47.0388f]
execute if score .this aj.fram matches 206 run data modify entity @s Pose.Head set value [-114.3768f,69.4003f,-43.3513f]
execute if score .this aj.fram matches 207 run data modify entity @s Pose.Head set value [-108.4946f,75.522f,-38.0974f]