#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run data modify entity @s Pose.Head set value [-45.1666f,0.304f,1.6437f]
execute if score .this aj.fram matches 145 run data modify entity @s Pose.Head set value [-43.0794f,0.3355f,1.8143f]
execute if score .this aj.fram matches 146 run data modify entity @s Pose.Head set value [-40.9623f,0.3665f,1.9817f]
execute if score .this aj.fram matches 147 run data modify entity @s Pose.Head set value [-38.8225f,0.3965f,2.144f]
execute if score .this aj.fram matches 148 run data modify entity @s Pose.Head set value [-36.6673f,0.4252f,2.2991f]
execute if score .this aj.fram matches 149 run data modify entity @s Pose.Head set value [-34.5038f,0.4522f,2.4453f]
execute if score .this aj.fram matches 150 run data modify entity @s Pose.Head set value [-32.3394f,0.4772f,2.5804f]
execute if score .this aj.fram matches 151 run data modify entity @s Pose.Head set value [-30.1813f,0.4998f,2.7026f]