#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 208 run data modify entity @s Pose.Head set value [-16.9222f,-77.667f,-108.5899f]
execute if score .this aj.fram matches 209 run data modify entity @s Pose.Head set value [11.6197f,-67.9656f,-152.1352f]
execute if score .this aj.fram matches 210 run data modify entity @s Pose.Head set value [11.2641f,-54.1308f,-165.1337f]
execute if score .this aj.fram matches 211 run data modify entity @s Pose.Head set value [4.1592f,-39.8067f,-169.5415f]
execute if score .this aj.fram matches 212 run data modify entity @s Pose.Head set value [-4.4353f,-25.7855f,-170.2817f]
execute if score .this aj.fram matches 213 run data modify entity @s Pose.Head set value [-12.7916f,-12.5027f,-168.5744f]
execute if score .this aj.fram matches 214 run data modify entity @s Pose.Head set value [-19.9919f,-0.4045f,-164.6547f]
execute if score .this aj.fram matches 215 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]