#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 232 run data modify entity @s Pose.Head set value [1.0382f,-51.8397f,4.87f]
execute if score .this aj.fram matches 233 run data modify entity @s Pose.Head set value [-0.8641f,-67.6182f,-27.7278f]
execute if score .this aj.fram matches 234 run data modify entity @s Pose.Head set value [27.8052f,-71.2919f,-90.5616f]
execute if score .this aj.fram matches 235 run data modify entity @s Pose.Head set value [38.3942f,-59.9957f,-133.9706f]
execute if score .this aj.fram matches 236 run data modify entity @s Pose.Head set value [27.7383f,-44.37f,-153.555f]
execute if score .this aj.fram matches 237 run data modify entity @s Pose.Head set value [11.5297f,-28.2328f,-163.5025f]
execute if score .this aj.fram matches 238 run data modify entity @s Pose.Head set value [-5.119f,-13.0312f,-167.1029f]
execute if score .this aj.fram matches 239 run data modify entity @s Pose.Head set value [-19.9919f,-0.4045f,-164.6547f]