#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 368 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 369 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 370 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 371 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 372 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 373 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 374 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 375 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]