#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 376 run tp @s ^-0.303 ^-0.709 ^-0.24 ~ ~
execute if score .this aj.fram matches 377 run tp @s ^-0.303 ^-0.709 ^-0.267 ~ ~
execute if score .this aj.fram matches 378 run tp @s ^-0.303 ^-0.709 ^-0.294 ~ ~
execute if score .this aj.fram matches 379 run tp @s ^-0.303 ^-0.709 ^-0.321 ~ ~
execute if score .this aj.fram matches 380 run tp @s ^-0.303 ^-0.709 ^-0.348 ~ ~
execute if score .this aj.fram matches 381 run tp @s ^-0.303 ^-0.709 ^-0.375 ~ ~
execute if score .this aj.fram matches 382 run tp @s ^-0.303 ^-0.709 ^-0.403 ~ ~
execute if score .this aj.fram matches 383 run tp @s ^-0.303 ^-0.709 ^-0.43 ~ ~