#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 264 run data modify entity @s Pose.Head set value [-19.9919f,-0.4045f,-164.6547f]
execute if score .this aj.fram matches 265 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 266 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 267 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 268 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 269 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 270 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 271 run data modify entity @s Pose.Head set value [18.4203f,-32.0317f,21.5144f]