#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 352 run tp @s ^-0.219 ^-0.523 ^0.368 ~ ~
execute if score .this aj.fram matches 353 run tp @s ^-0.238 ^-0.359 ^0.407 ~ ~
execute if score .this aj.fram matches 354 run tp @s ^-0.315 ^-0.172 ^0.4 ~ ~
execute if score .this aj.fram matches 355 run tp @s ^-0.303 ^-0.709 ^0.304 ~ ~
execute if score .this aj.fram matches 356 run tp @s ^-0.303 ^-0.709 ^0.304 ~ ~
execute if score .this aj.fram matches 357 run tp @s ^-0.303 ^-0.709 ^0.277 ~ ~
execute if score .this aj.fram matches 358 run tp @s ^-0.303 ^-0.709 ^0.25 ~ ~
execute if score .this aj.fram matches 359 run tp @s ^-0.303 ^-0.709 ^0.222 ~ ~