#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 128 run tp @s ^-0.467 ^0.022 ^1.002 ~ ~
execute if score .this aj.fram matches 129 run tp @s ^-0.536 ^0.04 ^0.955 ~ ~
execute if score .this aj.fram matches 130 run tp @s ^-0.604 ^0.037 ^0.916 ~ ~
execute if score .this aj.fram matches 131 run tp @s ^-0.662 ^0.029 ^0.876 ~ ~
execute if score .this aj.fram matches 132 run tp @s ^-0.7 ^0.016 ^0.854 ~ ~
execute if score .this aj.fram matches 133 run tp @s ^-0.712 ^0.005 ^0.854 ~ ~
execute if score .this aj.fram matches 134 run tp @s ^-0.708 ^0.008 ^0.851 ~ ~
execute if score .this aj.fram matches 135 run tp @s ^-0.699 ^0.012 ^0.851 ~ ~