#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 288 run tp @s ^-0.235 ^-0.608 ^0.338 ~ ~
execute if score .this aj.fram matches 289 run tp @s ^-0.222 ^-0.554 ^0.357 ~ ~
execute if score .this aj.fram matches 290 run tp @s ^-0.218 ^-0.49 ^0.378 ~ ~
execute if score .this aj.fram matches 291 run tp @s ^-0.225 ^-0.418 ^0.396 ~ ~
execute if score .this aj.fram matches 292 run tp @s ^-0.244 ^-0.339 ^0.409 ~ ~
execute if score .this aj.fram matches 293 run tp @s ^-0.274 ^-0.256 ^0.411 ~ ~
execute if score .this aj.fram matches 294 run tp @s ^-0.315 ^-0.172 ^0.4 ~ ~
execute if score .this aj.fram matches 295 run tp @s ^-0.303 ^-0.709 ^0.304 ~ ~