#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 176 run tp @s ^-0.418 ^-0.92 ^0.151 ~ ~
execute if score .this aj.fram matches 177 run tp @s ^-0.473 ^-0.87 ^0.185 ~ ~
execute if score .this aj.fram matches 178 run tp @s ^-0.531 ^-0.812 ^0.194 ~ ~
execute if score .this aj.fram matches 179 run tp @s ^-0.582 ^-0.756 ^0.177 ~ ~
execute if score .this aj.fram matches 180 run tp @s ^-0.619 ^-0.714 ^0.135 ~ ~
execute if score .this aj.fram matches 181 run tp @s ^-0.619 ^-0.714 ^0.135 ~ ~
execute if score .this aj.fram matches 182 run tp @s ^-0.619 ^-0.714 ^0.135 ~ ~
execute if score .this aj.fram matches 183 run tp @s ^-0.619 ^-0.714 ^0.135 ~ ~