#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 384 run tp @s ^-0.303 ^-0.709 ^-0.457 ~ ~
execute if score .this aj.fram matches 385 run tp @s ^-0.303 ^-0.709 ^-0.484 ~ ~
execute if score .this aj.fram matches 386 run tp @s ^-0.303 ^-0.709 ^-0.511 ~ ~
execute if score .this aj.fram matches 387 run tp @s ^-0.303 ^-0.709 ^-0.538 ~ ~
execute if score .this aj.fram matches 388 run tp @s ^-0.303 ^-0.709 ^-0.566 ~ ~
execute if score .this aj.fram matches 389 run tp @s ^-0.303 ^-0.709 ^-0.593 ~ ~
execute if score .this aj.fram matches 390 run tp @s ^-0.303 ^-0.709 ^-0.62 ~ ~
execute if score .this aj.fram matches 391 run tp @s ^-0.303 ^-0.709 ^-0.647 ~ ~