#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 160 run data modify entity @s Pose.Head set value [16.3124f,-17.9058f,52.1054f]
execute if score .this aj.fram matches 161 run data modify entity @s Pose.Head set value [21.8496f,-17.9522f,45.1529f]
execute if score .this aj.fram matches 162 run data modify entity @s Pose.Head set value [27.9237f,-17.1949f,37.9983f]
execute if score .this aj.fram matches 163 run data modify entity @s Pose.Head set value [34.266f,-15.635f,30.9721f]
execute if score .this aj.fram matches 164 run data modify entity @s Pose.Head set value [40.5932f,-13.379f,24.3721f]
execute if score .this aj.fram matches 165 run data modify entity @s Pose.Head set value [46.6559f,-10.6324f,18.4154f]
execute if score .this aj.fram matches 166 run data modify entity @s Pose.Head set value [52.2594f,-7.6723f,13.2211f]
execute if score .this aj.fram matches 167 run data modify entity @s Pose.Head set value [57.2575f,-4.8136f,8.8196f]