#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 240 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 241 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 242 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 243 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 244 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 245 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 246 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]
execute if score .this aj.fram matches 247 run data modify entity @s Pose.Head set value [40.9833f,-10.1048f,31.8222f]