#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 280 run tp @s ^-0.303 ^-0.709 ^0.304 ~ ~
execute if score .this aj.fram matches 281 run tp @s ^-0.303 ^-0.709 ^0.304 ~ ~
execute if score .this aj.fram matches 282 run tp @s ^-0.303 ^-0.709 ^0.304 ~ ~
execute if score .this aj.fram matches 283 run tp @s ^-0.303 ^-0.709 ^0.304 ~ ~
execute if score .this aj.fram matches 284 run tp @s ^-0.303 ^-0.709 ^0.304 ~ ~
execute if score .this aj.fram matches 285 run tp @s ^-0.303 ^-0.709 ^0.304 ~ ~
execute if score .this aj.fram matches 286 run tp @s ^-0.277 ^-0.685 ^0.31 ~ ~
execute if score .this aj.fram matches 287 run tp @s ^-0.254 ^-0.651 ^0.322 ~ ~