#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run tp @s ^-0.356 ^-1.23 ^1.223 ~ ~
execute if score .this aj.fram matches 89 run tp @s ^-0.352 ^-1.236 ^1.194 ~ ~
execute if score .this aj.fram matches 90 run tp @s ^-0.348 ^-1.241 ^1.164 ~ ~
execute if score .this aj.fram matches 91 run tp @s ^-0.344 ^-1.244 ^1.135 ~ ~
execute if score .this aj.fram matches 92 run tp @s ^-0.34 ^-1.246 ^1.106 ~ ~
execute if score .this aj.fram matches 93 run tp @s ^-0.336 ^-1.247 ^1.079 ~ ~
execute if score .this aj.fram matches 94 run tp @s ^-0.332 ^-1.246 ^1.052 ~ ~
execute if score .this aj.fram matches 95 run tp @s ^-0.328 ^-1.243 ^1.028 ~ ~