#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 360 run tp @s ^-0.058 ^-1.125 ^-0.22 ~ ~
execute if score .this aj.fram matches 361 run tp @s ^-0.058 ^-1.125 ^-0.247 ~ ~
execute if score .this aj.fram matches 362 run tp @s ^-0.058 ^-1.125 ^-0.274 ~ ~
execute if score .this aj.fram matches 363 run tp @s ^-0.058 ^-1.125 ^-0.301 ~ ~
execute if score .this aj.fram matches 364 run tp @s ^-0.058 ^-1.125 ^-0.328 ~ ~
execute if score .this aj.fram matches 365 run tp @s ^-0.058 ^-1.125 ^-0.355 ~ ~
execute if score .this aj.fram matches 366 run tp @s ^-0.058 ^-1.125 ^-0.383 ~ ~
execute if score .this aj.fram matches 367 run tp @s ^-0.058 ^-1.125 ^-0.41 ~ ~