#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [74f,0f,0f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [78.625f,0f,0f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [83.25f,0f,0f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [87.875f,0f,0f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [92.5f,0f,0f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [96.9263f,0f,0f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [99.0039f,0f,0f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [99.2749f,0f,0f]