#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 320 run tp @s ^-0.058 ^-1.125 ^-0.111 ~ ~
execute if score .this aj.fram matches 321 run tp @s ^-0.058 ^-1.125 ^-0.111 ~ ~
execute if score .this aj.fram matches 322 run tp @s ^-0.058 ^-1.125 ^-0.111 ~ ~
execute if score .this aj.fram matches 323 run tp @s ^-0.058 ^-1.133 ^-0.111 ~ ~
execute if score .this aj.fram matches 324 run tp @s ^-0.058 ^-1.141 ^-0.111 ~ ~
execute if score .this aj.fram matches 325 run tp @s ^-0.058 ^-1.149 ^-0.111 ~ ~
execute if score .this aj.fram matches 326 run tp @s ^-0.058 ^-1.157 ^-0.111 ~ ~
execute if score .this aj.fram matches 327 run tp @s ^-0.058 ^-1.125 ^-0.111 ~ ~