#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 136 run tp @s ^-0.508 ^-0.277 ^0.747 ~ ~
execute if score .this aj.fram matches 137 run tp @s ^-0.498 ^-0.273 ^0.742 ~ ~
execute if score .this aj.fram matches 138 run tp @s ^-0.486 ^-0.27 ^0.738 ~ ~
execute if score .this aj.fram matches 139 run tp @s ^-0.474 ^-0.269 ^0.734 ~ ~
execute if score .this aj.fram matches 140 run tp @s ^-0.461 ^-0.269 ^0.731 ~ ~
execute if score .this aj.fram matches 141 run tp @s ^-0.448 ^-0.271 ^0.727 ~ ~
execute if score .this aj.fram matches 142 run tp @s ^-0.435 ^-0.275 ^0.722 ~ ~
execute if score .this aj.fram matches 143 run tp @s ^-0.422 ^-0.281 ^0.716 ~ ~