#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run tp @s ^-0.125 ^-1.043 ^0.239 ~ ~
execute if score .this aj.fram matches 153 run tp @s ^-0.125 ^-1.038 ^0.224 ~ ~
execute if score .this aj.fram matches 154 run tp @s ^-0.125 ^-1.034 ^0.209 ~ ~
execute if score .this aj.fram matches 155 run tp @s ^-0.125 ^-1.029 ^0.194 ~ ~
execute if score .this aj.fram matches 156 run tp @s ^-0.125 ^-1.025 ^0.178 ~ ~
execute if score .this aj.fram matches 157 run tp @s ^-0.125 ^-1.021 ^0.162 ~ ~
execute if score .this aj.fram matches 158 run tp @s ^-0.125 ^-1.018 ^0.147 ~ ~
execute if score .this aj.fram matches 159 run tp @s ^-0.125 ^-1.014 ^0.131 ~ ~