#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 120 run data modify entity @s Pose.Head set value [-123.6012f,-16.318f,8.8468f]
execute if score .this aj.fram matches 121 run data modify entity @s Pose.Head set value [-132.3358f,-14.5503f,11.0621f]
execute if score .this aj.fram matches 122 run data modify entity @s Pose.Head set value [-141.086f,-12.2014f,12.6534f]
execute if score .this aj.fram matches 123 run data modify entity @s Pose.Head set value [-149.5078f,-9.7139f,13.1803f]
execute if score .this aj.fram matches 124 run data modify entity @s Pose.Head set value [-157.3376f,-7.4671f,12.5705f]
execute if score .this aj.fram matches 125 run data modify entity @s Pose.Head set value [-164.3252f,-5.5558f,10.8483f]
execute if score .this aj.fram matches 126 run data modify entity @s Pose.Head set value [-170.2241f,-3.8441f,7.8684f]
execute if score .this aj.fram matches 127 run data modify entity @s Pose.Head set value [-174.9595f,-2.919f,3.2f]