#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 272 run data modify entity @s Pose.Head set value [-87.0309f,-35.3715f,28.723f]
execute if score .this aj.fram matches 273 run data modify entity @s Pose.Head set value [-87.4166f,-32.2463f,22.5022f]
execute if score .this aj.fram matches 274 run data modify entity @s Pose.Head set value [-89.0918f,-28.3662f,16.624f]
execute if score .this aj.fram matches 275 run data modify entity @s Pose.Head set value [-92.1093f,-23.9647f,11.0595f]
execute if score .this aj.fram matches 276 run data modify entity @s Pose.Head set value [-96.449f,-19.2782f,5.6965f]
execute if score .this aj.fram matches 277 run data modify entity @s Pose.Head set value [-102.0596f,-14.5388f,0.3876f]
execute if score .this aj.fram matches 278 run data modify entity @s Pose.Head set value [-108.8807f,-9.974f,-5.0163f]
execute if score .this aj.fram matches 279 run data modify entity @s Pose.Head set value [-116.8466f,-5.8098f,-10.641f]