#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 256 run data modify entity @s Pose.Head set value [-81.6098f,35.3591f,-11.3855f]
execute if score .this aj.fram matches 257 run data modify entity @s Pose.Head set value [-84.461f,34.8136f,-11.5235f]
execute if score .this aj.fram matches 258 run data modify entity @s Pose.Head set value [-87.3108f,34.268f,-11.6573f]
execute if score .this aj.fram matches 259 run data modify entity @s Pose.Head set value [-90.159f,33.7222f,-11.7869f]
execute if score .this aj.fram matches 260 run data modify entity @s Pose.Head set value [-93.006f,33.1762f,-11.9124f]
execute if score .this aj.fram matches 261 run data modify entity @s Pose.Head set value [-95.8516f,32.6302f,-12.0338f]
execute if score .this aj.fram matches 262 run data modify entity @s Pose.Head set value [-98.696f,32.084f,-12.1513f]
execute if score .this aj.fram matches 263 run data modify entity @s Pose.Head set value [-101.5393f,31.5378f,-12.2648f]