#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 224 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 225 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 226 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 227 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 228 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 229 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 230 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 231 run data modify entity @s Pose.Head set value [-81.6098f,35.3591f,-11.3855f]