#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run data modify entity @s Pose.Head set value [-72.5f,0f,0f]
execute if score .this aj.fram matches 153 run data modify entity @s Pose.Head set value [-68.6219f,-0.1491f,0.8192f]
execute if score .this aj.fram matches 154 run data modify entity @s Pose.Head set value [-64.3f,-0.2028f,1.4747f]
execute if score .this aj.fram matches 155 run data modify entity @s Pose.Head set value [-59.6142f,-0.1759f,1.9792f]
execute if score .this aj.fram matches 156 run data modify entity @s Pose.Head set value [-54.6445f,-0.0829f,2.3452f]
execute if score .this aj.fram matches 157 run data modify entity @s Pose.Head set value [-49.4708f,0.0616f,2.5855f]
execute if score .this aj.fram matches 158 run data modify entity @s Pose.Head set value [-44.1729f,0.2431f,2.7125f]
execute if score .this aj.fram matches 159 run data modify entity @s Pose.Head set value [-38.8308f,0.4471f,2.739f]