#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run tp @s ^-0.411 ^-0.289 ^0.709 ~ ~
execute if score .this aj.fram matches 145 run tp @s ^-0.401 ^-0.298 ^0.701 ~ ~
execute if score .this aj.fram matches 146 run tp @s ^-0.392 ^-0.309 ^0.691 ~ ~
execute if score .this aj.fram matches 147 run tp @s ^-0.386 ^-0.321 ^0.679 ~ ~
execute if score .this aj.fram matches 148 run tp @s ^-0.381 ^-0.338 ^0.667 ~ ~
execute if score .this aj.fram matches 149 run tp @s ^-0.377 ^-0.355 ^0.653 ~ ~
execute if score .this aj.fram matches 150 run tp @s ^-0.375 ^-0.372 ^0.636 ~ ~
execute if score .this aj.fram matches 151 run tp @s ^-0.375 ^-0.389 ^0.618 ~ ~