#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 336 run tp @s ^-0.058 ^-1.367 ^-0.398 ~ ~
execute if score .this aj.fram matches 337 run tp @s ^-0.058 ^-1.368 ^-0.403 ~ ~
execute if score .this aj.fram matches 338 run tp @s ^-0.058 ^-1.369 ^-0.408 ~ ~
execute if score .this aj.fram matches 339 run tp @s ^-0.058 ^-1.371 ^-0.413 ~ ~
execute if score .this aj.fram matches 340 run tp @s ^-0.058 ^-1.372 ^-0.418 ~ ~
execute if score .this aj.fram matches 341 run tp @s ^-0.058 ^-1.367 ^-0.398 ~ ~
execute if score .this aj.fram matches 342 run tp @s ^-0.058 ^-1.367 ^-0.398 ~ ~
execute if score .this aj.fram matches 343 run tp @s ^-0.058 ^-1.367 ^-0.398 ~ ~