#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 280 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 281 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 282 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 283 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 284 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 285 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 286 run data modify entity @s Pose.Head set value [135.5315f,1.4221f,178.2866f]
execute if score .this aj.fram matches 287 run data modify entity @s Pose.Head set value [141.09f,1.2389f,178.4916f]