#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 112 run data modify entity @s Pose.Head set value [-98.7001f,-18.351f,0.6651f]
execute if score .this aj.fram matches 113 run data modify entity @s Pose.Head set value [-102.044f,-18.2677f,1.8332f]
execute if score .this aj.fram matches 114 run data modify entity @s Pose.Head set value [-105.3807f,-18.1364f,2.9963f]
execute if score .this aj.fram matches 115 run data modify entity @s Pose.Head set value [-108.6808f,-17.9542f,4.1365f]
execute if score .this aj.fram matches 116 run data modify entity @s Pose.Head set value [-111.9148f,-17.7199f,5.2355f]
execute if score .this aj.fram matches 117 run data modify entity @s Pose.Head set value [-115.053f,-17.4341f,6.2745f]
execute if score .this aj.fram matches 118 run data modify entity @s Pose.Head set value [-118.0662f,-17.1001f,7.2348f]
execute if score .this aj.fram matches 119 run data modify entity @s Pose.Head set value [-120.9251f,-16.7246f,8.0981f]