#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 96 run tp @s ^-0.125 ^-1.627 ^0.442 ~ ~
execute if score .this aj.fram matches 97 run tp @s ^-0.125 ^-1.623 ^0.436 ~ ~
execute if score .this aj.fram matches 98 run tp @s ^-0.125 ^-1.618 ^0.43 ~ ~
execute if score .this aj.fram matches 99 run tp @s ^-0.125 ^-1.613 ^0.423 ~ ~
execute if score .this aj.fram matches 100 run tp @s ^-0.125 ^-1.608 ^0.417 ~ ~
execute if score .this aj.fram matches 101 run tp @s ^-0.125 ^-1.603 ^0.41 ~ ~
execute if score .this aj.fram matches 102 run tp @s ^-0.125 ^-1.598 ^0.404 ~ ~
execute if score .this aj.fram matches 103 run tp @s ^-0.125 ^-1.593 ^0.398 ~ ~