#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 448 run data modify entity @s Pose.Head set value [-52.5067f,21.6492f,-10.8416f]
execute if score .this aj.fram matches 449 run data modify entity @s Pose.Head set value [-46.703f,19.612f,-9.7221f]
execute if score .this aj.fram matches 450 run data modify entity @s Pose.Head set value [-40.9622f,17.5197f,-8.6029f]
execute if score .this aj.fram matches 451 run data modify entity @s Pose.Head set value [-35.3581f,15.3995f,-7.4968f]
execute if score .this aj.fram matches 452 run data modify entity @s Pose.Head set value [-29.9573f,13.2799f,-6.4159f]
execute if score .this aj.fram matches 453 run data modify entity @s Pose.Head set value [-24.8196f,11.191f,-5.3716f]
execute if score .this aj.fram matches 454 run data modify entity @s Pose.Head set value [-19.9978f,9.1635f,-4.3746f]
execute if score .this aj.fram matches 455 run data modify entity @s Pose.Head set value [-15.5389f,7.2284f,-3.4358f]