#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 416 run tp @s ^-0.058 ^-1.367 ^-2.029 ~ ~
execute if score .this aj.fram matches 417 run tp @s ^-0.058 ^-1.367 ^-2.056 ~ ~
execute if score .this aj.fram matches 418 run tp @s ^-0.058 ^-1.367 ^-2.083 ~ ~
execute if score .this aj.fram matches 419 run tp @s ^-0.058 ^-1.367 ^-2.11 ~ ~
execute if score .this aj.fram matches 420 run tp @s ^-0.058 ^-1.367 ^-2.137 ~ ~
execute if score .this aj.fram matches 421 run tp @s ^-0.058 ^-1.367 ^-2.164 ~ ~
execute if score .this aj.fram matches 422 run tp @s ^-0.058 ^-1.367 ^-2.192 ~ ~
execute if score .this aj.fram matches 423 run tp @s ^-0.058 ^-1.367 ^-2.219 ~ ~