#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 360 run tp @s ^-0.058 ^-1.367 ^-0.507 ~ ~
execute if score .this aj.fram matches 361 run tp @s ^-0.058 ^-1.367 ^-0.534 ~ ~
execute if score .this aj.fram matches 362 run tp @s ^-0.058 ^-1.367 ^-0.561 ~ ~
execute if score .this aj.fram matches 363 run tp @s ^-0.058 ^-1.367 ^-0.588 ~ ~
execute if score .this aj.fram matches 364 run tp @s ^-0.058 ^-1.367 ^-0.616 ~ ~
execute if score .this aj.fram matches 365 run tp @s ^-0.058 ^-1.367 ^-0.643 ~ ~
execute if score .this aj.fram matches 366 run tp @s ^-0.058 ^-1.367 ^-0.67 ~ ~
execute if score .this aj.fram matches 367 run tp @s ^-0.058 ^-1.367 ^-0.697 ~ ~