#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 368 run tp @s ^-0.058 ^-1.125 ^-0.437 ~ ~
execute if score .this aj.fram matches 369 run tp @s ^-0.058 ^-1.125 ^-0.464 ~ ~
execute if score .this aj.fram matches 370 run tp @s ^-0.058 ^-1.125 ^-0.491 ~ ~
execute if score .this aj.fram matches 371 run tp @s ^-0.058 ^-1.125 ^-0.518 ~ ~
execute if score .this aj.fram matches 372 run tp @s ^-0.058 ^-1.125 ^-0.546 ~ ~
execute if score .this aj.fram matches 373 run tp @s ^-0.058 ^-1.125 ^-0.573 ~ ~
execute if score .this aj.fram matches 374 run tp @s ^-0.058 ^-1.125 ^-0.6 ~ ~
execute if score .this aj.fram matches 375 run tp @s ^-0.058 ^-1.125 ^-0.627 ~ ~