#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 376 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 377 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 378 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 379 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 380 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 381 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 382 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]
execute if score .this aj.fram matches 383 run data modify entity @s Pose.Head set value [-78.7569f,35.9044f,-11.2431f]