#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 288 run data modify entity @s Pose.Head set value [146.6485f,1.0572f,178.6992f]
execute if score .this aj.fram matches 289 run data modify entity @s Pose.Head set value [152.207f,0.8771f,178.9094f]
execute if score .this aj.fram matches 290 run data modify entity @s Pose.Head set value [157.7656f,0.6984f,179.1223f]
execute if score .this aj.fram matches 291 run data modify entity @s Pose.Head set value [163.3242f,0.5214f,179.3378f]
execute if score .this aj.fram matches 292 run data modify entity @s Pose.Head set value [168.8828f,0.346f,179.5559f]
execute if score .this aj.fram matches 293 run data modify entity @s Pose.Head set value [174.4414f,0.1721f,179.7767f]
execute if score .this aj.fram matches 294 run data modify entity @s Pose.Head set value [-180f,0f,180f]
execute if score .this aj.fram matches 295 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]