#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 104 run tp @s ^-0.125 ^-1.273 ^0.596 ~ ~
execute if score .this aj.fram matches 105 run tp @s ^-0.125 ^-1.266 ^0.587 ~ ~
execute if score .this aj.fram matches 106 run tp @s ^-0.125 ^-1.259 ^0.578 ~ ~
execute if score .this aj.fram matches 107 run tp @s ^-0.125 ^-1.252 ^0.569 ~ ~
execute if score .this aj.fram matches 108 run tp @s ^-0.125 ^-1.245 ^0.56 ~ ~
execute if score .this aj.fram matches 109 run tp @s ^-0.125 ^-1.239 ^0.551 ~ ~
execute if score .this aj.fram matches 110 run tp @s ^-0.125 ^-1.232 ^0.542 ~ ~
execute if score .this aj.fram matches 111 run tp @s ^-0.125 ^-1.225 ^0.533 ~ ~