#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run data modify entity @s Pose.Head set value [40.8539f,-3.5733f,0f]
execute if score .this aj.fram matches 153 run data modify entity @s Pose.Head set value [38.2132f,-3.6885f,0f]
execute if score .this aj.fram matches 154 run data modify entity @s Pose.Head set value [35.4766f,-3.78f,0f]
execute if score .this aj.fram matches 155 run data modify entity @s Pose.Head set value [32.6702f,-3.8452f,0f]
execute if score .this aj.fram matches 156 run data modify entity @s Pose.Head set value [29.8202f,-3.8817f,0f]
execute if score .this aj.fram matches 157 run data modify entity @s Pose.Head set value [26.9528f,-3.8871f,0f]
execute if score .this aj.fram matches 158 run data modify entity @s Pose.Head set value [24.0941f,-3.8587f,0f]
execute if score .this aj.fram matches 159 run data modify entity @s Pose.Head set value [21.2704f,-3.7944f,0f]