#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 264 run tp @s ^-0.399 ^-0.367 ^0.065 ~ ~
execute if score .this aj.fram matches 265 run tp @s ^-0.391 ^-0.499 ^0.047 ~ ~
execute if score .this aj.fram matches 266 run tp @s ^-0.391 ^-0.499 ^0.047 ~ ~
execute if score .this aj.fram matches 267 run tp @s ^-0.391 ^-0.499 ^0.047 ~ ~
execute if score .this aj.fram matches 268 run tp @s ^-0.391 ^-0.499 ^0.047 ~ ~
execute if score .this aj.fram matches 269 run tp @s ^-0.391 ^-0.499 ^0.047 ~ ~
execute if score .this aj.fram matches 270 run tp @s ^-0.391 ^-0.499 ^0.047 ~ ~
execute if score .this aj.fram matches 271 run tp @s ^-0.394 ^-0.485 ^0.052 ~ ~