#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 384 run tp @s ^-0.058 ^-1.367 ^-1.159 ~ ~
execute if score .this aj.fram matches 385 run tp @s ^-0.058 ^-1.367 ^-1.186 ~ ~
execute if score .this aj.fram matches 386 run tp @s ^-0.058 ^-1.367 ^-1.213 ~ ~
execute if score .this aj.fram matches 387 run tp @s ^-0.058 ^-1.367 ^-1.241 ~ ~
execute if score .this aj.fram matches 388 run tp @s ^-0.058 ^-1.367 ^-1.268 ~ ~
execute if score .this aj.fram matches 389 run tp @s ^-0.058 ^-1.367 ^-1.295 ~ ~
execute if score .this aj.fram matches 390 run tp @s ^-0.058 ^-1.367 ^-1.322 ~ ~
execute if score .this aj.fram matches 391 run tp @s ^-0.058 ^-1.367 ^-1.349 ~ ~