#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 376 run tp @s ^-0.058 ^-1.125 ^-0.654 ~ ~
execute if score .this aj.fram matches 377 run tp @s ^-0.058 ^-1.125 ^-0.682 ~ ~
execute if score .this aj.fram matches 378 run tp @s ^-0.058 ^-1.125 ^-0.709 ~ ~
execute if score .this aj.fram matches 379 run tp @s ^-0.058 ^-1.125 ^-0.736 ~ ~
execute if score .this aj.fram matches 380 run tp @s ^-0.058 ^-1.125 ^-0.763 ~ ~
execute if score .this aj.fram matches 381 run tp @s ^-0.058 ^-1.125 ^-0.79 ~ ~
execute if score .this aj.fram matches 382 run tp @s ^-0.058 ^-1.125 ^-0.817 ~ ~
execute if score .this aj.fram matches 383 run tp @s ^-0.058 ^-1.125 ^-0.845 ~ ~