#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 192 run data modify entity @s Pose.Head set value [-48.0543f,16.44f,34.0528f]
execute if score .this aj.fram matches 193 run data modify entity @s Pose.Head set value [-48.0543f,16.44f,34.0528f]
execute if score .this aj.fram matches 194 run data modify entity @s Pose.Head set value [-48.0543f,16.44f,34.0528f]
execute if score .this aj.fram matches 195 run data modify entity @s Pose.Head set value [-48.0543f,16.44f,34.0528f]
execute if score .this aj.fram matches 196 run data modify entity @s Pose.Head set value [-48.0543f,16.44f,34.0528f]
execute if score .this aj.fram matches 197 run data modify entity @s Pose.Head set value [-48.0543f,16.44f,34.0528f]
execute if score .this aj.fram matches 198 run data modify entity @s Pose.Head set value [-48.0543f,16.44f,34.0528f]
execute if score .this aj.fram matches 199 run data modify entity @s Pose.Head set value [-48.0543f,16.44f,34.0528f]