#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 392 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 393 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 394 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 395 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 396 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 397 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 398 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]
execute if score .this aj.fram matches 399 run data modify entity @s Pose.Head set value [129.9731f,1.6067f,178.0844f]