#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.385 ^-0.744 ^1.037 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.381 ^-0.749 ^1.076 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.379 ^-0.81 ^1.088 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.377 ^-0.885 ^1.085 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.375 ^-0.941 ^1.089 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^-0.375 ^-0.949 ^1.097 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^-0.375 ^-0.953 ^1.1 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.375 ^-0.954 ^1.101 ~ ~