#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [44.5f,0f,0f]
execute if score .this aj.fram matches 82 run data modify entity @s Pose.Head set value [44f,0f,0f]
execute if score .this aj.fram matches 83 run data modify entity @s Pose.Head set value [43.5f,0f,0f]
execute if score .this aj.fram matches 84 run data modify entity @s Pose.Head set value [43f,0f,0f]
execute if score .this aj.fram matches 85 run data modify entity @s Pose.Head set value [42.5f,0f,0f]
execute if score .this aj.fram matches 86 run data modify entity @s Pose.Head set value [42f,0f,0f]
execute if score .this aj.fram matches 87 run data modify entity @s Pose.Head set value [41.5f,0f,0f]