#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 168 run data modify entity @s Pose.Head set value [2.0854f,-1.1845f,0f]
execute if score .this aj.fram matches 169 run data modify entity @s Pose.Head set value [1.0495f,-0.6238f,0f]
execute if score .this aj.fram matches 170 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 171 run data modify entity @s Pose.Head set value [-13.4511f,14.062f,-2.9414f]
execute if score .this aj.fram matches 172 run data modify entity @s Pose.Head set value [-33.6319f,31.6039f,-9.5851f]
execute if score .this aj.fram matches 173 run data modify entity @s Pose.Head set value [-55.1577f,50.1651f,-17.2642f]
execute if score .this aj.fram matches 174 run data modify entity @s Pose.Head set value [-71.61f,67.9248f,-22.5211f]
execute if score .this aj.fram matches 175 run data modify entity @s Pose.Head set value [-55f,83.75f,0f]