#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run tp @s ^-0.125 ^-1.095 ^0.346 ~ ~
execute if score .this aj.fram matches 145 run tp @s ^-0.125 ^-1.085 ^0.333 ~ ~
execute if score .this aj.fram matches 146 run tp @s ^-0.125 ^-1.076 ^0.32 ~ ~
execute if score .this aj.fram matches 147 run tp @s ^-0.125 ^-1.067 ^0.306 ~ ~
execute if score .this aj.fram matches 148 run tp @s ^-0.125 ^-1.062 ^0.294 ~ ~
execute if score .this aj.fram matches 149 run tp @s ^-0.125 ^-1.057 ^0.281 ~ ~
execute if score .this aj.fram matches 150 run tp @s ^-0.125 ^-1.052 ^0.268 ~ ~
execute if score .this aj.fram matches 151 run tp @s ^-0.125 ^-1.047 ^0.254 ~ ~