#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 208 run tp @s ^-0.41 ^-0.427 ^0.028 ~ ~
execute if score .this aj.fram matches 209 run tp @s ^-0.409 ^-0.417 ^0.035 ~ ~
execute if score .this aj.fram matches 210 run tp @s ^-0.407 ^-0.407 ^0.042 ~ ~
execute if score .this aj.fram matches 211 run tp @s ^-0.405 ^-0.397 ^0.048 ~ ~
execute if score .this aj.fram matches 212 run tp @s ^-0.403 ^-0.387 ^0.054 ~ ~
execute if score .this aj.fram matches 213 run tp @s ^-0.401 ^-0.377 ^0.06 ~ ~
execute if score .this aj.fram matches 214 run tp @s ^-0.399 ^-0.367 ^0.065 ~ ~
execute if score .this aj.fram matches 215 run tp @s ^-0.391 ^-0.499 ^0.047 ~ ~