#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 136 run data modify entity @s Pose.Head set value [174.6791f,13.3f,-27.0201f]
execute if score .this aj.fram matches 137 run data modify entity @s Pose.Head set value [177.6194f,17.6937f,-23.8662f]
execute if score .this aj.fram matches 138 run data modify entity @s Pose.Head set value [-178.5111f,22.2728f,-19.5482f]
execute if score .this aj.fram matches 139 run data modify entity @s Pose.Head set value [-173.512f,26.7462f,-13.8929f]
execute if score .this aj.fram matches 140 run data modify entity @s Pose.Head set value [-167.2154f,30.7622f,-6.76f]
execute if score .this aj.fram matches 141 run data modify entity @s Pose.Head set value [-159.5736f,33.9228f,1.868f]
execute if score .this aj.fram matches 142 run data modify entity @s Pose.Head set value [-150.7779f,35.8348f,11.7672f]
execute if score .this aj.fram matches 143 run data modify entity @s Pose.Head set value [-141.3268f,36.2036f,22.4024f]