#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 408 run tp @s ^-0.058 ^-1.367 ^-1.811 ~ ~
execute if score .this aj.fram matches 409 run tp @s ^-0.058 ^-1.367 ^-1.838 ~ ~
execute if score .this aj.fram matches 410 run tp @s ^-0.058 ^-1.367 ^-1.866 ~ ~
execute if score .this aj.fram matches 411 run tp @s ^-0.058 ^-1.367 ^-1.893 ~ ~
execute if score .this aj.fram matches 412 run tp @s ^-0.058 ^-1.367 ^-1.92 ~ ~
execute if score .this aj.fram matches 413 run tp @s ^-0.058 ^-1.367 ^-1.947 ~ ~
execute if score .this aj.fram matches 414 run tp @s ^-0.058 ^-1.367 ^-1.974 ~ ~
execute if score .this aj.fram matches 415 run tp @s ^-0.058 ^-1.367 ^-2.001 ~ ~