#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 256 run data modify entity @s Pose.Head set value [135.5315f,1.4221f,178.2866f]
execute if score .this aj.fram matches 257 run data modify entity @s Pose.Head set value [141.09f,1.2389f,178.4916f]
execute if score .this aj.fram matches 258 run data modify entity @s Pose.Head set value [146.6485f,1.0572f,178.6992f]
execute if score .this aj.fram matches 259 run data modify entity @s Pose.Head set value [152.207f,0.8771f,178.9094f]
execute if score .this aj.fram matches 260 run data modify entity @s Pose.Head set value [157.7656f,0.6984f,179.1223f]
execute if score .this aj.fram matches 261 run data modify entity @s Pose.Head set value [163.3242f,0.5214f,179.3378f]
execute if score .this aj.fram matches 262 run data modify entity @s Pose.Head set value [168.8828f,0.346f,179.5559f]
execute if score .this aj.fram matches 263 run data modify entity @s Pose.Head set value [174.4414f,0.1721f,179.7767f]