#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 192 run data modify entity @s Pose.Head set value [-77.9579f,40.8018f,-9.9568f]
execute if score .this aj.fram matches 193 run data modify entity @s Pose.Head set value [-77.9579f,40.8018f,-9.9568f]
execute if score .this aj.fram matches 194 run data modify entity @s Pose.Head set value [-77.9579f,40.8018f,-9.9568f]
execute if score .this aj.fram matches 195 run data modify entity @s Pose.Head set value [-77.9579f,40.8018f,-9.9568f]
execute if score .this aj.fram matches 196 run data modify entity @s Pose.Head set value [-77.9579f,40.8018f,-9.9568f]
execute if score .this aj.fram matches 197 run data modify entity @s Pose.Head set value [-77.9579f,40.8018f,-9.9568f]
execute if score .this aj.fram matches 198 run data modify entity @s Pose.Head set value [-77.9579f,40.8018f,-9.9568f]
execute if score .this aj.fram matches 199 run data modify entity @s Pose.Head set value [-77.9579f,40.8018f,-9.9568f]