#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [-47.5f,0f,0f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [-46.5845f,0.1694f,0.1735f]
execute if score .this aj.fram matches 82 run data modify entity @s Pose.Head set value [-45.4253f,0.3762f,0.3911f]
execute if score .this aj.fram matches 83 run data modify entity @s Pose.Head set value [-44.0517f,0.6165f,0.6477f]
execute if score .this aj.fram matches 84 run data modify entity @s Pose.Head set value [-42.4928f,0.8862f,0.9382f]
execute if score .this aj.fram matches 85 run data modify entity @s Pose.Head set value [-40.7777f,1.1816f,1.2573f]
execute if score .this aj.fram matches 86 run data modify entity @s Pose.Head set value [-38.9356f,1.4984f,1.6f]
execute if score .this aj.fram matches 87 run data modify entity @s Pose.Head set value [-36.9957f,1.8329f,1.9611f]