#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 384 run tp @s ^-0.391 ^-0.499 ^-0.714 ~ ~
execute if score .this aj.fram matches 385 run tp @s ^-0.391 ^-0.499 ^-0.741 ~ ~
execute if score .this aj.fram matches 386 run tp @s ^-0.391 ^-0.499 ^-0.769 ~ ~
execute if score .this aj.fram matches 387 run tp @s ^-0.391 ^-0.499 ^-0.796 ~ ~
execute if score .this aj.fram matches 388 run tp @s ^-0.391 ^-0.499 ^-0.823 ~ ~
execute if score .this aj.fram matches 389 run tp @s ^-0.391 ^-0.499 ^-0.85 ~ ~
execute if score .this aj.fram matches 390 run tp @s ^-0.391 ^-0.499 ^-0.877 ~ ~
execute if score .this aj.fram matches 391 run tp @s ^-0.391 ^-0.499 ^-0.904 ~ ~