#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players add .aj.animation aj.emis.anim 0
scoreboard players add .aj.anim_loop aj.emis.anim 0
scoreboard players add .noScripts aj.i 0