#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-10.1676f,0f,0f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-13.7003f,0f,0f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-17.3834f,0f,0f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-21.0938f,0f,0f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-24.7085f,0f,0f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-28.1045f,0f,0f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-31.1589f,0f,0f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-33.7486f,0f,0f]