#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 72 run data modify entity @s Pose.Head set value [24.75f,0f,0f]
execute if score .this aj.fram matches 73 run data modify entity @s Pose.Head set value [23.375f,0f,0f]
execute if score .this aj.fram matches 74 run data modify entity @s Pose.Head set value [22f,0f,0f]
execute if score .this aj.fram matches 75 run data modify entity @s Pose.Head set value [20.625f,0f,0f]
execute if score .this aj.fram matches 76 run data modify entity @s Pose.Head set value [19.25f,0f,0f]
execute if score .this aj.fram matches 77 run data modify entity @s Pose.Head set value [17.875f,0f,0f]
execute if score .this aj.fram matches 78 run data modify entity @s Pose.Head set value [16.5f,0f,0f]
execute if score .this aj.fram matches 79 run data modify entity @s Pose.Head set value [15.125f,0f,0f]