#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~