#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0..63 run function emis:animations/frwd/tree/left_arm2_root_0-63
execute if score .this aj.fram matches 64..91 run function emis:animations/frwd/tree/left_arm2_root_64-91