#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-159.4792f,18.7813f,-9.9502f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-165.7676f,24.4133f,-11.0871f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [-171.0207f,29.0547f,-11.9708f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-175f,32.5f,-12.5f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [-179.7256f,35.9854f,-12.9777f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [178.0214f,37.8994f,-13.3568f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [177.7338f,38.5527f,-13.5718f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [178.9194f,38.2625f,-13.5466f]