#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run data modify entity @s Pose.Head set value [-0.3988f,-23.3034f,-1.8295f]
execute if score .this aj.fram matches 89 run data modify entity @s Pose.Head set value [-0.2936f,-11.2358f,-0.7238f]
execute if score .this aj.fram matches 90 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 91 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 92 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 93 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 94 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 95 run data modify entity @s Pose.Head set value [0f,0f,0f]