#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [58.51f,-0.2f,1.12f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [47.1264f,-0.4677f,2.6449f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [30.6772f,-0.8431f,4.7854f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [15.996f,-1.1716f,6.6599f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [9.9162f,-1.2988f,7.3873f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [10.5929f,-1.2791f,7.276f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [12.266f,-1.2356f,7.0292f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [14.7989f,-1.1717f,6.6656f]