#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^0.313 ^-0.355 ^-0.281 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^0.313 ^-0.363 ^-0.294 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^0.313 ^-0.37 ^-0.305 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^0.313 ^-0.375 ^-0.312 ~ ~