#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 72 run tp @s ^0.125 ^-1.481 ^-0.297 ~ ~
execute if score .this aj.fram matches 73 run tp @s ^0.125 ^-1.472 ^-0.28 ~ ~
execute if score .this aj.fram matches 74 run tp @s ^0.125 ^-1.462 ^-0.264 ~ ~
execute if score .this aj.fram matches 75 run tp @s ^0.125 ^-1.449 ^-0.249 ~ ~
execute if score .this aj.fram matches 76 run tp @s ^0.125 ^-1.436 ^-0.234 ~ ~
execute if score .this aj.fram matches 77 run tp @s ^0.125 ^-1.423 ^-0.219 ~ ~
execute if score .this aj.fram matches 78 run tp @s ^0.125 ^-1.411 ^-0.204 ~ ~
execute if score .this aj.fram matches 79 run tp @s ^0.125 ^-1.401 ^-0.189 ~ ~