#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^0.117 ^-1.465 ^-0.386 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^0.12 ^-1.472 ^-0.402 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^0.123 ^-1.479 ^-0.415 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^0.125 ^-1.483 ^-0.425 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^0.125 ^-1.483 ^-0.425 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^0.125 ^-1.483 ^-0.425 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^0.125 ^-1.483 ^-0.425 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^0.125 ^-1.483 ^-0.425 ~ ~