#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [14.8419f,0.0128f,-0.0717f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [16.3812f,0.0081f,-0.0454f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [17.5f,0f,0f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [18.5965f,-0.0114f,0.0623f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [19.0672f,-0.0186f,0.0997f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [19.0509f,-0.0313f,0.1683f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [18.6866f,-0.0594f,0.3239f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [18.1133f,-0.1123f,0.6225f]