#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [-5.228f,1.1683f,-5.6439f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [-12.3822f,2.8433f,-13.4452f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [-20.9891f,4.8823f,-22.855f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [-30.5752f,7.1423f,-33.3241f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [-40.6671f,9.4806f,-44.3038f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [-50.7913f,11.7542f,-55.2448f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [-60.4742f,13.8204f,-65.5983f]