#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run tp @s ^-0.526 ^-0.939 ^0.111 ~ ~
execute if score .this aj.fram matches 89 run tp @s ^-0.445 ^-0.96 ^0.057 ~ ~
execute if score .this aj.fram matches 90 run tp @s ^-0.375 ^-0.968 ^0.025 ~ ~
execute if score .this aj.fram matches 91 run tp @s ^-0.375 ^-0.968 ^0.025 ~ ~
execute if score .this aj.fram matches 92 run tp @s ^-0.375 ^-0.968 ^0.025 ~ ~
execute if score .this aj.fram matches 93 run tp @s ^-0.375 ^-0.968 ^0.025 ~ ~
execute if score .this aj.fram matches 94 run tp @s ^-0.375 ^-0.968 ^0.025 ~ ~
execute if score .this aj.fram matches 95 run tp @s ^-0.375 ^-0.968 ^0.025 ~ ~