#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run tp @s ^-0.041 ^-0.69 ^1.573 ~ ~
execute if score .this aj.fram matches 81 run tp @s ^-0.117 ^-0.787 ^1.427 ~ ~
execute if score .this aj.fram matches 82 run tp @s ^-0.185 ^-0.869 ^1.258 ~ ~
execute if score .this aj.fram matches 83 run tp @s ^-0.244 ^-0.932 ^1.076 ~ ~
execute if score .this aj.fram matches 84 run tp @s ^-0.29 ^-0.975 ^0.887 ~ ~
execute if score .this aj.fram matches 85 run tp @s ^-0.326 ^-1 ^0.7 ~ ~
execute if score .this aj.fram matches 86 run tp @s ^-0.35 ^-1.009 ^0.522 ~ ~
execute if score .this aj.fram matches 87 run tp @s ^-0.365 ^-1.006 ^0.359 ~ ~