#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 72 run tp @s ^-0.312 ^-0.438 ^0.117 ~ ~
execute if score .this aj.fram matches 73 run tp @s ^-0.312 ^-0.421 ^0.111 ~ ~
execute if score .this aj.fram matches 74 run tp @s ^-0.312 ^-0.402 ^0.105 ~ ~
execute if score .this aj.fram matches 75 run tp @s ^-0.312 ^-0.381 ^0.098 ~ ~
execute if score .this aj.fram matches 76 run tp @s ^-0.312 ^-0.361 ^0.091 ~ ~
execute if score .this aj.fram matches 77 run tp @s ^-0.312 ^-0.341 ^0.083 ~ ~
execute if score .this aj.fram matches 78 run tp @s ^-0.312 ^-0.323 ^0.076 ~ ~
execute if score .this aj.fram matches 79 run tp @s ^-0.312 ^-0.307 ^0.069 ~ ~