#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^-0.119 ^-1.368 ^-0.027 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^-0.109 ^-1.377 ^-0.025 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^-0.094 ^-1.38 ^-0.029 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^-0.081 ^-1.371 ^-0.039 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^-0.076 ^-1.363 ^-0.045 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^-0.077 ^-1.365 ^-0.044 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^-0.078 ^-1.367 ^-0.042 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^-0.081 ^-1.37 ^-0.04 ~ ~