#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64..71 run function emis:animations/frwd/tree/right_leg2_display_64-71
execute if score .this aj.fram matches 72..79 run function emis:animations/frwd/tree/right_leg2_display_72-79
execute if score .this aj.fram matches 80..87 run function emis:animations/frwd/tree/right_leg2_display_80-87
execute if score .this aj.fram matches 88 run data modify entity @s Pose.Head set value [0.99f,0f,0f]
execute if score .this aj.fram matches 89 run data modify entity @s Pose.Head set value [0.5878f,0f,0f]
execute if score .this aj.fram matches 90 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 91 run data modify entity @s Pose.Head set value [0f,0f,0f]