#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 312 run tp @s ^0.552 ^-0.023 ^0.386 ~ ~
execute if score .this aj.fram matches 313 run tp @s ^0.552 ^-0.023 ^0.387 ~ ~
execute if score .this aj.fram matches 314 run tp @s ^0.552 ^-0.023 ^0.387 ~ ~
execute if score .this aj.fram matches 315 run tp @s ^0.552 ^-0.023 ^0.387 ~ ~
execute if score .this aj.fram matches 316 run tp @s ^0.552 ^-0.023 ^0.387 ~ ~
execute if score .this aj.fram matches 317 run tp @s ^0.552 ^-0.023 ^0.387 ~ ~
execute if score .this aj.fram matches 318 run tp @s ^0.552 ^-0.023 ^0.387 ~ ~
execute if score .this aj.fram matches 319 run tp @s ^0.552 ^-0.023 ^0.387 ~ ~