#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 128 run data modify entity @s Pose.Head set value [41.0562f,1.41f,0.5697f]
execute if score .this aj.fram matches 129 run data modify entity @s Pose.Head set value [43.0125f,0.5838f,0.263f]
execute if score .this aj.fram matches 130 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.fram matches 131 run data modify entity @s Pose.Head set value [43.95f,0f,0f]
execute if score .this aj.fram matches 132 run data modify entity @s Pose.Head set value [42.9f,0f,0f]
execute if score .this aj.fram matches 133 run data modify entity @s Pose.Head set value [42.85f,0f,0f]
execute if score .this aj.fram matches 134 run data modify entity @s Pose.Head set value [42.8f,0f,0f]
execute if score .this aj.fram matches 135 run data modify entity @s Pose.Head set value [44.75f,0f,0f]