#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 136 run tp @s ^0.552 ^-0.135 ^0.901 ~ ~
execute if score .this aj.fram matches 137 run tp @s ^0.552 ^-0.094 ^0.854 ~ ~
execute if score .this aj.fram matches 138 run tp @s ^0.552 ^-0.079 ^0.832 ~ ~
execute if score .this aj.fram matches 139 run tp @s ^0.552 ^-0.064 ^0.81 ~ ~
execute if score .this aj.fram matches 140 run tp @s ^0.552 ^-0.072 ^0.823 ~ ~
execute if score .this aj.fram matches 141 run tp @s ^0.552 ^-0.081 ^0.835 ~ ~
execute if score .this aj.fram matches 142 run tp @s ^0.552 ^-0.083 ^0.839 ~ ~
execute if score .this aj.fram matches 143 run tp @s ^0.552 ^-0.086 ^0.843 ~ ~