#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 288 run tp @s ^0.552 ^-0.023 ^0.386 ~ ~
execute if score .this aj.fram matches 289 run tp @s ^0.552 ^-0.023 ^0.386 ~ ~
execute if score .this aj.fram matches 290 run tp @s ^0.552 ^-0.023 ^0.386 ~ ~
execute if score .this aj.fram matches 291 run tp @s ^0.552 ^-0.023 ^0.386 ~ ~
execute if score .this aj.fram matches 292 run tp @s ^0.552 ^-0.023 ^0.386 ~ ~
execute if score .this aj.fram matches 293 run tp @s ^0.552 ^-0.023 ^0.386 ~ ~
execute if score .this aj.fram matches 294 run tp @s ^0.552 ^-0.023 ^0.386 ~ ~
execute if score .this aj.fram matches 295 run tp @s ^0.552 ^-0.023 ^0.386 ~ ~