#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-30f,0f,0f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-29.9878f,0f,0f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-29.9756f,0f,0f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-29.9633f,0f,0f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-29.9511f,0f,0f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-29.9389f,0f,0f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-29.9267f,0f,0f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-29.9144f,0f,0f]