#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 352 run data modify entity @s Pose.Head set value [-63.9414f,0f,0f]
execute if score .this aj.fram matches 353 run data modify entity @s Pose.Head set value [-63.9255f,0f,0f]
execute if score .this aj.fram matches 354 run data modify entity @s Pose.Head set value [-63.8966f,0f,0f]
execute if score .this aj.fram matches 355 run data modify entity @s Pose.Head set value [-63.8551f,0f,0f]
execute if score .this aj.fram matches 356 run data modify entity @s Pose.Head set value [-63.8016f,0f,0f]
execute if score .this aj.fram matches 357 run data modify entity @s Pose.Head set value [-63.7367f,0f,0f]
execute if score .this aj.fram matches 358 run data modify entity @s Pose.Head set value [-63.6608f,0f,0f]
execute if score .this aj.fram matches 359 run data modify entity @s Pose.Head set value [-63.5745f,0f,0f]