#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 152 run tp @s ^0.552 ^-0.042 ^0.773 ~ ~
execute if score .this aj.fram matches 153 run tp @s ^0.552 ^-0.045 ^0.778 ~ ~
execute if score .this aj.fram matches 154 run tp @s ^0.552 ^-0.047 ^0.782 ~ ~
execute if score .this aj.fram matches 155 run tp @s ^0.552 ^-0.049 ^0.786 ~ ~
execute if score .this aj.fram matches 156 run tp @s ^0.552 ^-0.034 ^0.757 ~ ~
execute if score .this aj.fram matches 157 run tp @s ^0.552 ^-0.025 ^0.738 ~ ~
execute if score .this aj.fram matches 158 run tp @s ^0.552 ^-0.016 ^0.719 ~ ~
execute if score .this aj.fram matches 159 run tp @s ^0.552 ^-0.02 ^0.728 ~ ~