#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^0.552 ^-0.03 ^0.392 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^0.552 ^-0.031 ^0.393 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^0.552 ^-0.032 ^0.394 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^0.552 ^-0.033 ^0.395 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^0.552 ^-0.034 ^0.395 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^0.552 ^-0.035 ^0.396 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^0.552 ^-0.035 ^0.396 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^0.552 ^-0.036 ^0.396 ~ ~