#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^0.552 ^0.057 ^0.317 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^0.552 ^0.074 ^0.36 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^0.552 ^0.055 ^0.424 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^0.552 ^-0.023 ^0.384 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^0.552 ^-0.024 ^0.386 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^0.552 ^-0.026 ^0.388 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^0.552 ^-0.028 ^0.39 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^0.552 ^-0.029 ^0.391 ~ ~