#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 448 run tp @s ^0.552 ^0.211 ^-0.427 ~ ~
execute if score .this aj.fram matches 449 run tp @s ^0.552 ^0.208 ^-0.391 ~ ~
execute if score .this aj.fram matches 450 run tp @s ^0.552 ^0.223 ^-0.341 ~ ~
execute if score .this aj.fram matches 451 run tp @s ^0.552 ^0.217 ^-0.162 ~ ~
execute if score .this aj.fram matches 452 run tp @s ^0.552 ^0.232 ^-0.029 ~ ~
execute if score .this aj.fram matches 453 run tp @s ^0.552 ^0.162 ^0.18 ~ ~
execute if score .this aj.fram matches 454 run tp @s ^0.552 ^0.154 ^0.344 ~ ~
execute if score .this aj.fram matches 455 run tp @s ^0.552 ^0.101 ^0.515 ~ ~