#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 544 run tp @s ^0.552 ^-1.622 ^2.302 ~ ~
execute if score .this aj.fram matches 545 run tp @s ^0.552 ^-1.622 ^2.302 ~ ~
execute if score .this aj.fram matches 546 run tp @s ^0.552 ^-1.622 ^2.302 ~ ~
execute if score .this aj.fram matches 547 run tp @s ^0.552 ^-1.622 ^2.302 ~ ~
execute if score .this aj.fram matches 548 run tp @s ^0.552 ^-1.622 ^2.302 ~ ~
execute if score .this aj.fram matches 549 run tp @s ^0.552 ^-1.622 ^2.302 ~ ~
execute if score .this aj.fram matches 550 run tp @s ^0.552 ^-1.622 ^2.302 ~ ~
execute if score .this aj.fram matches 551 run tp @s ^0.552 ^-1.622 ^2.302 ~ ~