#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-14.25f,0f,0f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-2.2093f,0f,0f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [12.187f,0f,0f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [22.5f,0f,0f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [22.8739f,-0.0022f,-0.0002f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [23.2144f,-0.0087f,-0.0006f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [23.5226f,-0.019f,-0.0012f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [23.7998f,-0.0331f,-0.0021f]