#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-0.4622f,0f,0f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-0.52f,0f,0f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-0.625f,0f,0f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-0.73f,0f,0f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-0.835f,0f,0f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-0.94f,0f,0f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-1.637f,0f,0f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-2.683f,0f,0f]