#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 200 run data modify entity @s Pose.Head set value [-15.4008f,0f,0f]
execute if score .this aj.fram matches 201 run data modify entity @s Pose.Head set value [-15.4175f,0f,0f]
execute if score .this aj.fram matches 202 run data modify entity @s Pose.Head set value [-15.3562f,0f,0f]
execute if score .this aj.fram matches 203 run data modify entity @s Pose.Head set value [-15.2505f,0f,0f]
execute if score .this aj.fram matches 204 run data modify entity @s Pose.Head set value [-15.1336f,0f,0f]
execute if score .this aj.fram matches 205 run data modify entity @s Pose.Head set value [-15.039f,0f,0f]
execute if score .this aj.fram matches 206 run data modify entity @s Pose.Head set value [-15f,0f,0f]
execute if score .this aj.fram matches 207 run data modify entity @s Pose.Head set value [-15f,0f,0f]