#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 128 run data modify entity @s Pose.Head set value [3f,0f,0f]
execute if score .this aj.fram matches 129 run data modify entity @s Pose.Head set value [5.25f,0f,0f]
execute if score .this aj.fram matches 130 run data modify entity @s Pose.Head set value [7.5f,0f,0f]
execute if score .this aj.fram matches 131 run data modify entity @s Pose.Head set value [7.5f,0f,0f]
execute if score .this aj.fram matches 132 run data modify entity @s Pose.Head set value [7.5f,0f,0f]
execute if score .this aj.fram matches 133 run data modify entity @s Pose.Head set value [7.5f,0f,0f]
execute if score .this aj.fram matches 134 run data modify entity @s Pose.Head set value [7.5f,0f,0f]
execute if score .this aj.fram matches 135 run data modify entity @s Pose.Head set value [7.5f,0f,0f]