#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 408 run data modify entity @s Pose.Head set value [-11.8421f,0f,0f]
execute if score .this aj.fram matches 409 run data modify entity @s Pose.Head set value [-11.0526f,0f,0f]
execute if score .this aj.fram matches 410 run data modify entity @s Pose.Head set value [-10.2632f,0f,0f]
execute if score .this aj.fram matches 411 run data modify entity @s Pose.Head set value [-9.4737f,0f,0f]
execute if score .this aj.fram matches 412 run data modify entity @s Pose.Head set value [-8.6842f,0f,0f]
execute if score .this aj.fram matches 413 run data modify entity @s Pose.Head set value [-7.8947f,0f,0f]
execute if score .this aj.fram matches 414 run data modify entity @s Pose.Head set value [-7.1053f,0f,0f]
execute if score .this aj.fram matches 415 run data modify entity @s Pose.Head set value [-6.3158f,0f,0f]