#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 96 run data modify entity @s Pose.Head set value [-15.9644f,0f,0f]
execute if score .this aj.fram matches 97 run data modify entity @s Pose.Head set value [-16.061f,0f,0f]
execute if score .this aj.fram matches 98 run data modify entity @s Pose.Head set value [-16.1547f,0f,0f]
execute if score .this aj.fram matches 99 run data modify entity @s Pose.Head set value [-16.2443f,0f,0f]
execute if score .this aj.fram matches 100 run data modify entity @s Pose.Head set value [-16.3285f,0f,0f]
execute if score .this aj.fram matches 101 run data modify entity @s Pose.Head set value [-16.4062f,0f,0f]
execute if score .this aj.fram matches 102 run data modify entity @s Pose.Head set value [-16.4762f,0f,0f]
execute if score .this aj.fram matches 103 run data modify entity @s Pose.Head set value [-16.5371f,0f,0f]