#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 416 run tp @s ^0 ^0.412 ^0.101 ~ ~
execute if score .this aj.fram matches 417 run tp @s ^0 ^0.395 ^0.082 ~ ~
execute if score .this aj.fram matches 418 run tp @s ^0 ^0.379 ^0.063 ~ ~
execute if score .this aj.fram matches 419 run tp @s ^0 ^0.362 ^0.044 ~ ~
execute if score .this aj.fram matches 420 run tp @s ^0 ^0.346 ^0.025 ~ ~
execute if score .this aj.fram matches 421 run tp @s ^0 ^0.329 ^0.007 ~ ~
execute if score .this aj.fram matches 422 run tp @s ^0 ^0.313 ^-0.012 ~ ~
execute if score .this aj.fram matches 423 run tp @s ^0 ^0.296 ^-0.031 ~ ~