#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 120 run data modify entity @s Pose.Head set value [25.0589f,9.9775f,0.6745f]
execute if score .this aj.fram matches 121 run data modify entity @s Pose.Head set value [27.1974f,9.3071f,1.0035f]
execute if score .this aj.fram matches 122 run data modify entity @s Pose.Head set value [29.2798f,8.39f,1.2444f]
execute if score .this aj.fram matches 123 run data modify entity @s Pose.Head set value [31.3109f,7.2929f,1.3797f]
execute if score .this aj.fram matches 124 run data modify entity @s Pose.Head set value [33.2987f,6.0829f,1.4022f]
execute if score .this aj.fram matches 125 run data modify entity @s Pose.Head set value [35.2542f,4.8263f,1.3151f]
execute if score .this aj.fram matches 126 run data modify entity @s Pose.Head set value [37.19f,3.5877f,1.131f]
execute if score .this aj.fram matches 127 run data modify entity @s Pose.Head set value [39.1195f,2.4294f,0.8722f]