#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 120 run tp @s ^0 ^-0.581 ^0.187 ~ ~
execute if score .this aj.fram matches 121 run tp @s ^0 ^-0.579 ^0.217 ~ ~
execute if score .this aj.fram matches 122 run tp @s ^0 ^-0.577 ^0.248 ~ ~
execute if score .this aj.fram matches 123 run tp @s ^0 ^-0.575 ^0.279 ~ ~
execute if score .this aj.fram matches 124 run tp @s ^0 ^-0.573 ^0.309 ~ ~
execute if score .this aj.fram matches 125 run tp @s ^0 ^-0.571 ^0.34 ~ ~
execute if score .this aj.fram matches 126 run tp @s ^0 ^-0.569 ^0.37 ~ ~
execute if score .this aj.fram matches 127 run tp @s ^0 ^-0.568 ^0.401 ~ ~