#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 104 run data modify entity @s Pose.Head set value [23.6287f,10.791f,0.4219f]
execute if score .this aj.fram matches 105 run data modify entity @s Pose.Head set value [23.6198f,10.9285f,0.4188f]
execute if score .this aj.fram matches 106 run data modify entity @s Pose.Head set value [23.6181f,11.041f,0.4173f]
execute if score .this aj.fram matches 107 run data modify entity @s Pose.Head set value [23.6249f,11.1285f,0.4175f]
execute if score .this aj.fram matches 108 run data modify entity @s Pose.Head set value [23.6416f,11.1908f,0.42f]
execute if score .this aj.fram matches 109 run data modify entity @s Pose.Head set value [23.6694f,11.2281f,0.4249f]
execute if score .this aj.fram matches 110 run data modify entity @s Pose.Head set value [23.7096f,11.2403f,0.4326f]
execute if score .this aj.fram matches 111 run data modify entity @s Pose.Head set value [23.7634f,11.2274f,0.4433f]