#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 376 run data modify entity @s Pose.Head set value [0.9093f,0f,0f]
execute if score .this aj.fram matches 377 run data modify entity @s Pose.Head set value [0.8892f,0f,0f]
execute if score .this aj.fram matches 378 run data modify entity @s Pose.Head set value [0.8681f,0f,0f]
execute if score .this aj.fram matches 379 run data modify entity @s Pose.Head set value [0.8458f,0f,0f]
execute if score .this aj.fram matches 380 run data modify entity @s Pose.Head set value [0.8225f,0f,0f]
execute if score .this aj.fram matches 381 run data modify entity @s Pose.Head set value [0.798f,0f,0f]
execute if score .this aj.fram matches 382 run data modify entity @s Pose.Head set value [0.7724f,0f,0f]
execute if score .this aj.fram matches 383 run data modify entity @s Pose.Head set value [0.7457f,0f,0f]