#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 240 run tp @s ^0.125 ^-1.366 ^0.397 ~ ~
execute if score .this aj.fram matches 241 run tp @s ^0.125 ^-1.366 ^0.397 ~ ~
execute if score .this aj.fram matches 242 run tp @s ^0.125 ^-1.366 ^0.397 ~ ~
execute if score .this aj.fram matches 243 run tp @s ^0.125 ^-1.366 ^0.397 ~ ~
execute if score .this aj.fram matches 244 run tp @s ^0.125 ^-1.366 ^0.397 ~ ~
execute if score .this aj.fram matches 245 run tp @s ^0.125 ^-1.366 ^0.397 ~ ~
execute if score .this aj.fram matches 246 run tp @s ^0.125 ^-1.366 ^0.397 ~ ~
execute if score .this aj.fram matches 247 run tp @s ^0.125 ^-1.366 ^0.397 ~ ~