#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 304 run tp @s ^0.243 ^-1.657 ^0.602 ~ ~
execute if score .this aj.fram matches 305 run tp @s ^0.243 ^-1.657 ^0.601 ~ ~
execute if score .this aj.fram matches 306 run tp @s ^0.243 ^-1.658 ^0.601 ~ ~
execute if score .this aj.fram matches 307 run tp @s ^0.242 ^-1.658 ^0.601 ~ ~
execute if score .this aj.fram matches 308 run tp @s ^0.242 ^-1.658 ^0.6 ~ ~
execute if score .this aj.fram matches 309 run tp @s ^0.241 ^-1.659 ^0.6 ~ ~
execute if score .this aj.fram matches 310 run tp @s ^0.241 ^-1.659 ^0.599 ~ ~
execute if score .this aj.fram matches 311 run tp @s ^0.241 ^-1.66 ^0.599 ~ ~