#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [0.0039f,0f,0f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [0.001f,0f,0f]
execute if score .this aj.fram matches 82 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 83 run data modify entity @s Pose.Head set value [-0.0034f,0f,0f]
execute if score .this aj.fram matches 84 run data modify entity @s Pose.Head set value [-0.0131f,0f,0f]
execute if score .this aj.fram matches 85 run data modify entity @s Pose.Head set value [-0.0287f,0f,0f]
execute if score .this aj.fram matches 86 run data modify entity @s Pose.Head set value [-0.0496f,0f,0f]
execute if score .this aj.fram matches 87 run data modify entity @s Pose.Head set value [-0.0752f,0f,0f]