#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [0.7319f,-2.2781f,-2.8763f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [0.8726f,-2.7155f,-3.4289f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [1.027f,-3.1949f,-4.035f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [1.1958f,-3.7189f,-4.6976f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [1.38f,-4.29f,-5.42f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [2.161f,-6.6068f,-8.3675f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [3.1553f,-9.5132f,-12.0766f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [4.0694f,-12.3066f,-15.6235f]