#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 456 run tp @s ^0.313 ^-0.554 ^0.531 ~ ~
execute if score .this aj.fram matches 457 run tp @s ^0.313 ^-0.554 ^0.531 ~ ~
execute if score .this aj.fram matches 458 run tp @s ^0.313 ^-0.641 ^0.959 ~ ~
execute if score .this aj.fram matches 459 run tp @s ^0.313 ^-0.882 ^1.32 ~ ~
execute if score .this aj.fram matches 460 run tp @s ^0.313 ^-1.051 ^1.459 ~ ~
execute if score .this aj.fram matches 461 run tp @s ^0.313 ^-1.246 ^1.566 ~ ~
execute if score .this aj.fram matches 462 run tp @s ^0.313 ^-1.679 ^1.65 ~ ~
execute if score .this aj.fram matches 463 run tp @s ^0.313 ^-1.679 ^1.65 ~ ~