#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 56 run data modify entity @s Pose.Head set value [-4.9234f,-0.8294f,3.2129f]
execute if score .this aj.fram matches 57 run data modify entity @s Pose.Head set value [-5.3861f,-0.9425f,3.3735f]
execute if score .this aj.fram matches 58 run data modify entity @s Pose.Head set value [-5.8036f,-1.0445f,3.5163f]
execute if score .this aj.fram matches 59 run data modify entity @s Pose.Head set value [-6.1673f,-1.1329f,3.6386f]
execute if score .this aj.fram matches 60 run data modify entity @s Pose.Head set value [-6.4685f,-1.2054f,3.7381f]
execute if score .this aj.fram matches 61 run data modify entity @s Pose.Head set value [-6.6987f,-1.2598f,3.8123f]
execute if score .this aj.fram matches 62 run data modify entity @s Pose.Head set value [-6.8492f,-1.2937f,3.8588f]
execute if score .this aj.fram matches 63 run data modify entity @s Pose.Head set value [-6.9114f,-1.3048f,3.8751f]