#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 336 run data modify entity @s Pose.Head set value [9.1201f,4.3455f,-4.1373f]
execute if score .this aj.fram matches 337 run data modify entity @s Pose.Head set value [8.6622f,4.3326f,-4.1793f]
execute if score .this aj.fram matches 338 run data modify entity @s Pose.Head set value [8.4659f,4.3271f,-4.1973f]
execute if score .this aj.fram matches 339 run data modify entity @s Pose.Head set value [8.559f,4.4349f,-4.2169f]
execute if score .this aj.fram matches 340 run data modify entity @s Pose.Head set value [8.7636f,4.6723f,-4.2602f]
execute if score .this aj.fram matches 341 run data modify entity @s Pose.Head set value [8.9679f,4.9096f,-4.3035f]
execute if score .this aj.fram matches 342 run data modify entity @s Pose.Head set value [9.0607f,5.0175f,-4.3232f]
execute if score .this aj.fram matches 343 run data modify entity @s Pose.Head set value [8.9308f,4.8664f,-4.2957f]