#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 456 run tp @s ^0.141 ^-1.678 ^0.53 ~ ~
execute if score .this aj.fram matches 457 run tp @s ^0.141 ^-1.678 ^0.53 ~ ~
execute if score .this aj.fram matches 458 run tp @s ^0.139 ^-1.744 ^0.738 ~ ~
execute if score .this aj.fram matches 459 run tp @s ^0.133 ^-1.677 ^0.524 ~ ~
execute if score .this aj.fram matches 460 run tp @s ^0.131 ^-1.676 ^0.523 ~ ~
execute if score .this aj.fram matches 461 run tp @s ^0.129 ^-1.676 ^0.527 ~ ~
execute if score .this aj.fram matches 462 run tp @s ^0.125 ^-1.679 ^0.525 ~ ~
execute if score .this aj.fram matches 463 run tp @s ^0.125 ^-1.679 ^0.525 ~ ~