#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 256..263 run function emis:animations/dies/tree/left_leg2_display_256-263
execute if score .this aj.fram matches 264..271 run function emis:animations/dies/tree/left_leg2_display_264-271
execute if score .this aj.fram matches 272..279 run function emis:animations/dies/tree/left_leg2_display_272-279
execute if score .this aj.fram matches 280..287 run function emis:animations/dies/tree/left_leg2_display_280-287
execute if score .this aj.fram matches 288..295 run function emis:animations/dies/tree/left_leg2_display_288-295
execute if score .this aj.fram matches 296..303 run function emis:animations/dies/tree/left_leg2_display_296-303
execute if score .this aj.fram matches 304..311 run function emis:animations/dies/tree/left_leg2_display_304-311
execute if score .this aj.fram matches 312..319 run function emis:animations/dies/tree/left_leg2_display_312-319