#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [40.8209f,14.7403f,-11.2433f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [36.3497f,12.9523f,-9.3956f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [25.4961f,8.7439f,-5.3793f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [12.0997f,3.8487f,-1.4842f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [-11.1039f,-2.5096f,-2.2878f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-22.8183f,-4.5455f,-6.8774f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-33.2614f,-6.1165f,-11.8088f]