#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 145 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 146 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 147 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 148 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 149 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 150 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 151 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~