#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 168 run data modify entity @s Pose.Head set value [91.5017f,-11.2999f,-8.2806f]
execute if score .this aj.fram matches 169 run data modify entity @s Pose.Head set value [91.5017f,-11.2999f,-8.2806f]
execute if score .this aj.fram matches 170 run data modify entity @s Pose.Head set value [91.5017f,-11.2999f,-8.2806f]
execute if score .this aj.fram matches 171 run data modify entity @s Pose.Head set value [91.5017f,-11.2999f,-8.2806f]
execute if score .this aj.fram matches 172 run data modify entity @s Pose.Head set value [91.5017f,-11.2999f,-8.2806f]
execute if score .this aj.fram matches 173 run data modify entity @s Pose.Head set value [91.5017f,-11.2999f,-8.2806f]
execute if score .this aj.fram matches 174 run data modify entity @s Pose.Head set value [91.5017f,-11.2999f,-8.2806f]
execute if score .this aj.fram matches 175 run data modify entity @s Pose.Head set value [91.5017f,-11.2999f,-8.2806f]