#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [1.6091f,0.601f,0.1838f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [1.5932f,0.6264f,0.3011f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [1.4848f,0.6256f,0.4395f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [1.2926f,0.6008f,0.5963f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [1.0251f,0.5546f,0.7693f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [0.6909f,0.489f,0.9559f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [0.2986f,0.4066f,1.1537f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [-0.1431f,0.3097f,1.3602f]