#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.488 ^-0.48 ^-0.114 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.471 ^-0.503 ^-0.07 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.43 ^-0.554 ^0.012 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.39 ^-0.6 ^0.12 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.375 ^-0.625 ^0.234 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.393 ^-0.662 ^0.429 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.427 ^-0.71 ^0.624 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.459 ^-0.759 ^0.768 ~ ~