#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 272 run data modify entity @s Pose.Head set value [92.8686f,-15.5285f,-0.3872f]
execute if score .this aj.fram matches 273 run data modify entity @s Pose.Head set value [92.8971f,-15.5339f,-0.3917f]
execute if score .this aj.fram matches 274 run data modify entity @s Pose.Head set value [92.9234f,-15.5388f,-0.3958f]
execute if score .this aj.fram matches 275 run data modify entity @s Pose.Head set value [92.9474f,-15.5433f,-0.3995f]
execute if score .this aj.fram matches 276 run data modify entity @s Pose.Head set value [92.969f,-15.5474f,-0.4029f]
execute if score .this aj.fram matches 277 run data modify entity @s Pose.Head set value [92.9881f,-15.551f,-0.406f]
execute if score .this aj.fram matches 278 run data modify entity @s Pose.Head set value [93.0046f,-15.5541f,-0.4086f]
execute if score .this aj.fram matches 279 run data modify entity @s Pose.Head set value [93.0185f,-15.5568f,-0.4108f]