#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 336 run data modify entity @s Pose.Head set value [48.2868f,-3.8983f,-6.8104f]
execute if score .this aj.fram matches 337 run data modify entity @s Pose.Head set value [47.9719f,-3.9095f,-6.8105f]
execute if score .this aj.fram matches 338 run data modify entity @s Pose.Head set value [47.837f,-3.9143f,-6.8106f]
execute if score .this aj.fram matches 339 run data modify entity @s Pose.Head set value [48.3816f,-3.8976f,-6.8735f]
execute if score .this aj.fram matches 340 run data modify entity @s Pose.Head set value [49.5791f,-3.8607f,-7.013f]
execute if score .this aj.fram matches 341 run data modify entity @s Pose.Head set value [50.7757f,-3.8232f,-7.1538f]
execute if score .this aj.fram matches 342 run data modify entity @s Pose.Head set value [51.3194f,-3.806f,-7.2183f]
execute if score .this aj.fram matches 343 run data modify entity @s Pose.Head set value [50.5582f,-3.83f,-7.1281f]