#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 136 run data modify entity @s Pose.Head set value [0.2995f,0.1055f,-4.2525f]
execute if score .this aj.fram matches 137 run data modify entity @s Pose.Head set value [0.342f,0.1214f,-4.9631f]
execute if score .this aj.fram matches 138 run data modify entity @s Pose.Head set value [0.3835f,0.1372f,-5.6737f]
execute if score .this aj.fram matches 139 run data modify entity @s Pose.Head set value [0.4238f,0.1529f,-6.3843f]
execute if score .this aj.fram matches 140 run data modify entity @s Pose.Head set value [-4.513f,0.1812f,-7.4496f]
execute if score .this aj.fram matches 141 run data modify entity @s Pose.Head set value [-9.4522f,0.2091f,-8.5148f]
execute if score .this aj.fram matches 142 run data modify entity @s Pose.Head set value [-9.4131f,0.2238f,-9.222f]
execute if score .this aj.fram matches 143 run data modify entity @s Pose.Head set value [-9.375f,0.2383f,-9.9293f]