#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 192 run tp @s ^0.246 ^-1.698 ^0.592 ~ ~
execute if score .this aj.fram matches 193 run tp @s ^0.241 ^-1.677 ^0.596 ~ ~
execute if score .this aj.fram matches 194 run tp @s ^0.239 ^-1.668 ^0.596 ~ ~
execute if score .this aj.fram matches 195 run tp @s ^0.237 ^-1.664 ^0.595 ~ ~
execute if score .this aj.fram matches 196 run tp @s ^0.235 ^-1.664 ^0.593 ~ ~
execute if score .this aj.fram matches 197 run tp @s ^0.235 ^-1.667 ^0.592 ~ ~
execute if score .this aj.fram matches 198 run tp @s ^0.234 ^-1.667 ^0.592 ~ ~
execute if score .this aj.fram matches 199 run tp @s ^0.234 ^-1.666 ^0.592 ~ ~