#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 400 run tp @s ^0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 401 run tp @s ^0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 402 run tp @s ^0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 403 run tp @s ^0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 404 run tp @s ^0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 405 run tp @s ^0.125 ^-0.135 ^0.493 ~ ~
execute if score .this aj.fram matches 406 run tp @s ^0.125 ^-0.154 ^0.464 ~ ~
execute if score .this aj.fram matches 407 run tp @s ^0.125 ^-0.172 ^0.435 ~ ~