#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 208 run data modify entity @s Pose.Head set value [90.0094f,-15.0016f,-0.003f]
execute if score .this aj.fram matches 209 run data modify entity @s Pose.Head set value [90.0167f,-15.0029f,-0.0038f]
execute if score .this aj.fram matches 210 run data modify entity @s Pose.Head set value [90.0268f,-15.0048f,-0.0049f]
execute if score .this aj.fram matches 211 run data modify entity @s Pose.Head set value [90.0397f,-15.0072f,-0.0064f]
execute if score .this aj.fram matches 212 run data modify entity @s Pose.Head set value [90.0552f,-15.01f,-0.0082f]
execute if score .this aj.fram matches 213 run data modify entity @s Pose.Head set value [90.0733f,-15.0133f,-0.0102f]
execute if score .this aj.fram matches 214 run data modify entity @s Pose.Head set value [90.0938f,-15.0171f,-0.0126f]
execute if score .this aj.fram matches 215 run data modify entity @s Pose.Head set value [90.1168f,-15.0213f,-0.0152f]