#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 480 run data modify entity @s Pose.Head set value [90f,45f,0f]
execute if score .this aj.fram matches 481 run data modify entity @s Pose.Head set value [90f,45f,0f]
execute if score .this aj.fram matches 482 run data modify entity @s Pose.Head set value [90f,45f,0f]
execute if score .this aj.fram matches 483 run data modify entity @s Pose.Head set value [90f,45f,0f]
execute if score .this aj.fram matches 484 run data modify entity @s Pose.Head set value [90f,45f,0f]
execute if score .this aj.fram matches 485 run data modify entity @s Pose.Head set value [90f,45f,0f]
execute if score .this aj.fram matches 486 run data modify entity @s Pose.Head set value [90f,45f,0f]
execute if score .this aj.fram matches 487 run data modify entity @s Pose.Head set value [90f,45f,0f]