#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 240 run data modify entity @s Pose.Head set value [0.0453f,0f,0f]
execute if score .this aj.fram matches 241 run data modify entity @s Pose.Head set value [0.0418f,0f,0f]
execute if score .this aj.fram matches 242 run data modify entity @s Pose.Head set value [0.0382f,0f,0f]
execute if score .this aj.fram matches 243 run data modify entity @s Pose.Head set value [0.0347f,0f,0f]
execute if score .this aj.fram matches 244 run data modify entity @s Pose.Head set value [0.0311f,0f,0f]
execute if score .this aj.fram matches 245 run data modify entity @s Pose.Head set value [0.0277f,0f,0f]
execute if score .this aj.fram matches 246 run data modify entity @s Pose.Head set value [0.0243f,0f,0f]
execute if score .this aj.fram matches 247 run data modify entity @s Pose.Head set value [0.021f,0f,0f]