#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 400 run data modify entity @s Pose.Head set value [0.1013f,0f,0f]
execute if score .this aj.fram matches 401 run data modify entity @s Pose.Head set value [0.0514f,0f,0f]
execute if score .this aj.fram matches 402 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 403 run data modify entity @s Pose.Head set value [-0.335f,0f,0f]
execute if score .this aj.fram matches 404 run data modify entity @s Pose.Head set value [-0.7363f,0f,0f]
execute if score .this aj.fram matches 405 run data modify entity @s Pose.Head set value [-0.4086f,0f,0f]
execute if score .this aj.fram matches 406 run data modify entity @s Pose.Head set value [-0.1356f,0f,0f]
execute if score .this aj.fram matches 407 run data modify entity @s Pose.Head set value [0.0884f,0f,0f]