#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 464 run tp @s ^0.125 ^-1.679 ^0.9 ~ ~
execute if score .this aj.fram matches 465 run tp @s ^0.125 ^-1.679 ^0.9 ~ ~
execute if score .this aj.fram matches 466 run tp @s ^0.125 ^-1.679 ^0.9 ~ ~
execute if score .this aj.fram matches 467 run tp @s ^0.125 ^-1.679 ^0.9 ~ ~
execute if score .this aj.fram matches 468 run tp @s ^0.125 ^-1.679 ^0.9 ~ ~
execute if score .this aj.fram matches 469 run tp @s ^0.125 ^-1.679 ^0.9 ~ ~
execute if score .this aj.fram matches 470 run tp @s ^0.125 ^-1.679 ^0.9 ~ ~
execute if score .this aj.fram matches 471 run tp @s ^0.125 ^-1.679 ^0.9 ~ ~