#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 264 run data modify entity @s Pose.Head set value [-36.8747f,-23.9232f,-5.5109f]
execute if score .this aj.fram matches 265 run data modify entity @s Pose.Head set value [-36.9219f,-23.9512f,-5.5114f]
execute if score .this aj.fram matches 266 run data modify entity @s Pose.Head set value [-36.9674f,-23.9783f,-5.5119f]
execute if score .this aj.fram matches 267 run data modify entity @s Pose.Head set value [-37.0111f,-24.0042f,-5.5123f]
execute if score .this aj.fram matches 268 run data modify entity @s Pose.Head set value [-37.0528f,-24.029f,-5.5127f]
execute if score .this aj.fram matches 269 run data modify entity @s Pose.Head set value [-37.0926f,-24.0526f,-5.5131f]
execute if score .this aj.fram matches 270 run data modify entity @s Pose.Head set value [-37.1302f,-24.075f,-5.5135f]
execute if score .this aj.fram matches 271 run data modify entity @s Pose.Head set value [-37.1657f,-24.0961f,-5.5138f]