#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 256 run data modify entity @s Pose.Head set value [-36.4448f,-23.6674f,-5.5064f]
execute if score .this aj.fram matches 257 run data modify entity @s Pose.Head set value [-36.5028f,-23.702f,-5.507f]
execute if score .this aj.fram matches 258 run data modify entity @s Pose.Head set value [-36.5598f,-23.7359f,-5.5077f]
execute if score .this aj.fram matches 259 run data modify entity @s Pose.Head set value [-36.6156f,-23.7691f,-5.5082f]
execute if score .this aj.fram matches 260 run data modify entity @s Pose.Head set value [-36.6702f,-23.8015f,-5.5088f]
execute if score .this aj.fram matches 261 run data modify entity @s Pose.Head set value [-36.7235f,-23.8332f,-5.5094f]
execute if score .this aj.fram matches 262 run data modify entity @s Pose.Head set value [-36.7754f,-23.8641f,-5.5099f]
execute if score .this aj.fram matches 263 run data modify entity @s Pose.Head set value [-36.8259f,-23.8941f,-5.5104f]