#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 248 run data modify entity @s Pose.Head set value [91.7172f,-15.3149f,-0.2178f]
execute if score .this aj.fram matches 249 run data modify entity @s Pose.Head set value [91.7757f,-15.3257f,-0.2259f]
execute if score .this aj.fram matches 250 run data modify entity @s Pose.Head set value [91.8339f,-15.3364f,-0.234f]
execute if score .this aj.fram matches 251 run data modify entity @s Pose.Head set value [91.8916f,-15.3471f,-0.2422f]
execute if score .this aj.fram matches 252 run data modify entity @s Pose.Head set value [91.9489f,-15.3576f,-0.2503f]
execute if score .this aj.fram matches 253 run data modify entity @s Pose.Head set value [92.0056f,-15.3681f,-0.2584f]
execute if score .this aj.fram matches 254 run data modify entity @s Pose.Head set value [92.0616f,-15.3785f,-0.2664f]
execute if score .this aj.fram matches 255 run data modify entity @s Pose.Head set value [92.1169f,-15.3887f,-0.2744f]