#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run data modify entity @s Pose.Head set value [90.0217f,-15.1519f,-0.0012f]
execute if score .this aj.fram matches 65 run data modify entity @s Pose.Head set value [90.0203f,-15.1398f,-0.0014f]
execute if score .this aj.fram matches 66 run data modify entity @s Pose.Head set value [90.0189f,-15.1277f,-0.0016f]
execute if score .this aj.fram matches 67 run data modify entity @s Pose.Head set value [90.0175f,-15.1156f,-0.0018f]
execute if score .this aj.fram matches 68 run data modify entity @s Pose.Head set value [90.0161f,-15.1036f,-0.0019f]
execute if score .this aj.fram matches 69 run data modify entity @s Pose.Head set value [90.0147f,-15.0918f,-0.002f]
execute if score .this aj.fram matches 70 run data modify entity @s Pose.Head set value [90.0133f,-15.0804f,-0.0021f]
execute if score .this aj.fram matches 71 run data modify entity @s Pose.Head set value [90.012f,-15.0693f,-0.0022f]