#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 416 run tp @s ^0.375 ^0.037 ^0.096 ~ ~
execute if score .this aj.fram matches 417 run tp @s ^0.375 ^0.02 ^0.076 ~ ~
execute if score .this aj.fram matches 418 run tp @s ^0.375 ^0.004 ^0.057 ~ ~
execute if score .this aj.fram matches 419 run tp @s ^0.375 ^-0.013 ^0.038 ~ ~
execute if score .this aj.fram matches 420 run tp @s ^0.375 ^-0.029 ^0.018 ~ ~
execute if score .this aj.fram matches 421 run tp @s ^0.375 ^-0.046 ^-0.002 ~ ~
execute if score .this aj.fram matches 422 run tp @s ^0.375 ^-0.062 ^-0.022 ~ ~
execute if score .this aj.fram matches 423 run tp @s ^0.375 ^-0.078 ^-0.042 ~ ~