#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 184 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 185 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 186 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 187 run tp @s ^0.125 ^-1.369 ^0.386 ~ ~
execute if score .this aj.fram matches 188 run tp @s ^0.125 ^-1.361 ^0.4 ~ ~
execute if score .this aj.fram matches 189 run tp @s ^0.125 ^-1.368 ^0.417 ~ ~
execute if score .this aj.fram matches 190 run tp @s ^0.125 ^-1.388 ^0.404 ~ ~
execute if score .this aj.fram matches 191 run tp @s ^0.125 ^-1.406 ^0.399 ~ ~