#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 200 run data modify entity @s Pose.Head set value [90.0191f,-15.0244f,0.1175f]
execute if score .this aj.fram matches 201 run data modify entity @s Pose.Head set value [90.0199f,-15.0253f,0.1225f]
execute if score .this aj.fram matches 202 run data modify entity @s Pose.Head set value [90.0176f,-15.0215f,0.1042f]
execute if score .this aj.fram matches 203 run data modify entity @s Pose.Head set value [90.0136f,-15.0152f,0.0726f]
execute if score .this aj.fram matches 204 run data modify entity @s Pose.Head set value [90.009f,-15.0082f,0.0377f]
execute if score .this aj.fram matches 205 run data modify entity @s Pose.Head set value [90.0052f,-15.0026f,0.0094f]
execute if score .this aj.fram matches 206 run data modify entity @s Pose.Head set value [90.0034f,-15.0004f,-0.0023f]
execute if score .this aj.fram matches 207 run data modify entity @s Pose.Head set value [90.0049f,-15.0007f,-0.0024f]