#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 208 run data modify entity @s Pose.Head set value [-34.1029f,-22.2697f,-5.4774f]
execute if score .this aj.fram matches 209 run data modify entity @s Pose.Head set value [-34.1109f,-22.2744f,-5.4775f]
execute if score .this aj.fram matches 210 run data modify entity @s Pose.Head set value [-34.1219f,-22.281f,-5.4777f]
execute if score .this aj.fram matches 211 run data modify entity @s Pose.Head set value [-34.1359f,-22.2894f,-5.4779f]
execute if score .this aj.fram matches 212 run data modify entity @s Pose.Head set value [-34.1527f,-22.2995f,-5.4781f]
execute if score .this aj.fram matches 213 run data modify entity @s Pose.Head set value [-34.1723f,-22.3112f,-5.4784f]
execute if score .this aj.fram matches 214 run data modify entity @s Pose.Head set value [-34.1947f,-22.3246f,-5.4787f]
execute if score .this aj.fram matches 215 run data modify entity @s Pose.Head set value [-34.2196f,-22.3395f,-5.479f]