#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run data modify entity @s Pose.Head set value [-51.3223f,-0.6993f,-4.7217f]
execute if score .this aj.fram matches 145 run data modify entity @s Pose.Head set value [-54.3793f,-0.3878f,-4.9619f]
execute if score .this aj.fram matches 146 run data modify entity @s Pose.Head set value [-57.4308f,-0.0257f,-5.2181f]
execute if score .this aj.fram matches 147 run data modify entity @s Pose.Head set value [-60.4764f,0.386f,-5.4945f]
execute if score .this aj.fram matches 148 run data modify entity @s Pose.Head set value [-66.1419f,1.2106f,-6.1774f]
execute if score .this aj.fram matches 149 run data modify entity @s Pose.Head set value [-71.7999f,2.1127f,-6.9515f]
execute if score .this aj.fram matches 150 run data modify entity @s Pose.Head set value [-71.037f,2.1376f,-7.0498f]
execute if score .this aj.fram matches 151 run data modify entity @s Pose.Head set value [-70.2741f,2.1545f,-7.1473f]