#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run data modify entity @s Pose.Head set value [65.6931f,-0.1198f,-0.2207f]
execute if score .this aj.fram matches 65 run data modify entity @s Pose.Head set value [65.6876f,-0.1107f,-0.2044f]
execute if score .this aj.fram matches 66 run data modify entity @s Pose.Head set value [65.6789f,-0.1015f,-0.1877f]
execute if score .this aj.fram matches 67 run data modify entity @s Pose.Head set value [65.6668f,-0.0921f,-0.1707f]
execute if score .this aj.fram matches 68 run data modify entity @s Pose.Head set value [65.6513f,-0.0827f,-0.1536f]
execute if score .this aj.fram matches 69 run data modify entity @s Pose.Head set value [65.6321f,-0.0734f,-0.1366f]
execute if score .this aj.fram matches 70 run data modify entity @s Pose.Head set value [65.6093f,-0.0643f,-0.1198f]
execute if score .this aj.fram matches 71 run data modify entity @s Pose.Head set value [65.5826f,-0.0555f,-0.1034f]