#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 288 run data modify entity @s Pose.Head set value [-88.6683f,-0.0106f,-179.8096f]
execute if score .this aj.fram matches 289 run data modify entity @s Pose.Head set value [-86.4041f,-0.0108f,-179.8058f]
execute if score .this aj.fram matches 290 run data modify entity @s Pose.Head set value [-84.235f,-0.011f,-179.8023f]
execute if score .this aj.fram matches 291 run data modify entity @s Pose.Head set value [-82.1677f,-0.0111f,-179.7993f]
execute if score .this aj.fram matches 292 run data modify entity @s Pose.Head set value [-80.2092f,-0.0112f,-179.7966f]
execute if score .this aj.fram matches 293 run data modify entity @s Pose.Head set value [-78.3664f,-0.0113f,-179.7944f]
execute if score .this aj.fram matches 294 run data modify entity @s Pose.Head set value [-76.6462f,-0.0113f,-179.7927f]
execute if score .this aj.fram matches 295 run data modify entity @s Pose.Head set value [-75.0555f,-0.0114f,-179.7914f]