#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 256 run data modify entity @s Pose.Head set value [-169.956f,-0.0005f,-179.991f]
execute if score .this aj.fram matches 257 run data modify entity @s Pose.Head set value [-168.2986f,-0.0008f,-179.9872f]
execute if score .this aj.fram matches 258 run data modify entity @s Pose.Head set value [-166.5146f,-0.001f,-179.9831f]
execute if score .this aj.fram matches 259 run data modify entity @s Pose.Head set value [-164.6114f,-0.0013f,-179.9787f]
execute if score .this aj.fram matches 260 run data modify entity @s Pose.Head set value [-162.596f,-0.0015f,-179.974f]
execute if score .this aj.fram matches 261 run data modify entity @s Pose.Head set value [-160.4754f,-0.0018f,-179.969f]
execute if score .this aj.fram matches 262 run data modify entity @s Pose.Head set value [-158.2565f,-0.0022f,-179.9637f]
execute if score .this aj.fram matches 263 run data modify entity @s Pose.Head set value [-155.9461f,-0.0025f,-179.9582f]