#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 160 run data modify entity @s Pose.Head set value [80.1312f,0f,0f]
execute if score .this aj.fram matches 161 run data modify entity @s Pose.Head set value [80.0558f,0f,0f]
execute if score .this aj.fram matches 162 run data modify entity @s Pose.Head set value [79.7488f,0f,0f]
execute if score .this aj.fram matches 163 run data modify entity @s Pose.Head set value [79.1409f,0f,0f]
execute if score .this aj.fram matches 164 run data modify entity @s Pose.Head set value [78.4252f,0f,0f]
execute if score .this aj.fram matches 165 run data modify entity @s Pose.Head set value [77.8914f,0f,0f]
execute if score .this aj.fram matches 166 run data modify entity @s Pose.Head set value [77.9667f,0f,0f]
execute if score .this aj.fram matches 167 run data modify entity @s Pose.Head set value [78.669f,0f,0f]