#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 304 run data modify entity @s Pose.Head set value [-62.4555f,-0.0049f,-179.9062f]
execute if score .this aj.fram matches 305 run data modify entity @s Pose.Head set value [-63.0688f,-0.0036f,-179.9301f]
execute if score .this aj.fram matches 306 run data modify entity @s Pose.Head set value [-63.7368f,-0.0025f,-179.9525f]
execute if score .this aj.fram matches 307 run data modify entity @s Pose.Head set value [-64.3096f,-0.0014f,-179.9723f]
execute if score .this aj.fram matches 308 run data modify entity @s Pose.Head set value [-64.6373f,-0.0006f,-179.9885f]
execute if score .this aj.fram matches 309 run data modify entity @s Pose.Head set value [-64.5699f,0f,180f]
execute if score .this aj.fram matches 310 run data modify entity @s Pose.Head set value [-64.5832f,0f,180f]
execute if score .this aj.fram matches 311 run data modify entity @s Pose.Head set value [-64.5965f,0f,180f]