#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run tp @s ^-0.375 ^-1.353 ^0.194 ~ ~
execute if score .this aj.fram matches 89 run tp @s ^-0.375 ^-1.353 ^0.211 ~ ~
execute if score .this aj.fram matches 90 run tp @s ^-0.375 ^-1.352 ^0.23 ~ ~
execute if score .this aj.fram matches 91 run tp @s ^-0.375 ^-1.351 ^0.249 ~ ~
execute if score .this aj.fram matches 92 run tp @s ^-0.375 ^-1.349 ^0.269 ~ ~
execute if score .this aj.fram matches 93 run tp @s ^-0.375 ^-1.347 ^0.29 ~ ~
execute if score .this aj.fram matches 94 run tp @s ^-0.375 ^-1.343 ^0.311 ~ ~
execute if score .this aj.fram matches 95 run tp @s ^-0.375 ^-1.339 ^0.333 ~ ~