#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 272 run tp @s ^0.007 ^0.48 ^1.119 ~ ~
execute if score .this aj.fram matches 273 run tp @s ^0.007 ^0.507 ^1.06 ~ ~
execute if score .this aj.fram matches 274 run tp @s ^0.007 ^0.533 ^0.995 ~ ~
execute if score .this aj.fram matches 275 run tp @s ^0.007 ^0.556 ^0.926 ~ ~
execute if score .this aj.fram matches 276 run tp @s ^0.007 ^0.578 ^0.852 ~ ~
execute if score .this aj.fram matches 277 run tp @s ^0.006 ^0.598 ^0.775 ~ ~
execute if score .this aj.fram matches 278 run tp @s ^0.006 ^0.616 ^0.694 ~ ~
execute if score .this aj.fram matches 279 run tp @s ^0.006 ^0.633 ^0.61 ~ ~