#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 320 run data modify entity @s Pose.Head set value [-64.7123f,0f,180f]
execute if score .this aj.fram matches 321 run data modify entity @s Pose.Head set value [-64.7245f,0f,180f]
execute if score .this aj.fram matches 322 run data modify entity @s Pose.Head set value [-39.7365f,0f,180f]
execute if score .this aj.fram matches 323 run data modify entity @s Pose.Head set value [-15.6743f,0f,180f]
execute if score .this aj.fram matches 324 run data modify entity @s Pose.Head set value [13.9437f,0f,180f]
execute if score .this aj.fram matches 325 run data modify entity @s Pose.Head set value [35.2286f,0f,180f]
execute if score .this aj.fram matches 326 run data modify entity @s Pose.Head set value [35.2174f,0f,180f]
execute if score .this aj.fram matches 327 run data modify entity @s Pose.Head set value [35.2064f,0f,180f]