#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 336 run tp @s ^0 ^1.289 ^-0.717 ~ ~
execute if score .this aj.fram matches 337 run tp @s ^0 ^1.289 ^-0.717 ~ ~
execute if score .this aj.fram matches 338 run tp @s ^0 ^1.289 ^-0.717 ~ ~
execute if score .this aj.fram matches 339 run tp @s ^0 ^1.289 ^-0.717 ~ ~
execute if score .this aj.fram matches 340 run tp @s ^0 ^1.29 ^-0.716 ~ ~
execute if score .this aj.fram matches 341 run tp @s ^0 ^1.29 ^-0.716 ~ ~
execute if score .this aj.fram matches 342 run tp @s ^0 ^1.29 ^-0.716 ~ ~
execute if score .this aj.fram matches 343 run tp @s ^0 ^1.29 ^-0.716 ~ ~