#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 304 run data modify entity @s Pose.Head set value [-2.9972f,0f,0f]
execute if score .this aj.fram matches 305 run data modify entity @s Pose.Head set value [-2.9838f,0f,0f]
execute if score .this aj.fram matches 306 run data modify entity @s Pose.Head set value [-2.9704f,0f,0f]
execute if score .this aj.fram matches 307 run data modify entity @s Pose.Head set value [-2.9569f,0f,0f]
execute if score .this aj.fram matches 308 run data modify entity @s Pose.Head set value [-2.9435f,0f,0f]
execute if score .this aj.fram matches 309 run data modify entity @s Pose.Head set value [-2.9301f,0f,0f]
execute if score .this aj.fram matches 310 run data modify entity @s Pose.Head set value [-2.9168f,0f,0f]
execute if score .this aj.fram matches 311 run data modify entity @s Pose.Head set value [-2.9035f,0f,0f]