#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 344 run tp @s ^-0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 345 run tp @s ^-0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 346 run tp @s ^-0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 347 run tp @s ^-0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 348 run tp @s ^-0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 349 run tp @s ^-0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 350 run tp @s ^-0.125 ^-0.116 ^0.522 ~ ~
execute if score .this aj.fram matches 351 run tp @s ^-0.125 ^-0.116 ^0.522 ~ ~