#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run data modify entity @s Pose.Head set value [-35.2789f,22.4188f,5.0455f]
execute if score .this aj.fram matches 41 run data modify entity @s Pose.Head set value [-35.4487f,22.4403f,4.9833f]
execute if score .this aj.fram matches 42 run data modify entity @s Pose.Head set value [-35.5982f,22.4592f,4.9285f]
execute if score .this aj.fram matches 43 run data modify entity @s Pose.Head set value [-35.7281f,22.4755f,4.8808f]
execute if score .this aj.fram matches 44 run data modify entity @s Pose.Head set value [-35.8392f,22.4894f,4.8401f]
execute if score .this aj.fram matches 45 run data modify entity @s Pose.Head set value [-35.9323f,22.501f,4.8059f]
execute if score .this aj.fram matches 46 run data modify entity @s Pose.Head set value [-36.0083f,22.5104f,4.778f]
execute if score .this aj.fram matches 47 run data modify entity @s Pose.Head set value [-36.0679f,22.5178f,4.7561f]