#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 352 run tp @s ^-0.15 ^-0.49 ^0.527 ~ ~
execute if score .this aj.fram matches 353 run tp @s ^-0.149 ^-0.49 ^0.526 ~ ~
execute if score .this aj.fram matches 354 run tp @s ^-0.148 ^-0.49 ^0.525 ~ ~
execute if score .this aj.fram matches 355 run tp @s ^-0.146 ^-0.49 ^0.524 ~ ~
execute if score .this aj.fram matches 356 run tp @s ^-0.145 ^-0.49 ^0.523 ~ ~
execute if score .this aj.fram matches 357 run tp @s ^-0.144 ^-0.49 ^0.523 ~ ~
execute if score .this aj.fram matches 358 run tp @s ^-0.143 ^-0.49 ^0.522 ~ ~
execute if score .this aj.fram matches 359 run tp @s ^-0.143 ^-0.49 ^0.522 ~ ~