#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 208 run data modify entity @s Pose.Head set value [-34.1015f,22.2696f,5.4773f]
execute if score .this aj.fram matches 209 run data modify entity @s Pose.Head set value [-34.1076f,22.2742f,5.4773f]
execute if score .this aj.fram matches 210 run data modify entity @s Pose.Head set value [-34.1162f,22.2806f,5.4773f]
execute if score .this aj.fram matches 211 run data modify entity @s Pose.Head set value [-34.127f,22.2887f,5.4773f]
execute if score .this aj.fram matches 212 run data modify entity @s Pose.Head set value [-34.14f,22.2985f,5.4772f]
execute if score .this aj.fram matches 213 run data modify entity @s Pose.Head set value [-34.1551f,22.3099f,5.4772f]
execute if score .this aj.fram matches 214 run data modify entity @s Pose.Head set value [-34.1724f,22.3228f,5.4772f]
execute if score .this aj.fram matches 215 run data modify entity @s Pose.Head set value [-34.1917f,22.3373f,5.4771f]