#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 192 run data modify entity @s Pose.Head set value [-12.7719f,0f,0f]
execute if score .this aj.fram matches 193 run data modify entity @s Pose.Head set value [8.0406f,0f,0f]
execute if score .this aj.fram matches 194 run data modify entity @s Pose.Head set value [19.2384f,0f,0f]
execute if score .this aj.fram matches 195 run data modify entity @s Pose.Head set value [17.6039f,0f,0f]
execute if score .this aj.fram matches 196 run data modify entity @s Pose.Head set value [14.9144f,0f,0f]
execute if score .this aj.fram matches 197 run data modify entity @s Pose.Head set value [11.1937f,0f,0f]
execute if score .this aj.fram matches 198 run data modify entity @s Pose.Head set value [6.4656f,0f,0f]
execute if score .this aj.fram matches 199 run data modify entity @s Pose.Head set value [1.4867f,0f,0f]