#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 56 run data modify entity @s Pose.Head set value [90.0311f,15.233f,-0.0009f]
execute if score .this aj.fram matches 57 run data modify entity @s Pose.Head set value [90.0302f,15.2253f,-0.0007f]
execute if score .this aj.fram matches 58 run data modify entity @s Pose.Head set value [90.0293f,15.2167f,-0.0004f]
execute if score .this aj.fram matches 59 run data modify entity @s Pose.Head set value [90.0282f,15.2073f,-0.0001f]
execute if score .this aj.fram matches 60 run data modify entity @s Pose.Head set value [90.027f,15.1972f,0.0001f]
execute if score .this aj.fram matches 61 run data modify entity @s Pose.Head set value [90.0258f,15.1865f,0.0004f]
execute if score .this aj.fram matches 62 run data modify entity @s Pose.Head set value [90.0245f,15.1753f,0.0007f]
execute if score .this aj.fram matches 63 run data modify entity @s Pose.Head set value [90.0231f,15.1637f,0.0009f]