#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 200 run data modify entity @s Pose.Head set value [89.9775f,15.0234f,-0.1284f]
execute if score .this aj.fram matches 201 run data modify entity @s Pose.Head set value [89.9765f,15.0242f,-0.1338f]
execute if score .this aj.fram matches 202 run data modify entity @s Pose.Head set value [89.9806f,15.0207f,-0.1139f]
execute if score .this aj.fram matches 203 run data modify entity @s Pose.Head set value [89.9875f,15.0146f,-0.0794f]
execute if score .this aj.fram matches 204 run data modify entity @s Pose.Head set value [89.9951f,15.0079f,-0.0413f]
execute if score .this aj.fram matches 205 run data modify entity @s Pose.Head set value [90.0012f,15.0025f,-0.0105f]
execute if score .this aj.fram matches 206 run data modify entity @s Pose.Head set value [90.0034f,15.0004f,0.0023f]
execute if score .this aj.fram matches 207 run data modify entity @s Pose.Head set value [90.0053f,15.0007f,0.0024f]