#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 144 run data modify entity @s Pose.Head set value [-90.2383f,0f,0f]
execute if score .this aj.fram matches 145 run data modify entity @s Pose.Head set value [-90f,0f,0f]
execute if score .this aj.fram matches 146 run data modify entity @s Pose.Head set value [-90.0898f,0f,0f]
execute if score .this aj.fram matches 147 run data modify entity @s Pose.Head set value [-90.3687f,0f,0f]
execute if score .this aj.fram matches 148 run data modify entity @s Pose.Head set value [-90.6633f,0f,0f]
execute if score .this aj.fram matches 149 run data modify entity @s Pose.Head set value [-90.8f,0f,0f]
execute if score .this aj.fram matches 150 run data modify entity @s Pose.Head set value [-90.7313f,0f,0f]
execute if score .this aj.fram matches 151 run data modify entity @s Pose.Head set value [-90.55f,0f,0f]