#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 264 run data modify entity @s Pose.Head set value [93.1681f,15.4757f,0.2041f]
execute if score .this aj.fram matches 265 run data modify entity @s Pose.Head set value [93.2218f,15.4838f,0.2082f]
execute if score .this aj.fram matches 266 run data modify entity @s Pose.Head set value [93.2735f,15.4916f,0.2121f]
execute if score .this aj.fram matches 267 run data modify entity @s Pose.Head set value [93.3231f,15.4992f,0.2159f]
execute if score .this aj.fram matches 268 run data modify entity @s Pose.Head set value [93.3706f,15.5063f,0.2196f]
execute if score .this aj.fram matches 269 run data modify entity @s Pose.Head set value [93.4158f,15.5132f,0.2231f]
execute if score .this aj.fram matches 270 run data modify entity @s Pose.Head set value [93.4586f,15.5197f,0.2264f]
execute if score .this aj.fram matches 271 run data modify entity @s Pose.Head set value [93.4989f,15.5258f,0.2296f]