#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 248 run data modify entity @s Pose.Head set value [92.1193f,15.3177f,0.129f]
execute if score .this aj.fram matches 249 run data modify entity @s Pose.Head set value [92.1914f,15.3286f,0.1339f]
execute if score .this aj.fram matches 250 run data modify entity @s Pose.Head set value [92.2631f,15.3393f,0.1388f]
execute if score .this aj.fram matches 251 run data modify entity @s Pose.Head set value [92.3343f,15.35f,0.1437f]
execute if score .this aj.fram matches 252 run data modify entity @s Pose.Head set value [92.4048f,15.3607f,0.1486f]
execute if score .this aj.fram matches 253 run data modify entity @s Pose.Head set value [92.4746f,15.3712f,0.1535f]
execute if score .this aj.fram matches 254 run data modify entity @s Pose.Head set value [92.5437f,15.3816f,0.1584f]
execute if score .this aj.fram matches 255 run data modify entity @s Pose.Head set value [92.6118f,15.3918f,0.1632f]