#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 416 run data modify entity @s Pose.Head set value [-0.5938f,0f,0f]
execute if score .this aj.fram matches 417 run data modify entity @s Pose.Head set value [-0.3752f,0f,0f]
execute if score .this aj.fram matches 418 run data modify entity @s Pose.Head set value [-0.1455f,0f,0f]
execute if score .this aj.fram matches 419 run data modify entity @s Pose.Head set value [0.0998f,0f,0f]
execute if score .this aj.fram matches 420 run data modify entity @s Pose.Head set value [0.3651f,0f,0f]
execute if score .this aj.fram matches 421 run data modify entity @s Pose.Head set value [0.6549f,0f,0f]
execute if score .this aj.fram matches 422 run data modify entity @s Pose.Head set value [0.9737f,0f,0f]
execute if score .this aj.fram matches 423 run data modify entity @s Pose.Head set value [1.3259f,0f,0f]