#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 248 run tp @s ^-0.24 ^-1.661 ^0.597 ~ ~
execute if score .this aj.fram matches 249 run tp @s ^-0.24 ^-1.661 ^0.598 ~ ~
execute if score .this aj.fram matches 250 run tp @s ^-0.24 ^-1.661 ^0.598 ~ ~
execute if score .this aj.fram matches 251 run tp @s ^-0.241 ^-1.66 ^0.598 ~ ~
execute if score .this aj.fram matches 252 run tp @s ^-0.241 ^-1.66 ^0.598 ~ ~
execute if score .this aj.fram matches 253 run tp @s ^-0.241 ^-1.66 ^0.598 ~ ~
execute if score .this aj.fram matches 254 run tp @s ^-0.241 ^-1.66 ^0.598 ~ ~
execute if score .this aj.fram matches 255 run tp @s ^-0.242 ^-1.66 ^0.599 ~ ~