#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.125 ^-0.975 ^0.107 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.125 ^-0.973 ^0.133 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.125 ^-0.975 ^0.163 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.125 ^-0.985 ^0.194 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.125 ^-1 ^0.234 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.125 ^-1.047 ^0.359 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^-0.125 ^-1.125 ^0.484 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^-0.125 ^-1.219 ^0.57 ~ ~