#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 440 run tp @s ^-0.312 ^0.296 ^-0.031 ~ ~
execute if score .this aj.fram matches 441 run tp @s ^-0.312 ^0.296 ^-0.031 ~ ~
execute if score .this aj.fram matches 442 run tp @s ^-0.312 ^0.296 ^-0.031 ~ ~
execute if score .this aj.fram matches 443 run tp @s ^-0.312 ^0.117 ^-0.031 ~ ~
execute if score .this aj.fram matches 444 run tp @s ^-0.312 ^-0.062 ^-0.031 ~ ~
execute if score .this aj.fram matches 445 run tp @s ^-0.312 ^-0.241 ^-0.031 ~ ~
execute if score .this aj.fram matches 446 run tp @s ^-0.312 ^-0.236 ^-0.01 ~ ~
execute if score .this aj.fram matches 447 run tp @s ^-0.312 ^-0.232 ^0.01 ~ ~