#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 80 run data modify entity @s Pose.Head set value [1.2366f,0.0039f,-0.0068f]
execute if score .this aj.fram matches 81 run data modify entity @s Pose.Head set value [0.6544f,0.001f,-0.0017f]
execute if score .this aj.fram matches 82 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 83 run data modify entity @s Pose.Head set value [-0.9132f,0f,0f]
execute if score .this aj.fram matches 84 run data modify entity @s Pose.Head set value [-1.9383f,0f,0f]
execute if score .this aj.fram matches 85 run data modify entity @s Pose.Head set value [-3.0697f,0f,0f]
execute if score .this aj.fram matches 86 run data modify entity @s Pose.Head set value [-4.3016f,0f,0f]
execute if score .this aj.fram matches 87 run data modify entity @s Pose.Head set value [-5.6283f,0f,0f]