#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run tp @s ^-0.375 ^-1.013 ^0.246 ~ ~
execute if score .this aj.fram matches 89 run tp @s ^-0.375 ^-1.012 ^0.255 ~ ~
execute if score .this aj.fram matches 90 run tp @s ^-0.375 ^-1.011 ^0.264 ~ ~
execute if score .this aj.fram matches 91 run tp @s ^-0.375 ^-1.009 ^0.274 ~ ~
execute if score .this aj.fram matches 92 run tp @s ^-0.375 ^-1.006 ^0.283 ~ ~
execute if score .this aj.fram matches 93 run tp @s ^-0.375 ^-1.003 ^0.293 ~ ~
execute if score .this aj.fram matches 94 run tp @s ^-0.375 ^-1 ^0.304 ~ ~
execute if score .this aj.fram matches 95 run tp @s ^-0.375 ^-0.996 ^0.314 ~ ~