#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 88 run data modify entity @s Pose.Head set value [-7.044f,0f,0f]
execute if score .this aj.fram matches 89 run data modify entity @s Pose.Head set value [-8.543f,0f,0f]
execute if score .this aj.fram matches 90 run data modify entity @s Pose.Head set value [-10.1196f,0f,0f]
execute if score .this aj.fram matches 91 run data modify entity @s Pose.Head set value [-11.7679f,0f,0f]
execute if score .this aj.fram matches 92 run data modify entity @s Pose.Head set value [-13.4823f,0f,0f]
execute if score .this aj.fram matches 93 run data modify entity @s Pose.Head set value [-15.257f,0f,0f]
execute if score .this aj.fram matches 94 run data modify entity @s Pose.Head set value [-17.0863f,0f,0f]
execute if score .this aj.fram matches 95 run data modify entity @s Pose.Head set value [-18.9645f,0f,0f]