#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 344 run data modify entity @s Pose.Head set value [-1.5262f,-3.5334f,4.8839f]
execute if score .this aj.fram matches 345 run data modify entity @s Pose.Head set value [-1.4605f,-3.24f,4.8021f]
execute if score .this aj.fram matches 346 run data modify entity @s Pose.Head set value [-1.3779f,-2.8685f,4.6986f]
execute if score .this aj.fram matches 347 run data modify entity @s Pose.Head set value [-1.2811f,-2.4294f,4.5763f]
execute if score .this aj.fram matches 348 run data modify entity @s Pose.Head set value [-1.1727f,-1.9329f,4.4381f]
execute if score .this aj.fram matches 349 run data modify entity @s Pose.Head set value [-1.0554f,-1.3896f,4.287f]
execute if score .this aj.fram matches 350 run data modify entity @s Pose.Head set value [-0.9318f,-0.8098f,4.1259f]
execute if score .this aj.fram matches 351 run data modify entity @s Pose.Head set value [-0.8043f,-0.204f,3.9575f]