#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 288 run tp @s ^-0.245 ^-1.656 ^0.601 ~ ~
execute if score .this aj.fram matches 289 run tp @s ^-0.245 ^-1.657 ^0.601 ~ ~
execute if score .this aj.fram matches 290 run tp @s ^-0.245 ^-1.657 ^0.601 ~ ~
execute if score .this aj.fram matches 291 run tp @s ^-0.245 ^-1.657 ^0.601 ~ ~
execute if score .this aj.fram matches 292 run tp @s ^-0.244 ^-1.657 ^0.601 ~ ~
execute if score .this aj.fram matches 293 run tp @s ^-0.244 ^-1.657 ^0.601 ~ ~
execute if score .this aj.fram matches 294 run tp @s ^-0.244 ^-1.657 ^0.601 ~ ~
execute if score .this aj.fram matches 295 run tp @s ^-0.244 ^-1.657 ^0.601 ~ ~