#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run tp @s ^-0.373 ^-1.018 ^0.176 ~ ~
execute if score .this aj.fram matches 65 run tp @s ^-0.373 ^-1.018 ^0.176 ~ ~
execute if score .this aj.fram matches 66 run tp @s ^-0.373 ^-1.018 ^0.175 ~ ~
execute if score .this aj.fram matches 67 run tp @s ^-0.373 ^-1.017 ^0.175 ~ ~
execute if score .this aj.fram matches 68 run tp @s ^-0.373 ^-1.017 ^0.175 ~ ~
execute if score .this aj.fram matches 69 run tp @s ^-0.374 ^-1.017 ^0.175 ~ ~
execute if score .this aj.fram matches 70 run tp @s ^-0.374 ^-1.017 ^0.175 ~ ~
execute if score .this aj.fram matches 71 run tp @s ^-0.374 ^-1.017 ^0.176 ~ ~