#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 296 run tp @s ^-0.244 ^-1.657 ^0.601 ~ ~
execute if score .this aj.fram matches 297 run tp @s ^-0.244 ^-1.657 ^0.6 ~ ~
execute if score .this aj.fram matches 298 run tp @s ^-0.244 ^-1.658 ^0.6 ~ ~
execute if score .this aj.fram matches 299 run tp @s ^-0.243 ^-1.658 ^0.6 ~ ~
execute if score .this aj.fram matches 300 run tp @s ^-0.243 ^-1.658 ^0.6 ~ ~
execute if score .this aj.fram matches 301 run tp @s ^-0.243 ^-1.658 ^0.6 ~ ~
execute if score .this aj.fram matches 302 run tp @s ^-0.243 ^-1.659 ^0.6 ~ ~
execute if score .this aj.fram matches 303 run tp @s ^-0.242 ^-1.659 ^0.599 ~ ~