#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 192..199 run function emis:animations/dies/tree/right_leg2_display_192-199
execute if score .this aj.fram matches 200..207 run function emis:animations/dies/tree/right_leg2_display_200-207
execute if score .this aj.fram matches 208..215 run function emis:animations/dies/tree/right_leg2_display_208-215
execute if score .this aj.fram matches 216..223 run function emis:animations/dies/tree/right_leg2_display_216-223
execute if score .this aj.fram matches 224..231 run function emis:animations/dies/tree/right_leg2_display_224-231
execute if score .this aj.fram matches 232..239 run function emis:animations/dies/tree/right_leg2_display_232-239
execute if score .this aj.fram matches 240..247 run function emis:animations/dies/tree/right_leg2_display_240-247
execute if score .this aj.fram matches 248..255 run function emis:animations/dies/tree/right_leg2_display_248-255