#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 328 run data modify entity @s Pose.Head set value [34.4569f,4.6378f,6.3488f]
execute if score .this aj.fram matches 329 run data modify entity @s Pose.Head set value [35.8452f,4.7908f,6.2003f]
execute if score .this aj.fram matches 330 run data modify entity @s Pose.Head set value [37.0674f,4.9359f,6.091f]
execute if score .this aj.fram matches 331 run data modify entity @s Pose.Head set value [37.8694f,5.0354f,6.0308f]
execute if score .this aj.fram matches 332 run data modify entity @s Pose.Head set value [38.1887f,5.0758f,6.0096f]
execute if score .this aj.fram matches 333 run data modify entity @s Pose.Head set value [38.3129f,5.0916f,6.0017f]
execute if score .this aj.fram matches 334 run data modify entity @s Pose.Head set value [38.2951f,5.0894f,6.0028f]
execute if score .this aj.fram matches 335 run data modify entity @s Pose.Head set value [38.1887f,5.0758f,6.0096f]