#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 192 run data modify entity @s Pose.Head set value [-32.4376f,20.9057f,9.1982f]
execute if score .this aj.fram matches 193 run data modify entity @s Pose.Head set value [-33.1671f,21.6755f,7.5328f]
execute if score .this aj.fram matches 194 run data modify entity @s Pose.Head set value [-33.5046f,21.9813f,6.733f]
execute if score .this aj.fram matches 195 run data modify entity @s Pose.Head set value [-33.7386f,22.1382f,6.2086f]
execute if score .this aj.fram matches 196 run data modify entity @s Pose.Head set value [-33.8953f,22.2045f,5.8821f]
execute if score .this aj.fram matches 197 run data modify entity @s Pose.Head set value [-34.004f,22.2322f,5.668f]
execute if score .this aj.fram matches 198 run data modify entity @s Pose.Head set value [-34.0964f,22.2658f,5.4773f]
execute if score .this aj.fram matches 199 run data modify entity @s Pose.Head set value [-34.142f,22.2895f,5.3773f]