#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run data modify entity @s Pose.Head set value [3.1125f,0.2006f,-0.3541f]
execute if score .this aj.fram matches 65 run data modify entity @s Pose.Head set value [3.2889f,0.1853f,-0.3267f]
execute if score .this aj.fram matches 66 run data modify entity @s Pose.Head set value [3.4397f,0.1698f,-0.2989f]
execute if score .this aj.fram matches 67 run data modify entity @s Pose.Head set value [3.562f,0.1542f,-0.2711f]
execute if score .this aj.fram matches 68 run data modify entity @s Pose.Head set value [3.653f,0.1387f,-0.2434f]
execute if score .this aj.fram matches 69 run data modify entity @s Pose.Head set value [3.7098f,0.1234f,-0.2162f]
execute if score .this aj.fram matches 70 run data modify entity @s Pose.Head set value [3.7293f,0.1083f,-0.1895f]
execute if score .this aj.fram matches 71 run data modify entity @s Pose.Head set value [3.7087f,0.0937f,-0.1638f]