#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 64 run data modify entity @s Pose.Head set value [-35.3559f,22.4284f,5.0171f]
execute if score .this aj.fram matches 65 run data modify entity @s Pose.Head set value [-35.2585f,22.4161f,5.0528f]
execute if score .this aj.fram matches 66 run data modify entity @s Pose.Head set value [-35.1601f,22.4035f,5.0888f]
execute if score .this aj.fram matches 67 run data modify entity @s Pose.Head set value [-35.0614f,22.3909f,5.125f]
execute if score .this aj.fram matches 68 run data modify entity @s Pose.Head set value [-34.9632f,22.3783f,5.1609f]
execute if score .this aj.fram matches 69 run data modify entity @s Pose.Head set value [-34.8664f,22.3659f,5.1963f]
execute if score .this aj.fram matches 70 run data modify entity @s Pose.Head set value [-34.7717f,22.3537f,5.2308f]
execute if score .this aj.fram matches 71 run data modify entity @s Pose.Head set value [-34.68f,22.3419f,5.2643f]