#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 232 run data modify entity @s Pose.Head set value [90.9889f,15.1482f,0.0572f]
execute if score .this aj.fram matches 233 run data modify entity @s Pose.Head set value [91.0544f,15.158f,0.0611f]
execute if score .this aj.fram matches 234 run data modify entity @s Pose.Head set value [91.121f,15.168f,0.0651f]
execute if score .this aj.fram matches 235 run data modify entity @s Pose.Head set value [91.1887f,15.1781f,0.0692f]
execute if score .this aj.fram matches 236 run data modify entity @s Pose.Head set value [91.2573f,15.1884f,0.0734f]
execute if score .this aj.fram matches 237 run data modify entity @s Pose.Head set value [91.3268f,15.1988f,0.0776f]
execute if score .this aj.fram matches 238 run data modify entity @s Pose.Head set value [91.3971f,15.2094f,0.082f]
execute if score .this aj.fram matches 239 run data modify entity @s Pose.Head set value [91.468f,15.22f,0.0864f]