#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 552 run data modify entity @s Pose.Head set value [93.9802f,-29.7392f,-8.6375f]
execute if score .this aj.fram matches 553 run data modify entity @s Pose.Head set value [93.9802f,-29.7392f,-8.6375f]
execute if score .this aj.fram matches 554 run data modify entity @s Pose.Head set value [93.9802f,-29.7392f,-8.6375f]
execute if score .this aj.fram matches 555 run data modify entity @s Pose.Head set value [93.9802f,-29.7392f,-8.6375f]
execute if score .this aj.fram matches 556 run data modify entity @s Pose.Head set value [93.9802f,-29.7392f,-8.6375f]
execute if score .this aj.fram matches 557 run data modify entity @s Pose.Head set value [93.9802f,-29.7392f,-8.6375f]