#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 160 run data modify entity @s Pose.Head set value [-90f,0f,0f]
execute if score .this aj.fram matches 161 run data modify entity @s Pose.Head set value [-90.3544f,0f,0f]
execute if score .this aj.fram matches 162 run data modify entity @s Pose.Head set value [-90.7512f,0f,0f]
execute if score .this aj.fram matches 163 run data modify entity @s Pose.Head set value [-91.1208f,0f,0f]
execute if score .this aj.fram matches 164 run data modify entity @s Pose.Head set value [-91.3936f,0f,0f]
execute if score .this aj.fram matches 165 run data modify entity @s Pose.Head set value [-91.5f,0f,0f]
execute if score .this aj.fram matches 166 run data modify entity @s Pose.Head set value [-91.2333f,0f,0f]
execute if score .this aj.fram matches 167 run data modify entity @s Pose.Head set value [-90.6333f,0f,0f]