#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.emis.grab.loop matches 0 run function emis:animations/grab/stop
execute if score @s aj.emis.grab.loop matches 1 run function emis:animations/grab/pause
execute if score @s aj.emis.grab.loop matches 2 run function emis:animations/grab/zzz/execute/104