#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.emis.root] run function emis:animations/alts/zzz/conditional/132
execute if score #execute aj.i matches 0 run function emis:animations/alts/zzz/conditional/133