#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0.552 ^0.403 ^-0.031 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0.551 ^0.397 ^-0.038 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0.551 ^0.389 ^-0.038 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0.551 ^0.379 ^-0.031 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0.551 ^0.368 ^-0.019 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0.551 ^0.356 ^-0.005 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.552 ^0.344 ^0.011 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0.552 ^0.333 ^0.026 ~ ~