#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^0.552 ^1.008 ^-0.212 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^0.552 ^1.088 ^-0.183 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^0.552 ^1.166 ^-0.119 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^0.552 ^1.214 ^-0.035 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^0.552 ^1.212 ^0.048 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^0.552 ^1.152 ^0.109 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^0.55 ^0.913 ^0.166 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^0.546 ^0.548 ^0.214 ~ ~