#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [1.8207f,1.0241f,0f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [1.8434f,1.5362f,0f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [1.7069f,1.7922f,0f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [1.3769f,1.6898f,0f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [0.8193f,1.1265f,0f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [-8.6111f,2.7778f,0f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [-20f,1.3889f,0f]