#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0 ^-0.389 ^0.063 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0 ^-0.625 ^0.063 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0 ^-0.51 ^0.053 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0 ^-0.374 ^0.042 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0 ^-0.246 ^0.029 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0 ^-0.209 ^0.014 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0 ^-0.188 ^0 ~ ~