#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [-0.9728f,-63.6542f,0f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [-5f,-65f,0f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [-17.3148f,-65f,0f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [-34.6296f,-65f,0f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-50f,-65f,0f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-57.188f,-65.088f,0f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-63.964f,-65.264f,0f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-69.896f,-65.396f,0f]