#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.428 ^-1.301 ^0.138 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.431 ^-1.519 ^0.141 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.385 ^-1.454 ^0.207 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.314 ^-1.39 ^0.239 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^0.226 ^-1.349 ^0.209 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.146 ^-1.381 ^0.101 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.125 ^-1.375 ^0 ~ ~