#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run tp @s ^0.105 ^-0.702 ^-0.007 ~ ~
execute if score .this aj.fram matches 17 run tp @s ^0.129 ^-0.635 ^0.004 ~ ~
execute if score .this aj.fram matches 18 run tp @s ^0.2 ^-0.568 ^0.036 ~ ~
execute if score .this aj.fram matches 19 run tp @s ^0.292 ^-0.491 ^0.078 ~ ~
execute if score .this aj.fram matches 20 run tp @s ^0.36 ^-0.433 ^0.108 ~ ~
execute if score .this aj.fram matches 21 run tp @s ^0.385 ^-0.454 ^0.119 ~ ~
execute if score .this aj.fram matches 22 run tp @s ^0.405 ^-0.649 ^0.127 ~ ~
execute if score .this aj.fram matches 23 run tp @s ^0.419 ^-0.971 ^0.133 ~ ~