#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0.125 ^-1.375 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0.127 ^-1.381 ^0.013 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0.137 ^-1.388 ^0.033 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0.157 ^-1.394 ^0.053 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0.189 ^-1.398 ^0.067 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0.23 ^-1.4 ^0.068 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.271 ^-1.398 ^0.053 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0.306 ^-1.394 ^0.023 ~ ~