#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^-0.442 ^-0.204 ^0.488 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.435 ^-0.122 ^0.456 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.416 ^-0.059 ^0.41 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.389 ^-0.015 ^0.36 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^-0.359 ^0.015 ^0.321 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^-0.331 ^0.119 ^0.289 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^-0.311 ^0.425 ^0.242 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^-0.299 ^0.732 ^0.219 ~ ~