#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^-0.243 ^-1.099 ^0.47 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^-0.24 ^-1.373 ^0.48 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^-0.25 ^-1.366 ^0.46 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^-0.209 ^-1.369 ^0.403 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^-0.154 ^-1.36 ^0.282 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^-0.127 ^-1.384 ^0.126 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^-0.125 ^-1.375 ^0 ~ ~