#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 16 run data modify entity @s Pose.Head set value [177.6186f,28.6491f,-0.0692f]
execute if score .this aj.fram matches 17 run data modify entity @s Pose.Head set value [176.2521f,28.7454f,-0.0982f]
execute if score .this aj.fram matches 18 run data modify entity @s Pose.Head set value [176.7591f,28.0611f,-0.1174f]
execute if score .this aj.fram matches 19 run data modify entity @s Pose.Head set value [178.4368f,26.7137f,-0.1171f]
execute if score .this aj.fram matches 20 run data modify entity @s Pose.Head set value [-179.4163f,24.8207f,-0.0837f]
execute if score .this aj.fram matches 21 run data modify entity @s Pose.Head set value [-177.5f,22.5f,0f]
execute if score .this aj.fram matches 22 run data modify entity @s Pose.Head set value [-153.0729f,12.5212f,0.5627f]
execute if score .this aj.fram matches 23 run data modify entity @s Pose.Head set value [-128.6214f,2.5492f,1.3103f]