#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.312 ^-0.25 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.312 ^-0.256 ^0.019 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.311 ^-0.265 ^0.039 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.309 ^-0.275 ^0.06 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.306 ^-0.287 ^0.081 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.303 ^-0.299 ^0.102 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^-0.298 ^-0.311 ^0.123 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.293 ^-0.322 ^0.145 ~ ~