#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-105.85f,23.49f,0f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-100f,22.5f,0f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-83.36f,22.32f,0f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-60.78f,16.56f,0f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-36.52f,8.64f,0f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-14.84f,1.98f,0f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [0f,0f,0f]