#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0..7 run function emis:animations/b_tp/tree/left_arm_display_0-7
execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [-20f,-8f,0f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [-10f,-4f,0f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [0f,0f,0f]