#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0.375 ^-0.625 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0.379 ^-0.62 ^-0.052 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0.392 ^-0.603 ^-0.107 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0.413 ^-0.575 ^-0.167 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0.439 ^-0.538 ^-0.236 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0.469 ^-0.492 ^-0.314 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.439 ^-0.538 ^0.214 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0.413 ^-0.575 ^0.17 ~ ~