#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [67.5f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [56.4049f,3.9643f,-0.544f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [45.3099f,7.9287f,-1.088f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [34.2148f,11.893f,-1.632f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [23.1197f,15.8574f,-2.176f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [12.0247f,19.8217f,-2.7199f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [23.1197f,15.8574f,-2.176f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [34.2148f,11.893f,-1.632f]