#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0..7 run function emis:animations/b_tp/tree/right_leg2_root_0-7
execute if score .this aj.fram matches 8 run tp @s ^-0.157 ^-1.368 ^0.065 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^-0.141 ^-1.374 ^0.033 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^-0.125 ^-1.375 ^0 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^-0.125 ^-1.375 ^0 ~ ~