#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.emis.root] at @s run function emis:animations/ring/zzz/conditional/28
execute if score #execute aj.i matches 0 run function emis:animations/ring/zzz/conditional/29