#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.552 ^0.326 ^-0.031 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.552 ^0.316 ^-0.031 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.552 ^0.307 ^-0.031 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.552 ^0.299 ^-0.031 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.552 ^0.294 ^-0.031 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.552 ^0.294 ^-0.031 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.552 ^0.294 ^-0.031 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.552 ^0.294 ^-0.031 ~ ~