#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [-2.3177f,-2.3177f,0f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [-5.4167f,-5.4167f,0f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [-9.1406f,-9.1406f,0f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [-13.3333f,-13.3333f,0f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [-17.8385f,-17.8385f,0f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [-22.5f,-22.5f,0f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [-27.1615f,-27.1615f,0f]