#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^0.375 ^-0.625 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^0.393 ^-0.627 ^0.009 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^0.416 ^-0.626 ^0.018 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^0.441 ^-0.621 ^0.026 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^0.465 ^-0.612 ^0.03 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^0.486 ^-0.599 ^0.031 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.5 ^-0.585 ^0.028 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0.507 ^-0.572 ^0.022 ~ ~