#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^0.471 ^-0.559 ^-0.015 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^0.327 ^-0.493 ^0.044 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^0.151 ^-0.428 ^0.091 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^0.013 ^-0.491 ^-0.006 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^-0.02 ^-0.556 ^-0.129 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^0.151 ^-0.528 ^-0.009 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^0.304 ^-0.55 ^0.043 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^0.386 ^-0.601 ^0.036 ~ ~