#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run tp @s ^0.21 ^-1.397 ^0.102 ~ ~
execute if score .this aj.fram matches 9 run tp @s ^0.23 ^-1.392 ^0.105 ~ ~
execute if score .this aj.fram matches 10 run tp @s ^0.249 ^-1.386 ^0.105 ~ ~
execute if score .this aj.fram matches 11 run tp @s ^0.264 ^-1.38 ^0.102 ~ ~
execute if score .this aj.fram matches 12 run tp @s ^0.276 ^-1.375 ^0.099 ~ ~
execute if score .this aj.fram matches 13 run tp @s ^0.276 ^-1.375 ^0.099 ~ ~
execute if score .this aj.fram matches 14 run tp @s ^0.276 ^-1.375 ^0.099 ~ ~
execute if score .this aj.fram matches 15 run tp @s ^0.276 ^-1.375 ^0.099 ~ ~