#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.375 ^-0.968 ^0.025 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.365 ^-1.007 ^0.099 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.34 ^-1.05 ^0.203 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.29 ^-1.088 ^0.333 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.209 ^-1.111 ^0.478 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.091 ^-1.109 ^0.625 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^0.06 ^-1.078 ^0.758 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^0.236 ^-1.015 ^0.862 ~ ~