#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.375 ^-0.625 ^0 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.374 ^-0.631 ^0.029 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.37 ^-0.637 ^0.069 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.361 ^-0.643 ^0.115 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.346 ^-0.649 ^0.166 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.324 ^-0.653 ^0.218 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^-0.294 ^-0.655 ^0.269 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.26 ^-0.655 ^0.316 ~ ~