#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 8 run data modify entity @s Pose.Head set value [19.3519f,-35.1852f,0f]
execute if score .this aj.fram matches 9 run data modify entity @s Pose.Head set value [21.9141f,-39.8437f,0f]
execute if score .this aj.fram matches 10 run data modify entity @s Pose.Head set value [24.1898f,-43.9815f,0f]
execute if score .this aj.fram matches 11 run data modify entity @s Pose.Head set value [26.0836f,-47.4248f,0f]
execute if score .this aj.fram matches 12 run data modify entity @s Pose.Head set value [27.5f,-50f,0f]
execute if score .this aj.fram matches 13 run data modify entity @s Pose.Head set value [27.5f,-50f,0f]
execute if score .this aj.fram matches 14 run data modify entity @s Pose.Head set value [27.5f,-50f,0f]
execute if score .this aj.fram matches 15 run data modify entity @s Pose.Head set value [27.5f,-50f,0f]