#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run tp @s ^0.125 ^-1 ^-0.029 ~ ~
execute if score .this aj.fram matches 49 run tp @s ^0.125 ^-1 ^-0.023 ~ ~
execute if score .this aj.fram matches 50 run tp @s ^0.125 ^-1 ^-0.019 ~ ~
execute if score .this aj.fram matches 51 run tp @s ^0.125 ^-1 ^-0.014 ~ ~
execute if score .this aj.fram matches 52 run tp @s ^0.125 ^-1 ^-0.009 ~ ~
execute if score .this aj.fram matches 53 run tp @s ^0.125 ^-1 ^-0.006 ~ ~
execute if score .this aj.fram matches 54 run tp @s ^0.125 ^-1 ^-0.002 ~ ~
execute if score .this aj.fram matches 55 run tp @s ^0.125 ^-1 ^0 ~ ~