#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-73.2611f,-59.3262f,-101.719f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-73.4291f,-61.717f,-102.9801f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [-73.5029f,-63.3863f,-103.9162f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-73.427f,-64.2676f,-104.5267f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [-73.1723f,-64.2935f,-104.7852f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [-72.7482f,-63.3953f,-104.6269f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [-72.1995f,-61.5041f,-103.9518f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [-71.5855f,-58.5506f,-102.6457f]