#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 48 run data modify entity @s Pose.Head set value [-55.4533f,37.853f,-26.3657f]
execute if score .this aj.fram matches 49 run data modify entity @s Pose.Head set value [-49.8838f,32.7468f,-21.5704f]
execute if score .this aj.fram matches 50 run data modify entity @s Pose.Head set value [-44.0085f,26.6463f,-16.9999f]
execute if score .this aj.fram matches 51 run data modify entity @s Pose.Head set value [-38.104f,20.0911f,-12.7209f]
execute if score .this aj.fram matches 52 run data modify entity @s Pose.Head set value [-32.4558f,13.6176f,-8.806f]
execute if score .this aj.fram matches 53 run data modify entity @s Pose.Head set value [-27.3566f,7.7584f,-5.3304f]
execute if score .this aj.fram matches 54 run data modify entity @s Pose.Head set value [-23.1042f,3.0434f,-2.37f]
execute if score .this aj.fram matches 55 run data modify entity @s Pose.Head set value [-20f,0f,0f]