#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-7.2869f,-8.2156f,-1.2093f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-7.2597f,-7.0297f,-1.3638f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-7.234f,-5.9099f,-1.5096f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-7.2104f,-4.8827f,-1.6434f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-7.1896f,-3.9745f,-1.7617f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-7.1721f,-3.2119f,-1.8611f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-7.1585f,-2.6211f,-1.938f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-7.1769f,-2.0303f,-2.0252f]