#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-72.4913f,-23.5507f,-81.5984f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-72.5105f,-29.6653f,-85.2151f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-72.5569f,-35.4511f,-88.5814f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-72.6315f,-40.7747f,-91.6231f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-72.7269f,-45.5031f,-94.274f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-72.8237f,-49.5036f,-96.4801f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-72.889f,-52.6439f,-98.2009f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-73.0617f,-56.28f,-100.1262f]