#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 40 run tp @s ^0.14 ^-1.372 ^-0.016 ~ ~
execute if score .this aj.fram matches 41 run tp @s ^0.139 ^-1.373 ^-0.015 ~ ~
execute if score .this aj.fram matches 42 run tp @s ^0.138 ^-1.373 ^-0.014 ~ ~
execute if score .this aj.fram matches 43 run tp @s ^0.137 ^-1.373 ^-0.013 ~ ~
execute if score .this aj.fram matches 44 run tp @s ^0.136 ^-1.374 ^-0.012 ~ ~
execute if score .this aj.fram matches 45 run tp @s ^0.135 ^-1.374 ^-0.011 ~ ~
execute if score .this aj.fram matches 46 run tp @s ^0.134 ^-1.374 ^-0.01 ~ ~
execute if score .this aj.fram matches 47 run tp @s ^0.132 ^-1.375 ^-0.008 ~ ~