#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [67.5f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [62.7603f,-2.198f,4.6873f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [56.057f,-5.1732f,11.0423f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [47.8723f,-8.7037f,18.6329f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [38.6967f,-12.5801f,27.022f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [29.0299f,-16.6062f,35.7715f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [19.3774f,-20.5956f,44.4481f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [10.2445f,-24.3662f,52.6289f]