#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^-0.567 ^0.394 ^0.132 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^-0.565 ^0.403 ^0.1 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^-0.565 ^0.407 ^0.079 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^-0.565 ^0.409 ^0.07 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^-0.568 ^0.407 ^0.072 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^-0.572 ^0.402 ^0.087 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^-0.578 ^0.392 ^0.115 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^-0.586 ^0.377 ^0.155 ~ ~