#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [0.72f,27.585f,81.5135f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [1.7846f,35.0764f,83.0556f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [2.888f,42.1602f,84.5818f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [4.0337f,48.6739f,86.0754f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [5.2218f,54.4552f,87.5171f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [6.4395f,59.3418f,88.8751f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [7.6442f,63.172f,90.0885f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [9.165f,67.5356f,91.6934f]