#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run tp @s ^-0.375 ^-0.968 ^0.025 ~ ~
execute if score .this aj.fram matches 1 run tp @s ^-0.428 ^-0.956 ^0.088 ~ ~
execute if score .this aj.fram matches 2 run tp @s ^-0.489 ^-0.927 ^0.175 ~ ~
execute if score .this aj.fram matches 3 run tp @s ^-0.54 ^-0.875 ^0.274 ~ ~
execute if score .this aj.fram matches 4 run tp @s ^-0.566 ^-0.808 ^0.376 ~ ~
execute if score .this aj.fram matches 5 run tp @s ^-0.559 ^-0.736 ^0.466 ~ ~
execute if score .this aj.fram matches 6 run tp @s ^-0.521 ^-0.674 ^0.537 ~ ~
execute if score .this aj.fram matches 7 run tp @s ^-0.463 ^-0.632 ^0.583 ~ ~