#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run data modify entity @s Pose.Head set value [-86.78f,27.585f,81.5135f]
execute if score .this aj.fram matches 25 run data modify entity @s Pose.Head set value [-85.7154f,35.0764f,83.0556f]
execute if score .this aj.fram matches 26 run data modify entity @s Pose.Head set value [-84.612f,42.1602f,84.5818f]
execute if score .this aj.fram matches 27 run data modify entity @s Pose.Head set value [-83.4663f,48.6739f,86.0754f]
execute if score .this aj.fram matches 28 run data modify entity @s Pose.Head set value [-82.2782f,54.4552f,87.5171f]
execute if score .this aj.fram matches 29 run data modify entity @s Pose.Head set value [-81.0605f,59.3418f,88.8751f]
execute if score .this aj.fram matches 30 run data modify entity @s Pose.Head set value [-79.8558f,63.172f,90.0885f]
execute if score .this aj.fram matches 31 run data modify entity @s Pose.Head set value [-78.335f,67.5356f,91.6934f]