#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 24 run tp @s ^-0.146 ^-1.375 ^-0.037 ~ ~
execute if score .this aj.fram matches 25 run tp @s ^-0.148 ^-1.374 ^-0.033 ~ ~
execute if score .this aj.fram matches 26 run tp @s ^-0.149 ^-1.374 ^-0.028 ~ ~
execute if score .this aj.fram matches 27 run tp @s ^-0.15 ^-1.373 ^-0.025 ~ ~
execute if score .this aj.fram matches 28 run tp @s ^-0.151 ^-1.373 ^-0.021 ~ ~
execute if score .this aj.fram matches 29 run tp @s ^-0.152 ^-1.372 ^-0.019 ~ ~
execute if score .this aj.fram matches 30 run tp @s ^-0.153 ^-1.372 ^-0.017 ~ ~
execute if score .this aj.fram matches 31 run tp @s ^-0.154 ^-1.371 ^-0.016 ~ ~