#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.fram matches 1 run data modify entity @s Pose.Head set value [-5.1757f,-2.2181f,4.4658f]
execute if score .this aj.fram matches 2 run data modify entity @s Pose.Head set value [-12.2922f,-5.2679f,10.6062f]
execute if score .this aj.fram matches 3 run data modify entity @s Pose.Head set value [-20.8644f,-8.9416f,18.0027f]
execute if score .this aj.fram matches 4 run data modify entity @s Pose.Head set value [-30.407f,-13.0312f,26.2365f]
execute if score .this aj.fram matches 5 run data modify entity @s Pose.Head set value [-40.4348f,-17.3287f,34.889f]
execute if score .this aj.fram matches 6 run data modify entity @s Pose.Head set value [-50.4626f,-21.6263f,43.5414f]
execute if score .this aj.fram matches 7 run data modify entity @s Pose.Head set value [-60.0053f,-25.7159f,51.7752f]