#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run tp @s ^-0.154 ^-1.371 ^-0.016 ~ ~
execute if score .this aj.fram matches 33 run tp @s ^-0.155 ^-1.37 ^-0.016 ~ ~
execute if score .this aj.fram matches 34 run tp @s ^-0.156 ^-1.37 ^-0.016 ~ ~
execute if score .this aj.fram matches 35 run tp @s ^-0.156 ^-1.37 ^-0.017 ~ ~
execute if score .this aj.fram matches 36 run tp @s ^-0.156 ^-1.37 ^-0.017 ~ ~
execute if score .this aj.fram matches 37 run tp @s ^-0.156 ^-1.371 ^-0.017 ~ ~
execute if score .this aj.fram matches 38 run tp @s ^-0.155 ^-1.371 ^-0.017 ~ ~
execute if score .this aj.fram matches 39 run tp @s ^-0.154 ^-1.371 ^-0.017 ~ ~