#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.fram matches 32 run data modify entity @s Pose.Head set value [-75.893f,64.247f,87.9701f]
execute if score .this aj.fram matches 33 run data modify entity @s Pose.Head set value [-75.8078f,66.7226f,88.4359f]
execute if score .this aj.fram matches 34 run data modify entity @s Pose.Head set value [-75.7709f,68.2965f,88.7366f]
execute if score .this aj.fram matches 35 run data modify entity @s Pose.Head set value [-75.7764f,68.9319f,88.8634f]
execute if score .this aj.fram matches 36 run data modify entity @s Pose.Head set value [-75.8184f,68.5918f,88.8074f]
execute if score .this aj.fram matches 37 run data modify entity @s Pose.Head set value [-75.891f,67.2393f,88.5598f]
execute if score .this aj.fram matches 38 run data modify entity @s Pose.Head set value [-75.9881f,64.8375f,88.1118f]
execute if score .this aj.fram matches 39 run data modify entity @s Pose.Head set value [-76.1038f,61.3496f,87.4544f]